"use client";
import{useState}from"react";
type Q={id:string;questionType:string;stem:Record<string,unknown>;marks:number;order:number};
type Feedback={correct:boolean;feedback:string;score:number;maxScore:number};
export function QuestionRunner({questions,setId}:{questions:Q[];setId?:string}){
 const[index,setIndex]=useState(0),[answer,setAnswer]=useState(""),[feedback,setFeedback]=useState<Feedback|null>(null),[busy,setBusy]=useState(false),[complete,setComplete]=useState(false),[error,setError]=useState("");const q=questions[index];
 if(!q)return <div className="emptyState">No published questions in this set.</div>;
 const options=Array.isArray(q.stem.options)?q.stem.options.filter((x):x is string=>typeof x==="string"):[];
 async function submit(){setBusy(true);setError("");const response=options.length?{option:answer}:{text:answer};const r=await fetch("/api/student/paper2/attempt",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({questionId:q.id,response,setId})});const b=await r.json().catch(()=>({}))as{correct?:boolean;feedback?:string;score?:number;maxScore?:number;error?:string};setBusy(false);if(!r.ok){setError(b.error||"Could not check answer");return;}const next={correct:Boolean(b.correct),feedback:b.feedback||"",score:b.score||0,maxScore:b.maxScore||q.marks};setFeedback(next);if(next.correct&&index===questions.length-1&&setId){const done=await fetch(`/api/student/practice/${encodeURIComponent(setId)}/complete`,{method:"POST"}),body=await done.json().catch(()=>({}))as{error?:string};if(done.ok)setComplete(true);else setError(body.error||"Could not complete reading practice");}}
 function change(value:string){setAnswer(value);if(feedback&&!feedback.correct)setFeedback(null);}
 function next(){if(!feedback?.correct)return;setIndex(index+1);setAnswer("");setFeedback(null);setError("");}
 return <section className="card readingGate paper2Gate"><div className="cardHeader"><h2>Question {index+1} of {questions.length}</h2><span>{q.questionType.replaceAll("_"," ")}</span></div><p className="bankPrompt">{String(q.stem.prompt||"")}</p>{options.length?<div className="optionList">{options.map(o=><label className={answer===o?"optionRow selected":"optionRow"} key={o}><input type="radio" name={`q-${q.id}`} disabled={Boolean(feedback?.correct)} checked={answer===o} onChange={()=>change(o)}/><span>{o}</span></label>)}</div>:<textarea className="answerArea" disabled={Boolean(feedback?.correct)} value={answer} onChange={e=>change(e.target.value)} placeholder="Type your answer"/>}{feedback&&<div className={feedback.correct?"notice successNotice":"notice warnNotice"}><strong>{feedback.correct?"Correct — next question unlocked":"Not correct yet — try again"}</strong> · {feedback.score}/{feedback.maxScore}<div>{feedback.feedback}</div></div>}{feedback&&!feedback.correct&&<div className="notice warnNotice">You must answer this question correctly before moving on.</div>}{error&&<div className="notice errorNotice">{error}</div>}{complete&&<div className="notice successNotice"><strong>Reading passed.</strong> Every question in this set is correct, so today&apos;s Reading task is complete.</div>}<div className="rowActions readingGateActions"><button className="button primary" disabled={busy||!answer.trim()||Boolean(feedback?.correct)} onClick={()=>void submit()}>{busy?"Checking…":feedback&&!feedback.correct?"Check revised answer":"Check answer"}</button>{feedback?.correct&&index<questions.length-1&&<button className="button secondary" onClick={next}>Next question →</button>}</div></section>;
}
