PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO content_sources (id,name,source_type,base_url,allowed_host,topic,usage_mode,enabled) VALUES
('src-nasa-jpl','NASA JPL News','rss','https://www.jpl.nasa.gov/feeds/news/','jpl.nasa.gov','Science & Space','reference_only',1),
('src-sg-nea','Singapore NEA News','rss','https://www.nea.gov.sg/rss/news_update','nea.gov.sg','Environment & Singapore','reference_only',1),
('src-sg-sfa','Singapore Food Agency Newsroom','rss','https://www.sfa.gov.sg/rss/newsroom','sfa.gov.sg','Food & Singapore','reference_only',1);

INSERT OR IGNORE INTO content_items (id,content_type,title,school_level,topic,status,active_version,description,source_attribution,published_at)
VALUES
('starter-mangroves','article','How Mangroves Protect a Coastline','P6','Environment','published',1,'A guided reading on how mangrove roots, mud and wildlife work together.','English Mastery original learning material',CURRENT_TIMESTAMP),
('starter-space-exercise','article','Why Astronauts Exercise in Space','P6','Science & Space','published',1,'A science reading about muscles, bones and daily exercise in microgravity.','English Mastery original learning material',CURRENT_TIMESTAMP),
('starter-hawker-waste','article','Small Choices, Less Food Waste','P5','Singapore & Community','published',1,'A Singapore-focused reading about practical ways to reduce food waste.','English Mastery original learning material',CURRENT_TIMESTAMP);

INSERT OR IGNORE INTO content_versions (id,content_id,version,body_json,curriculum_version_id,review_status) VALUES
('starter-mangroves-v1','starter-mangroves',1,'{"summary":"Mangroves protect coastlines while supporting a rich ecosystem.","readingTime":7,"paragraphs":["Mangroves grow where land and sea meet. Their roots spread through soft mud and slow down waves before the water reaches the shore. During rough weather, this can reduce the force of moving water and help protect the coastline from erosion.","The roots also trap mud and small pieces of organic matter. Over time, this material can build up around the trees. The calmer water provides shelter for young fish, crabs and other animals that might struggle in stronger currents.","Mangroves are valuable, but they are not an excuse to ignore other forms of coastal protection. Scientists and planners often study local conditions before deciding how natural habitats and engineering should work together.","For communities, protecting mangroves can therefore serve two purposes: it supports wildlife and can strengthen the resilience of coastal areas. The challenge is to balance human needs with the health of the habitat."],"vocabulary":[{"word":"erosion","pos":"noun","definition":"the gradual wearing away of soil or rock","simple":"when land is slowly worn away","example":"Mangrove roots can reduce coastal erosion."},{"word":"resilience","pos":"noun","definition":"the ability to recover or remain strong when conditions are difficult","simple":"the ability to cope and recover","example":"Healthy habitats can improve coastal resilience."}],"sourceNote":"Original educational text created for P6 English practice."}','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved'),
('starter-space-exercise-v1','starter-space-exercise',1,'{"summary":"Astronauts exercise every day to protect their bodies in microgravity.","readingTime":7,"paragraphs":["On Earth, our muscles and bones constantly work against gravity. Even simple actions such as standing and walking place weight on the body. In space, astronauts experience microgravity, so their bodies do not receive the same daily physical load.","Without regular exercise, muscles can become weaker and bones can lose some of their strength. Astronauts therefore follow a carefully planned exercise routine. They use special equipment that allows them to run, cycle and perform resistance exercises while staying safely attached.","Exercise in space is not only about fitness. It is part of preparing astronauts to work effectively during a mission and to return safely to Earth. A person who has spent months in microgravity must readapt to normal gravity after landing.","Researchers study these changes because long missions may take people farther from Earth in the future. Understanding how the human body responds to space helps scientists improve training, equipment and health plans."],"vocabulary":[{"word":"resistance","pos":"noun","definition":"a force that makes movement more difficult","simple":"a force you push or pull against","example":"Resistance exercise helps astronauts maintain muscle strength."},{"word":"readapt","pos":"verb","definition":"to become used to a situation again","simple":"to get used to something again","example":"Astronauts must readapt to Earth gravity."}],"sourceNote":"Original educational text created for P6 English practice."}','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved'),
('starter-hawker-waste-v1','starter-hawker-waste',1,'{"summary":"Reducing food waste starts with practical choices before and during a meal.","readingTime":6,"paragraphs":["A busy hawker centre offers many choices, and it can be tempting to order more food than we need. However, uneaten food requires resources to produce, transport and prepare. When it is thrown away, those resources are wasted as well.","One simple habit is to think about portion size before ordering. A child who knows that a full plate is too much can ask for less rice or choose one main dish instead of several side dishes. Families can also share food when portions are large.","Reducing waste does not mean that people should force themselves to eat when they are already full. The better approach is to plan more carefully. This makes the decision before the food becomes waste.","Small choices may seem unimportant, but repeated habits can have a wider effect. When many people order thoughtfully, less food is discarded and the community uses resources more responsibly."],"vocabulary":[{"word":"portion","pos":"noun","definition":"an amount of food served to one person","simple":"how much food is served","example":"He asked for a smaller portion of rice."},{"word":"discarded","pos":"verb","definition":"thrown away because something is no longer wanted","simple":"thrown away","example":"Less food is discarded when people plan carefully."}],"sourceNote":"Original educational text created for P5 English practice."}','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved');

INSERT OR IGNORE INTO content_skills (content_id,skill_id,coverage) VALUES
('starter-mangroves','R-INFER',1),('starter-mangroves','R-EVIDENCE',1),('starter-mangroves','R-VOCAB',0.8),
('starter-space-exercise','R-INFER',1),('starter-space-exercise','R-EVIDENCE',1),('starter-space-exercise','R-VOCAB',0.8),
('starter-hawker-waste','R-LITERAL',1),('starter-hawker-waste','R-INFER',0.8),('starter-hawker-waste','R-VOCAB',0.8);

INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,marks) VALUES
('q-mangrove-1','multiple_choice','P6',2,'{"prompt":"What is one direct way mangrove roots protect a coastline?","options":["They make seawater warmer.","They slow down waves before they reach the shore.","They remove all mud from the coast.","They stop every storm from forming."]}','{"correctOption":1}','{"text":"The first paragraph states that the roots slow down waves, reducing the force of moving water."}','published','starter-mangroves','SG-PRIMARY-ENGLISH-2020-PSLE-2026',1),
('q-mangrove-2','short_answer','P6',3,'{"prompt":"Why does the passage say mangroves can serve two purposes for communities?"}','{"acceptedKeywords":["wildlife","coast","coastal","protect","resilience"],"modelAnswer":"They support wildlife while also helping coastal areas become more resilient to waves and erosion."}','{"text":"A complete answer should identify both the ecological and coastal-protection benefits."}','published','starter-mangroves','SG-PRIMARY-ENGLISH-2020-PSLE-2026',2),
('q-space-1','multiple_choice','P6',2,'{"prompt":"Why can astronauts lose muscle and bone strength in space?","options":["They cannot eat in space.","Microgravity reduces the normal physical load on the body.","Spacecraft are too cold for exercise.","Astronauts are not allowed to stand."]}','{"correctOption":1}','{"text":"The passage explains that the body does not work against gravity in the usual way."}','published','starter-space-exercise','SG-PRIMARY-ENGLISH-2020-PSLE-2026',1),
('q-space-2','short_answer','P6',3,'{"prompt":"How does exercise help astronauts beyond simply keeping them fit?"}','{"acceptedKeywords":["mission","work","return","Earth","readapt","gravity"],"modelAnswer":"It helps them work effectively during missions and prepares their bodies to return and readapt to Earth gravity."}','{"text":"Use information from the third paragraph."}','published','starter-space-exercise','SG-PRIMARY-ENGLISH-2020-PSLE-2026',2),
('q-waste-1','multiple_choice','P5',2,'{"prompt":"What does the writer suggest doing before food becomes waste?","options":["Order extra food in case someone is hungry.","Plan the portion and amount of food more carefully.","Finish every meal even when full.","Avoid eating at hawker centres."]}','{"correctOption":1}','{"text":"The passage emphasises planning before ordering instead of forcing oneself to finish too much food."}','published','starter-hawker-waste','SG-PRIMARY-ENGLISH-2020-PSLE-2026',1),
('q-waste-2','short_answer','P5',2,'{"prompt":"Why can small choices have a wider effect?"}','{"acceptedKeywords":["many","people","habits","less","food","discarded","resources"],"modelAnswer":"When many people repeat thoughtful habits, less food is discarded and fewer resources are wasted."}','{"text":"The final paragraph links individual habits with community-level impact."}','published','starter-hawker-waste','SG-PRIMARY-ENGLISH-2020-PSLE-2026',2);

INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES
('q-mangrove-1','R-LITERAL',1),('q-mangrove-2','R-INFER',1),('q-mangrove-2','R-EVIDENCE',1),
('q-space-1','R-LITERAL',1),('q-space-2','R-INFER',1),('q-space-2','R-EVIDENCE',1),
('q-waste-1','R-LITERAL',1),('q-waste-2','R-INFER',1);
