PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS question_bank_sources (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  provider TEXT NOT NULL,
  source_kind TEXT NOT NULL,
  categories_json TEXT NOT NULL DEFAULT '[]',
  usage_mode TEXT NOT NULL DEFAULT 'reference_only',
  licence_note TEXT,
  enabled INTEGER NOT NULL DEFAULT 1,
  priority INTEGER NOT NULL DEFAULT 50,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS question_bank_items (
  question_id TEXT PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
  source_id TEXT REFERENCES question_bank_sources(id),
  category TEXT NOT NULL CHECK(category IN ('oral','reading_comprehension','cloze','writing')),
  subcategory TEXT NOT NULL,
  provenance TEXT NOT NULL DEFAULT 'original',
  source_reference TEXT,
  tags_json TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_qbank_category ON question_bank_items(category,subcategory);
CREATE INDEX IF NOT EXISTS idx_qbank_source ON question_bank_items(source_id);

CREATE TABLE IF NOT EXISTS specialised_sessions (
  id TEXT PRIMARY KEY,
  child_id TEXT NOT NULL REFERENCES child_profiles(id) ON DELETE CASCADE,
  mode TEXT NOT NULL CHECK(mode IN ('practice','exam')),
  category TEXT NOT NULL CHECK(category IN ('oral','reading_comprehension','cloze','writing')),
  requested_count INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','evaluating','completed','abandoned')),
  score REAL,
  max_score REAL,
  started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_specialised_sessions_child ON specialised_sessions(child_id,started_at);

CREATE TABLE IF NOT EXISTS specialised_session_items (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES specialised_sessions(id) ON DELETE CASCADE,
  question_id TEXT NOT NULL REFERENCES questions(id),
  item_order INTEGER NOT NULL,
  question_type TEXT NOT NULL,
  stem_json TEXT NOT NULL,
  answer_json TEXT NOT NULL,
  explanation_json TEXT,
  marks REAL NOT NULL DEFAULT 1,
  response_json TEXT,
  score REAL,
  max_score REAL,
  feedback_json TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','answered','evaluating','completed','failed')),
  generation_job_id TEXT,
  answered_at TEXT,
  completed_at TEXT,
  UNIQUE(session_id,item_order)
);
CREATE INDEX IF NOT EXISTS idx_specialised_items_session ON specialised_session_items(session_id,item_order);
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-internal','English Mastery Original PSLE Bank','https://study.wisewavesg.com','English Mastery','internal_original','["oral","reading_comprehension","cloze","writing"]','owned','Original questions authored/generated for this platform; no third-party text copied.','100');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-seab','SEAB PSLE English specimen papers','https://www.seab.gov.sg/psle/psle-formats-examined-in-2026/','SEAB','official_specimen','["oral","reading_comprehension","cloze","writing"]','format_reference','Use only to align format, item families and difficulty; do not reproduce protected passages or questions.','100');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-moe','MOE Primary English syllabus','https://www.moe.gov.sg/-/media/files/primary/2020-english-language-primary.ashx','MOE','official_curriculum','["oral","reading_comprehension","cloze","writing"]','curriculum_reference','Curriculum and outcomes reference.','100');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-bc-read','British Council LearnEnglish Kids · Reading','https://learnenglishkids.britishcouncil.org/read-write/reading-practice','British Council','free_learning_reference','["reading_comprehension"]','reference_only','Reference themes, level and activity patterns only; generate original passages/questions.','80');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-bc-write','British Council LearnEnglish Kids · Writing','https://learnenglishkids.britishcouncil.org/read-write/writing-practice','British Council','free_learning_reference','["writing"]','reference_only','Reference text types and age-appropriate task patterns only.','80');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-bc-speak','British Council LearnEnglish Kids · Speak & spell','https://learnenglishkids.britishcouncil.org/speak-spell','British Council','free_learning_reference','["oral"]','reference_only','Reference age-appropriate pronunciation/speaking activities only.','80');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-bc-grammar','British Council LearnEnglish Kids · Grammar','https://learnenglishkids.britishcouncil.org/grammar-vocabulary/grammar-practice','British Council','free_learning_reference','["cloze"]','reference_only','Reference grammar concepts only; generate original items.','80');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-cambridge','Cambridge English · Activities for learners','https://www.cambridgeenglish.org/learning-english/activities-for-learners/','Cambridge English','free_learning_reference','["reading_comprehension","cloze","writing"]','reference_only','Reference CEFR activity patterns; generate original PSLE-aligned questions.','70');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-readtheory','ReadTheory','https://readtheory.org/','ReadTheory','free_platform_reference','["reading_comprehension"]','reference_only','Do not copy passages/questions; use as reading-difficulty and question-style reference only.','60');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-readworks','ReadWorks','https://www.readworks.org/','ReadWorks','free_platform_reference','["reading_comprehension"]','reference_only','Account/free education resource; do not ingest protected passages unless licence permits.','60');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-commonlit','CommonLit','https://www.commonlit.org/','CommonLit','free_platform_reference','["reading_comprehension"]','reference_only','Reference guided-reading/assessment patterns only; do not copy protected text.','60');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-k5','K5 Learning · Reading & grammar worksheets','https://www.k5learning.com/reading-comprehension-worksheets','K5 Learning','free_worksheet_reference','["reading_comprehension","cloze"]','reference_only','Reference skills and worksheet patterns; generate original material.','55');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-efe','EnglishForEveryone.org','https://englishforeveryone.org/','EnglishForEveryone.org','free_worksheet_reference','["reading_comprehension","cloze"]','reference_only','Reference worksheet structures; verify licence before reuse of any source text.','55');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-agendaweb','AgendaWeb English exercises','https://agendaweb.org/','AgendaWeb','free_exercise_reference','["cloze","reading_comprehension"]','reference_only','Reference grammar/vocabulary exercise concepts only.','50');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-perfectgrammar','Perfect English Grammar','https://www.perfect-english-grammar.com/grammar-exercises.html','Perfect English Grammar','free_exercise_reference','["cloze"]','reference_only','Reference grammar coverage; generate original PSLE items.','50');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-esllounge','ESL Lounge Student','https://www.esl-lounge.com/student/','ESL Lounge','free_exercise_reference','["cloze","reading_comprehension"]','reference_only','Reference exercise forms only; generate original items.','45');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-usingenglish','UsingEnglish.com Quizzes','https://www.usingenglish.com/quizzes/','UsingEnglish.com','free_exercise_reference','["cloze"]','reference_only','Reference grammar/usage domains only.','45');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-newslevels','News in Levels','https://www.newsinlevels.com/','News in Levels','free_reading_reference','["reading_comprehension","writing","oral"]','reference_only','Use topic ideas/facts only; generate original child-safe passages and tasks.','45');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-bne','Breaking News English','https://breakingnewsenglish.com/','Breaking News English','free_learning_reference','["reading_comprehension","cloze","oral","writing"]','reference_only','Use only where licensing permits; default to reference-only original generation.','40');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-wonderopolis','Wonderopolis','https://wonderopolis.org/','Wonderopolis','free_reading_reference','["reading_comprehension","oral","writing"]','reference_only','Use topic ideas/factual research only; generate original text.','40');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-nasa-kids','NASA Science for Kids','https://science.nasa.gov/kids/','NASA','public_science_reference','["reading_comprehension","oral","writing"]','reference_only','Use public factual background; generate original PSLE-style language questions.','50');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-noaa','NOAA Ocean Facts','https://oceanservice.noaa.gov/facts/','NOAA','public_science_reference','["reading_comprehension","oral","writing"]','reference_only','Use factual background; generate original PSLE-style language questions.','50');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-nparks','NParks Singapore','https://www.nparks.gov.sg/','NParks','public_sg_reference','["reading_comprehension","oral","writing"]','reference_only','Use Singapore factual/topic background; generate original tasks.','60');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-nea','NEA Singapore','https://www.nea.gov.sg/','NEA','public_sg_reference','["reading_comprehension","oral","writing"]','reference_only','Use Singapore factual/topic background; generate original tasks.','60');
INSERT OR IGNORE INTO question_bank_sources (id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority) VALUES ('qsrc-roots','Roots.gov.sg','https://www.roots.gov.sg/','National Heritage Board','public_sg_reference','["reading_comprehension","oral","writing"]','reference_only','Use factual/cultural background; generate original tasks.','60');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p5-01','oral_conversation','P5','3','{"prompt":"Tell your examiner about one responsibility you have at home. Why is it important?","topic":"Helping at home"}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p5-01','qsrc-internal','oral','conversation','original','Original PSLE-aligned bank item','["P5","oral","conversation"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-01','S-SBC-IDEA','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-01','S-INTERACT','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p5-02','oral_conversation','P5','3','{"prompt":"Describe a time you helped a friend solve a problem. What did you learn?","topic":"Friendship"}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p5-02','qsrc-internal','oral','conversation','original','Original PSLE-aligned bank item','["P5","oral","conversation"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-02','S-SBC-IDEA','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-02','S-INTERACT','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p5-03','oral_stimulus','P5','3','{"prompt":"Imagine a busy school library where two pupils are talking loudly while others are reading. What do you notice, and what should the pupils do?","topic":"Library scene"}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p5-03','qsrc-internal','oral','stimulus','original','Original PSLE-aligned bank item','["P5","oral","stimulus"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-03','S-SBC-IDEA','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-03','S-INTERACT','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p5-04','oral_stimulus','P5','3','{"prompt":"Imagine a canteen table with a large amount of untouched food left on trays. What might have happened and how can students reduce waste?","topic":"Food waste"}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p5-04','qsrc-internal','oral','stimulus','original','Original PSLE-aligned bank item','["P5","oral","stimulus"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-04','S-SBC-IDEA','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-04','S-INTERACT','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p5-05','oral_reading_aloud','P5','3','{"prompt":"Read this aloud clearly and expressively.","topic":"Community notice","referenceText":"Our neighbourhood clean-up will take place this Saturday morning. Volunteers should meet at the community centre by eight o’clock and bring a reusable water bottle. Gloves and litter-pickers will be provided."}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p5-05','qsrc-internal','oral','reading_aloud','original','Original PSLE-aligned bank item','["P5","oral","reading_aloud"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-05','S-PRON','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-05','S-FLUENCY','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p5-06','oral_conversation','P5','3','{"prompt":"Talk about a mistake that taught you something useful. How did you respond?","topic":"Learning from mistakes"}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p5-06','qsrc-internal','oral','conversation','original','Original PSLE-aligned bank item','["P5","oral","conversation"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-06','S-SBC-IDEA','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-06','S-INTERACT','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p5-07','oral_stimulus','P5','3','{"prompt":"Imagine an MRT carriage where a young passenger notices an elderly person standing nearby. What should happen next and why?","topic":"MRT courtesy"}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p5-07','qsrc-internal','oral','stimulus','original','Original PSLE-aligned bank item','["P5","oral","stimulus"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-07','S-SBC-IDEA','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-07','S-INTERACT','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p5-08','oral_conversation','P5','3','{"prompt":"Which healthy habit is hardest for children to maintain? Explain your view.","topic":"Healthy habits"}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p5-08','qsrc-internal','oral','conversation','original','Original PSLE-aligned bank item','["P5","oral","conversation"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-08','S-SBC-IDEA','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p5-08','S-INTERACT','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p6-01','oral_conversation','P6','3','{"prompt":"Do you think children should be given more responsibility at home and in school? Give reasons and examples.","topic":"Responsibility"}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p6-01','qsrc-internal','oral','conversation','original','Original PSLE-aligned bank item','["P6","oral","conversation"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-01','S-SBC-IDEA','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-01','S-INTERACT','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p6-02','oral_stimulus','P6','3','{"prompt":"Imagine a park where one group is feeding wild animals despite a sign asking visitors not to. What are the possible consequences?","topic":"Park behaviour"}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p6-02','qsrc-internal','oral','stimulus','original','Original PSLE-aligned bank item','["P6","oral","stimulus"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-02','S-SBC-IDEA','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-02','S-INTERACT','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p6-03','oral_stimulus','P6','3','{"prompt":"Imagine a student receiving a message from an unknown person asking for personal information. What should the student do and why?","topic":"Online safety"}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p6-03','qsrc-internal','oral','stimulus','original','Original PSLE-aligned bank item','["P6","oral","stimulus"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-03','S-SBC-IDEA','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-03','S-INTERACT','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p6-04','oral_reading_aloud','P6','3','{"prompt":"Read this aloud clearly and expressively.","topic":"School announcement","referenceText":"Students taking part in the science exhibition should place their projects in the hall before assembly. Each team must attach a clear label and check that all moving parts are safe. Judges will begin their visit at ten o’clock."}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p6-04','qsrc-internal','oral','reading_aloud','original','Original PSLE-aligned bank item','["P6","oral","reading_aloud"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-04','S-PRON','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-04','S-FLUENCY','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p6-05','oral_conversation','P6','3','{"prompt":"How can technology improve learning without becoming a distraction?","topic":"Technology"}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p6-05','qsrc-internal','oral','conversation','original','Original PSLE-aligned bank item','["P6","oral","conversation"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-05','S-SBC-IDEA','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-05','S-INTERACT','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p6-06','oral_conversation','P6','3','{"prompt":"Which environmental habit should every family adopt? Explain how it would help.","topic":"Environment"}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p6-06','qsrc-internal','oral','conversation','original','Original PSLE-aligned bank item','["P6","oral","conversation"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-06','S-SBC-IDEA','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-06','S-INTERACT','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p6-07','oral_stimulus','P6','3','{"prompt":"Imagine a group of pupils packing food supplies for families in need. What can young people learn from volunteering?","topic":"Volunteering"}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p6-07','qsrc-internal','oral','stimulus','original','Original PSLE-aligned bank item','["P6","oral","stimulus"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-07','S-SBC-IDEA','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-07','S-INTERACT','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('oral-p6-08','oral_conversation','P6','3','{"prompt":"Is courage always about doing something dangerous? Explain your answer with examples.","topic":"Courage"}','{"rubric":"AI oral rubric"}','{"text":"Develop a relevant answer with clear ideas, accurate language and effective interaction."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','4');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('oral-p6-08','qsrc-internal','oral','conversation','original','Original PSLE-aligned bank item','["P6","oral","conversation"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-08','S-SBC-IDEA','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('oral-p6-08','S-INTERACT','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p5-otters-1','reading_mcq','P5','3','{"title":"City Otters","passage":"After years of cleaner waterways and habitat improvement, otters began appearing more often along Singapore’s rivers and reservoirs. Their return excited many residents, but it also created new challenges. Otters sometimes cross roads or enter fish ponds while searching for food. Wildlife groups therefore encourage people to observe them from a safe distance, keep food away from wild animals and avoid blocking an otter family’s path. These simple actions allow people and wildlife to share the city more safely.","prompt":"What is the main reason otters are seen more often in the city?","options":["Cleaner waterways and improved habitats","Residents feed them every day","Fish ponds were removed","Roads were closed"]}','{"correctOption":0}','{"text":"Cleaner waterways and habitat improvement supported their return."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p5-otters-1','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P5","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p5-otters-1','R-LITERAL','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p5-otters-2','reading_mcq','P5','3','{"title":"City Otters","passage":"After years of cleaner waterways and habitat improvement, otters began appearing more often along Singapore’s rivers and reservoirs. Their return excited many residents, but it also created new challenges. Otters sometimes cross roads or enter fish ponds while searching for food. Wildlife groups therefore encourage people to observe them from a safe distance, keep food away from wild animals and avoid blocking an otter family’s path. These simple actions allow people and wildlife to share the city more safely.","prompt":"Why are people advised not to block an otter family’s path?","options":["To make photographs easier","To reduce stress and allow safe movement","To encourage otters to enter homes","To keep reservoirs empty"]}','{"correctOption":1}','{"text":"Giving wildlife space helps reduce conflict and allows safe movement."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p5-otters-2','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P5","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p5-otters-2','R-INFER','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p5-otters-3','reading_mcq','P5','3','{"title":"City Otters","passage":"After years of cleaner waterways and habitat improvement, otters began appearing more often along Singapore’s rivers and reservoirs. Their return excited many residents, but it also created new challenges. Otters sometimes cross roads or enter fish ponds while searching for food. Wildlife groups therefore encourage people to observe them from a safe distance, keep food away from wild animals and avoid blocking an otter family’s path. These simple actions allow people and wildlife to share the city more safely.","prompt":"Which challenge is mentioned in the passage?","options":["Otters cannot swim","Otters may cross roads or enter fish ponds","Residents cannot see rivers","Wildlife groups close parks"]}','{"correctOption":1}','{"text":"The passage specifically mentions road crossing and fish ponds."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p5-otters-3','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P5","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p5-otters-3','R-INFER','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p5-otters-4','reading_mcq','P5','3','{"title":"City Otters","passage":"After years of cleaner waterways and habitat improvement, otters began appearing more often along Singapore’s rivers and reservoirs. Their return excited many residents, but it also created new challenges. Otters sometimes cross roads or enter fish ponds while searching for food. Wildlife groups therefore encourage people to observe them from a safe distance, keep food away from wild animals and avoid blocking an otter family’s path. These simple actions allow people and wildlife to share the city more safely.","prompt":"Which statement best summarises the passage?","options":["Cities should remove all wildlife","People and wildlife can coexist when people behave responsibly","Otters should be kept as pets","Only experts should visit reservoirs"]}','{"correctOption":1}','{"text":"The passage focuses on responsible coexistence."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p5-otters-4','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P5","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p5-otters-4','R-INFER','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p5-space-1','reading_mcq','P5','3','{"title":"Exercise in Space","passage":"Astronauts living in space can float because they experience microgravity. Floating may look easy, but the human body changes when muscles and bones do not work against gravity in the usual way. To reduce these changes, astronauts exercise for about two hours each day using special machines. Some machines imitate running, while others provide resistance for strength training. Regular exercise helps astronauts remain strong enough to work in space and return safely to Earth.","prompt":"Why do astronauts exercise every day?","options":["To learn how to float","To reduce muscle and bone loss","To make the spacecraft move faster","To sleep more easily"]}','{"correctOption":1}','{"text":"Exercise helps reduce changes to muscles and bones."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p5-space-1','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P5","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p5-space-1','R-LITERAL','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p5-space-2','reading_mcq','P5','3','{"title":"Exercise in Space","passage":"Astronauts living in space can float because they experience microgravity. Floating may look easy, but the human body changes when muscles and bones do not work against gravity in the usual way. To reduce these changes, astronauts exercise for about two hours each day using special machines. Some machines imitate running, while others provide resistance for strength training. Regular exercise helps astronauts remain strong enough to work in space and return safely to Earth.","prompt":"What does “resistance” help astronauts practise?","options":["Strength training","Reading","Navigation","Cooking"]}','{"correctOption":0}','{"text":"Resistance equipment is used for strength training."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p5-space-2','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P5","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p5-space-2','R-INFER','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p5-space-3','reading_mcq','P5','3','{"title":"Exercise in Space","passage":"Astronauts living in space can float because they experience microgravity. Floating may look easy, but the human body changes when muscles and bones do not work against gravity in the usual way. To reduce these changes, astronauts exercise for about two hours each day using special machines. Some machines imitate running, while others provide resistance for strength training. Regular exercise helps astronauts remain strong enough to work in space and return safely to Earth.","prompt":"What can be inferred about microgravity?","options":["It makes normal muscle use less demanding","It prevents all movement","It increases Earth’s gravity","It makes exercise impossible"]}','{"correctOption":0}','{"text":"The body does not work against gravity in the usual way."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p5-space-3','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P5","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p5-space-3','R-INFER','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p5-space-4','reading_mcq','P5','3','{"title":"Exercise in Space","passage":"Astronauts living in space can float because they experience microgravity. Floating may look easy, but the human body changes when muscles and bones do not work against gravity in the usual way. To reduce these changes, astronauts exercise for about two hours each day using special machines. Some machines imitate running, while others provide resistance for strength training. Regular exercise helps astronauts remain strong enough to work in space and return safely to Earth.","prompt":"Which is the best title?","options":["How Astronauts Stay Strong in Space","Why Spacecraft Need Windows","How to Build a Rocket","Sleeping on Earth"]}','{"correctOption":0}','{"text":"The passage explains exercise and physical strength in space."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p5-space-4','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P5","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p5-space-4','R-INFER','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p6-mangrove-1','reading_mcq','P6','3','{"title":"Mangrove Defences","passage":"Mangrove forests grow where land and sea meet. Their tangled roots trap sediment and slow moving water. During storms, this network can reduce the energy of waves before the waves reach areas farther inland. Mangroves also provide nursery habitats for fish and other animals. However, mangroves are not a complete replacement for every form of coastal protection. Scientists often recommend combining healthy natural habitats with careful planning and, where necessary, engineered defences.","prompt":"How do mangrove roots help protect coasts?","options":["They increase wave energy","They trap sediment and slow water","They remove all seawater","They move storms away"]}','{"correctOption":1}','{"text":"The roots trap sediment and slow moving water."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p6-mangrove-1','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P6","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p6-mangrove-1','R-LITERAL','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p6-mangrove-2','reading_mcq','P6','3','{"title":"Mangrove Defences","passage":"Mangrove forests grow where land and sea meet. Their tangled roots trap sediment and slow moving water. During storms, this network can reduce the energy of waves before the waves reach areas farther inland. Mangroves also provide nursery habitats for fish and other animals. However, mangroves are not a complete replacement for every form of coastal protection. Scientists often recommend combining healthy natural habitats with careful planning and, where necessary, engineered defences.","prompt":"What does “nursery habitats” most likely mean?","options":["Places where young animals can grow","Buildings for children","Areas with no wildlife","Deep ocean trenches"]}','{"correctOption":0}','{"text":"A nursery habitat supports young animals as they grow."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p6-mangrove-2','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P6","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p6-mangrove-2','R-INFER','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p6-mangrove-3','reading_mcq','P6','3','{"title":"Mangrove Defences","passage":"Mangrove forests grow where land and sea meet. Their tangled roots trap sediment and slow moving water. During storms, this network can reduce the energy of waves before the waves reach areas farther inland. Mangroves also provide nursery habitats for fish and other animals. However, mangroves are not a complete replacement for every form of coastal protection. Scientists often recommend combining healthy natural habitats with careful planning and, where necessary, engineered defences.","prompt":"Why does the writer mention engineered defences?","options":["To show mangroves are useless","To explain that protection may need several approaches","To encourage removal of forests","To claim storms can be stopped completely"]}','{"correctOption":1}','{"text":"The passage supports combining natural and engineered approaches where needed."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p6-mangrove-3','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P6","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p6-mangrove-3','R-INFER','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p6-mangrove-4','reading_mcq','P6','3','{"title":"Mangrove Defences","passage":"Mangrove forests grow where land and sea meet. Their tangled roots trap sediment and slow moving water. During storms, this network can reduce the energy of waves before the waves reach areas farther inland. Mangroves also provide nursery habitats for fish and other animals. However, mangroves are not a complete replacement for every form of coastal protection. Scientists often recommend combining healthy natural habitats with careful planning and, where necessary, engineered defences.","prompt":"Which idea is best supported?","options":["One solution is always enough","Healthy ecosystems can contribute to coastal protection","Mangroves grow only in freshwater","Engineering should never be used"]}','{"correctOption":1}','{"text":"The passage explains a protective role for mangroves as part of broader planning."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p6-mangrove-4','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P6","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p6-mangrove-4','R-INFER','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p6-library-1','reading_mcq','P6','3','{"title":"A Quieter Library","passage":"When a school library introduced silent study zones, some students worried that the space would feel unfriendly. The librarian therefore created different areas for different purposes. One corner allowed quiet group discussion, another was reserved for silent reading, and a third contained movable tables for project work. After several weeks, students reported fewer arguments about noise. More importantly, they began choosing spaces that matched the kind of work they needed to do. The change succeeded not because everyone behaved in the same way, but because the library recognised that different activities require different conditions.","prompt":"Why did the librarian create different areas?","options":["To reduce the number of books","To match spaces to different activities","To prevent project work","To make all areas silent"]}','{"correctOption":1}','{"text":"The areas were designed for different types of work."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p6-library-1','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P6","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p6-library-1','R-LITERAL','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p6-library-2','reading_mcq','P6','3','{"title":"A Quieter Library","passage":"When a school library introduced silent study zones, some students worried that the space would feel unfriendly. The librarian therefore created different areas for different purposes. One corner allowed quiet group discussion, another was reserved for silent reading, and a third contained movable tables for project work. After several weeks, students reported fewer arguments about noise. More importantly, they began choosing spaces that matched the kind of work they needed to do. The change succeeded not because everyone behaved in the same way, but because the library recognised that different activities require different conditions.","prompt":"What was an important result after several weeks?","options":["Students stopped visiting","Noise arguments decreased","All group work ended","The library removed tables"]}','{"correctOption":1}','{"text":"Students reported fewer arguments about noise."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p6-library-2','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P6","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p6-library-2','R-INFER','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p6-library-3','reading_mcq','P6','3','{"title":"A Quieter Library","passage":"When a school library introduced silent study zones, some students worried that the space would feel unfriendly. The librarian therefore created different areas for different purposes. One corner allowed quiet group discussion, another was reserved for silent reading, and a third contained movable tables for project work. After several weeks, students reported fewer arguments about noise. More importantly, they began choosing spaces that matched the kind of work they needed to do. The change succeeded not because everyone behaved in the same way, but because the library recognised that different activities require different conditions.","prompt":"What does the final sentence suggest?","options":["Fair rules can allow for different needs","Everyone should work in exactly the same way","Libraries should be completely silent","Projects should be done at home"]}','{"correctOption":0}','{"text":"The successful design recognised different activity needs."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p6-library-3','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P6","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p6-library-3','R-INFER','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('read-p6-library-4','reading_mcq','P6','3','{"title":"A Quieter Library","passage":"When a school library introduced silent study zones, some students worried that the space would feel unfriendly. The librarian therefore created different areas for different purposes. One corner allowed quiet group discussion, another was reserved for silent reading, and a third contained movable tables for project work. After several weeks, students reported fewer arguments about noise. More importantly, they began choosing spaces that matched the kind of work they needed to do. The change succeeded not because everyone behaved in the same way, but because the library recognised that different activities require different conditions.","prompt":"Which word best describes the librarian’s approach?","options":["Flexible","Careless","Secretive","Wasteful"]}','{"correctOption":0}','{"text":"Creating different zones for different purposes shows flexibility."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('read-p6-library-4','qsrc-internal','reading_comprehension','mixed','original','Original PSLE-aligned bank item','["P6","reading_comprehension","mixed"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('read-p6-library-4','R-INFER','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-01','cloze_vocabulary','P5','3','{"prompt":"The hikers were ___ when dark clouds gathered above them.","options":["cheerful","concerned","careless","sleepy"]}','{"correctOption":1}','{"text":"Concerned fits because dark clouds may signal bad weather."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-01','qsrc-internal','cloze','vocabulary','original','Original PSLE-aligned bank item','["P5","cloze","vocabulary"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-01','R-VOCABCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-02','cloze_vocabulary','P5','3','{"prompt":"Maya gave a ___ explanation so everyone understood the plan.","options":["clear","rare","silent","rough"]}','{"correctOption":0}','{"text":"Clear describes an explanation that is easy to understand."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-02','qsrc-internal','cloze','vocabulary','original','Original PSLE-aligned bank item','["P5","cloze","vocabulary"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-02','R-VOCABCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-03','cloze_vocabulary','P5','3','{"prompt":"The class worked together to ___ the problem.","options":["solve","borrow","hide","scatter"]}','{"correctOption":0}','{"text":"Solve means find an answer to a problem."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-03','qsrc-internal','cloze','vocabulary','original','Original PSLE-aligned bank item','["P5","cloze","vocabulary"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-03','R-VOCABCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-04','cloze_vocabulary','P5','3','{"prompt":"The old bridge was closed because it was no longer ___.","options":["safe","tiny","polite","famous"]}','{"correctOption":0}','{"text":"Safe fits the reason for closing a bridge."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-04','qsrc-internal','cloze','vocabulary','original','Original PSLE-aligned bank item','["P5","cloze","vocabulary"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-04','R-VOCABCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-05','cloze_vocabulary','P5','3','{"prompt":"Jin spoke ___ so the younger pupils would not be frightened.","options":["gently","wildly","rarely","briefly"]}','{"correctOption":0}','{"text":"Gently describes a calm and kind manner."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-05','qsrc-internal','cloze','vocabulary','original','Original PSLE-aligned bank item','["P5","cloze","vocabulary"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-05','R-VOCABCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-06','cloze_vocabulary','P5','3','{"prompt":"The team felt ___ after practising for several weeks.","options":["prepared","empty","ordinary","distant"]}','{"correctOption":0}','{"text":"Prepared means ready for the event."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-06','qsrc-internal','cloze','vocabulary','original','Original PSLE-aligned bank item','["P5","cloze","vocabulary"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-06','R-VOCABCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-07','cloze_vocabulary','P6','3','{"prompt":"The council introduced measures to ___ the amount of food waste.","options":["reduce","announce","divide","ignore"]}','{"correctOption":0}','{"text":"Reduce means make an amount smaller."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-07','qsrc-internal','cloze','vocabulary','original','Original PSLE-aligned bank item','["P6","cloze","vocabulary"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-07','R-VOCABCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-08','cloze_vocabulary','P6','3','{"prompt":"Although the task looked difficult, Amir remained ___.","options":["determined","fragile","casual","ancient"]}','{"correctOption":0}','{"text":"Determined describes someone who continues despite difficulty."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-08','qsrc-internal','cloze','vocabulary','original','Original PSLE-aligned bank item','["P6","cloze","vocabulary"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-08','R-VOCABCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-09','cloze_vocabulary','P6','3','{"prompt":"The scientist repeated the experiment to ___ the result.","options":["verify","decorate","replace","entertain"]}','{"correctOption":0}','{"text":"Verify means check that something is accurate or true."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-09','qsrc-internal','cloze','vocabulary','original','Original PSLE-aligned bank item','["P6","cloze","vocabulary"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-09','R-VOCABCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-10','cloze_vocabulary','P6','3','{"prompt":"The instructions were ___, so no one knew which step came first.","options":["ambiguous","generous","efficient","ordinary"]}','{"correctOption":0}','{"text":"Ambiguous means unclear or open to more than one interpretation."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-10','qsrc-internal','cloze','vocabulary','original','Original PSLE-aligned bank item','["P6","cloze","vocabulary"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-10','R-VOCABCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-11','cloze_vocabulary','P6','3','{"prompt":"The volunteers made a ___ effort to finish before the rain arrived.","options":["concerted","hollow","distant","minor"]}','{"correctOption":0}','{"text":"A concerted effort is a determined, coordinated effort."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-11','qsrc-internal','cloze','vocabulary','original','Original PSLE-aligned bank item','["P6","cloze","vocabulary"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-11','R-VOCABCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-12','cloze_vocabulary','P6','3','{"prompt":"The new rule was introduced to ___ students from sharing passwords.","options":["discourage","admire","collect","restore"]}','{"correctOption":0}','{"text":"Discourage means make someone less likely to do something."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-12','qsrc-internal','cloze','vocabulary','original','Original PSLE-aligned bank item','["P6","cloze","vocabulary"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-12','R-VOCABCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-13','cloze_grammar','P5','3','{"prompt":"Neither Ben nor his friends ___ ready to leave.","options":["was","were","is","be"]}','{"correctOption":1}','{"text":"The verb agrees with the nearer plural subject “friends”."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-13','qsrc-internal','cloze','grammar','original','Original PSLE-aligned bank item','["P5","cloze","grammar"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-13','R-GRAMMARCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-14','cloze_grammar','P5','3','{"prompt":"If it ___ tomorrow, the match will be moved indoors.","options":["rains","rained","will rain","rain"]}','{"correctOption":0}','{"text":"The first conditional uses present simple in the if-clause."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-14','qsrc-internal','cloze','grammar','original','Original PSLE-aligned bank item','["P5","cloze","grammar"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-14','R-GRAMMARCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-15','cloze_grammar','P5','3','{"prompt":"The books on the shelf ___ arranged by topic.","options":["is","are","was","has"]}','{"correctOption":1}','{"text":"The plural subject “books” takes “are”."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-15','qsrc-internal','cloze','grammar','original','Original PSLE-aligned bank item','["P5","cloze","grammar"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-15','R-GRAMMARCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-16','cloze_grammar','P5','3','{"prompt":"She has lived here ___ 2022.","options":["for","since","during","from"]}','{"correctOption":1}','{"text":"Since introduces the starting point of a continuing period."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-16','qsrc-internal','cloze','grammar','original','Original PSLE-aligned bank item','["P5","cloze","grammar"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-16','R-GRAMMARCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-17','cloze_grammar','P5','3','{"prompt":"We waited quietly ___ the teacher was speaking.","options":["while","because of","despite","unless"]}','{"correctOption":0}','{"text":"While connects two actions happening at the same time."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-17','qsrc-internal','cloze','grammar','original','Original PSLE-aligned bank item','["P5","cloze","grammar"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-17','R-GRAMMARCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-18','cloze_grammar','P5','3','{"prompt":"The puppy wagged ___ tail when it saw its owner.","options":["its","it’s","their","his"]}','{"correctOption":0}','{"text":"Its is the possessive determiner."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-18','qsrc-internal','cloze','grammar','original','Original PSLE-aligned bank item','["P5","cloze","grammar"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-18','R-GRAMMARCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-19','cloze_grammar','P6','3','{"prompt":"Despite ___ tired, Lena completed the report.","options":["being","was","be","been"]}','{"correctOption":0}','{"text":"Despite can be followed by a gerund phrase: despite being tired."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-19','qsrc-internal','cloze','grammar','original','Original PSLE-aligned bank item','["P6","cloze","grammar"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-19','R-GRAMMARCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-20','cloze_grammar','P6','3','{"prompt":"By the time we arrived, the performance ___.","options":["had begun","begins","has begun","begin"]}','{"correctOption":0}','{"text":"Past perfect marks the earlier past action."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-20','qsrc-internal','cloze','grammar','original','Original PSLE-aligned bank item','["P6","cloze","grammar"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-20','R-GRAMMARCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-21','cloze_grammar','P6','3','{"prompt":"The teacher asked whether I ___ the instructions.","options":["had understood","understand","will understand","am understanding"]}','{"correctOption":0}','{"text":"Reported speech shifts the earlier action to past perfect here."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-21','qsrc-internal','cloze','grammar','original','Original PSLE-aligned bank item','["P6","cloze","grammar"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-21','R-GRAMMARCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-22','cloze_grammar','P6','3','{"prompt":"Not only the players but also the coach ___ disappointed.","options":["was","were","are","have"]}','{"correctOption":0}','{"text":"The verb agrees with the nearer singular subject “coach”."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-22','qsrc-internal','cloze','grammar','original','Original PSLE-aligned bank item','["P6","cloze","grammar"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-22','R-GRAMMARCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-23','cloze_grammar','P6','3','{"prompt":"The project, together with its supporting documents, ___ due tomorrow.","options":["is","are","were","have"]}','{"correctOption":0}','{"text":"The main singular subject “project” controls agreement."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-23','qsrc-internal','cloze','grammar','original','Original PSLE-aligned bank item','["P6","cloze","grammar"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-23','R-GRAMMARCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('cloze-24','cloze_grammar','P6','3','{"prompt":"Unless you ___ the form today, your application cannot be processed.","options":["submit","submitted","will submit","submitting"]}','{"correctOption":0}','{"text":"Unless takes present simple for a future condition."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','1');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('cloze-24','qsrc-internal','cloze','grammar','original','Original PSLE-aligned bank item','["P6","cloze","grammar"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('cloze-24','R-GRAMMARCLOZE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p5-01','writing_continuous','P5','3','{"title":"A Difficult Choice","prompt":"Write a story about a time when a character had to make a difficult choice. Show what made the decision difficult and what happened afterwards.","writingType":"continuous","minimumWords":100}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','20');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p5-01','qsrc-internal','writing','continuous','original','Original PSLE-aligned bank item','["P5","writing","continuous"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-01','W-CW-IDEAS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-01','W-CW-ORG','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-01','W-CW-VOCAB','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-01','W-CW-GRAM','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p5-02','writing_continuous','P5','3','{"title":"An Unexpected Visitor","prompt":"Write a story about an unexpected visitor. Develop the setting, the problem and the ending.","writingType":"continuous","minimumWords":100}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','20');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p5-02','qsrc-internal','writing','continuous','original','Original PSLE-aligned bank item','["P5","writing","continuous"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-02','W-CW-IDEAS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-02','W-CW-ORG','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-02','W-CW-VOCAB','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-02','W-CW-GRAM','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p5-03','writing_continuous','P5','3','{"title":"Being Responsible","prompt":"Write a story that shows why responsibility matters. You may write about school, home or the community.","writingType":"continuous","minimumWords":100}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','20');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p5-03','qsrc-internal','writing','continuous','original','Original PSLE-aligned bank item','["P5","writing","continuous"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-03','W-CW-IDEAS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-03','W-CW-ORG','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-03','W-CW-VOCAB','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-03','W-CW-GRAM','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p5-04','writing_continuous','P5','3','{"title":"A Lost Item","prompt":"Write a story about an important item that went missing and how the problem was resolved.","writingType":"continuous","minimumWords":100}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','20');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p5-04','qsrc-internal','writing','continuous','original','Original PSLE-aligned bank item','["P5","writing","continuous"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-04','W-CW-IDEAS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-04','W-CW-ORG','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-04','W-CW-VOCAB','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-04','W-CW-GRAM','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p5-05','writing_situational','P5','3','{"title":"Class Reading Corner","prompt":"Your class wants to improve its reading corner. Write an email to your teacher suggesting two changes and explaining why they would help.","writingType":"situational","minimumWords":100}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','14');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p5-05','qsrc-internal','writing','situational','original','Original PSLE-aligned bank item','["P5","writing","situational"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-05','W-SW-PAC','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-05','W-SW-POINTS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-05','W-SW-TONE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p5-06','writing_situational','P5','3','{"title":"School Event Invitation","prompt":"Write an email inviting a family member to your school’s learning showcase. Include the date, time, place, purpose and what visitors can expect.","writingType":"situational","minimumWords":100}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','14');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p5-06','qsrc-internal','writing','situational','original','Original PSLE-aligned bank item','["P5","writing","situational"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-06','W-SW-PAC','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-06','W-SW-POINTS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-06','W-SW-TONE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p5-07','writing_situational','P5','3','{"title":"Canteen Feedback","prompt":"Write a polite email to the canteen committee about one problem you noticed and two practical suggestions.","writingType":"situational","minimumWords":100}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','14');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p5-07','qsrc-internal','writing','situational','original','Original PSLE-aligned bank item','["P5","writing","situational"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-07','W-SW-PAC','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-07','W-SW-POINTS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-07','W-SW-TONE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p5-08','writing_situational','P5','3','{"title":"Borrowed Equipment","prompt":"Write a note explaining that a piece of class equipment was damaged accidentally. Explain what happened and what you will do next.","writingType":"situational","minimumWords":100}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','14');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p5-08','qsrc-internal','writing','situational','original','Original PSLE-aligned bank item','["P5","writing","situational"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-08','W-SW-PAC','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-08','W-SW-POINTS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p5-08','W-SW-TONE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p6-01','writing_continuous','P6','3','{"title":"A Promise","prompt":"Write a story about a promise that became difficult to keep. Develop the conflict and show what the character learned.","writingType":"continuous","minimumWords":150}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','20');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p6-01','qsrc-internal','writing','continuous','original','Original PSLE-aligned bank item','["P6","writing","continuous"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-01','W-CW-IDEAS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-01','W-CW-ORG','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-01','W-CW-VOCAB','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-01','W-CW-GRAM','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p6-02','writing_continuous','P6','3','{"title":"The Warning","prompt":"Write a story in which a warning plays an important part. Build tension and develop a convincing ending.","writingType":"continuous","minimumWords":150}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','20');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p6-02','qsrc-internal','writing','continuous','original','Original PSLE-aligned bank item','["P6","writing","continuous"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-02','W-CW-IDEAS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-02','W-CW-ORG','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-02','W-CW-VOCAB','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-02','W-CW-GRAM','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p6-03','writing_continuous','P6','3','{"title":"A Second Chance","prompt":"Write a story about someone who receives a second chance. Show how the person changes or acts differently.","writingType":"continuous","minimumWords":150}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','20');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p6-03','qsrc-internal','writing','continuous','original','Original PSLE-aligned bank item','["P6","writing","continuous"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-03','W-CW-IDEAS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-03','W-CW-ORG','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-03','W-CW-VOCAB','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-03','W-CW-GRAM','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p6-04','writing_continuous','P6','3','{"title":"Working Together","prompt":"Write a story about a situation that could only be solved when people worked together.","writingType":"continuous","minimumWords":150}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','20');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p6-04','qsrc-internal','writing','continuous','original','Original PSLE-aligned bank item','["P6","writing","continuous"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-04','W-CW-IDEAS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-04','W-CW-ORG','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-04','W-CW-VOCAB','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-04','W-CW-GRAM','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p6-05','writing_situational','P6','3','{"title":"Community Clean-up","prompt":"Write an email encouraging classmates to join a community clean-up. Include purpose, arrangements, what to bring and why participation matters.","writingType":"situational","minimumWords":100}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','14');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p6-05','qsrc-internal','writing','situational','original','Original PSLE-aligned bank item','["P6","writing","situational"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-05','W-SW-PAC','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-05','W-SW-POINTS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-05','W-SW-TONE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p6-06','writing_situational','P6','3','{"title":"Library Proposal","prompt":"Write a proposal-style email to your school librarian suggesting a new activity for the library. Explain how it would benefit students.","writingType":"situational","minimumWords":100}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','14');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p6-06','qsrc-internal','writing','situational','original','Original PSLE-aligned bank item','["P6","writing","situational"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-06','W-SW-PAC','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-06','W-SW-POINTS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-06','W-SW-TONE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p6-07','writing_situational','P6','3','{"title":"Lost-and-Found Improvement","prompt":"Write an email to a school leader suggesting how the lost-and-found system could be improved. Give clear reasons.","writingType":"situational","minimumWords":100}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','14');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p6-07','qsrc-internal','writing','situational','original','Original PSLE-aligned bank item','["P6","writing","situational"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-07','W-SW-PAC','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-07','W-SW-POINTS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-07','W-SW-TONE','1');
INSERT OR IGNORE INTO questions (id,question_type,school_level,difficulty,stem_json,answer_json,explanation_json,status,source_content_id,curriculum_version_id,generation_model,marks) VALUES ('writing-p6-08','writing_situational','P6','3','{"title":"Thank-you Message","prompt":"Write a formal thank-you email to a community volunteer who helped at a school event. Include specific details about the help provided and its impact.","writingType":"situational","minimumWords":100}','{"rubric":"PSLE writing rubric"}','{"text":"Plan, write and review for task fulfilment, organisation, vocabulary, grammar and mechanics."}','published',NULL,'SG-PRIMARY-ENGLISH-2020-PSLE-2026','seed-v0.5-r7','14');
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json) VALUES ('writing-p6-08','qsrc-internal','writing','situational','original','Original PSLE-aligned bank item','["P6","writing","situational"]');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-08','W-SW-PAC','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-08','W-SW-POINTS','1');
INSERT OR IGNORE INTO question_skills (question_id,skill_id,weight) VALUES ('writing-p6-08','W-SW-TONE','1');

-- Bring earlier standalone Paper 2 questions into the Question Bank as well.
INSERT OR IGNORE INTO question_bank_items (question_id,source_id,category,subcategory,provenance,source_reference,tags_json)
SELECT q.id,'qsrc-internal',
  CASE WHEN q.question_type IN ('grammar_cloze','vocabulary_cloze','comprehension_cloze','grammar_mcq','vocabulary_mcq','editing_grammar','editing_spelling') THEN 'cloze' ELSE 'reading_comprehension' END,
  q.question_type,'original','Earlier English Mastery standalone bank item',json_array(q.school_level,q.question_type)
FROM questions q
WHERE q.status='published' AND q.source_content_id IS NULL
  AND q.question_type IN ('grammar_cloze','vocabulary_cloze','comprehension_cloze','grammar_mcq','vocabulary_mcq','editing_grammar','editing_spelling','open_comprehension','synthesis','visual_text');
