PRAGMA foreign_keys = ON;

-- R20 visibility contract:
-- guests see platform/global content only; authenticated learners see global + tenant content.
-- getVisibleLessonIds now enforces this at query time and no longer truncates the library.

-- Speaking reference sources for future platform-managed expansion.
INSERT OR IGNORE INTO question_bank_sources
(id,name,url,provider,source_kind,categories_json,usage_mode,licence_note,priority)
VALUES
('qsrc-cambridge-young-speaking','Cambridge English · Young Learners Speaking','https://www.cambridgeenglish.org/learning-english/parents-and-children/learning-activities-to-do-with-your-child/six-fun-activities/','Cambridge English','young_learners_speaking_reference','["oral"]','reference_only','Use speaking activity patterns, age-appropriate topics and task ideas only; generate original English Mastery content. Do not copy source text or protected activity wording.','90'),
('qsrc-cambridge-speaking','Cambridge English · Speaking Activities','https://www.cambridgeenglish.org/learning-english/activities-for-learners/?skill=speaking','Cambridge English','speaking_activity_reference','["oral"]','reference_only','Use speaking/pronunciation activity patterns and broad language goals only; generate original PSLE-aligned content.','75');

-- Original platform Reading Aloud tasks. These are global and therefore visible to guests.
INSERT OR IGNORE INTO content_items
(id,content_type,title,school_level,topic,source_url,licence,status,active_version,description,source_attribution,published_at,scope)
VALUES
('r20-speak-p5-library-visit','oral_prompt','A Visit to the School Library','P5','School','https://www.moe.gov.sg/-/media/files/primary/2020-english-language-primary.ashx','owned','published',1,'Original Reading Aloud practice focusing on clear phrasing, pace and expression.','English Mastery original · aligned to MOE English Language Syllabus 2020',CURRENT_TIMESTAMP,'global'),
('r20-speak-p5-helpful-neighbour','oral_prompt','A Helpful Neighbour','P5','Community','https://www.moe.gov.sg/-/media/files/primary/2020-english-language-primary.ashx','owned','published',1,'Original Reading Aloud practice with dialogue-like phrasing and natural emphasis.','English Mastery original · aligned to MOE English Language Syllabus 2020',CURRENT_TIMESTAMP,'global'),
('r20-speak-p6-school-exhibition','oral_prompt','The School Exhibition','P6','School','https://www.moe.gov.sg/-/media/files/primary/2020-english-language-primary.ashx','owned','published',1,'Original Reading Aloud practice requiring confident delivery and appropriate emphasis.','English Mastery original · aligned to MOE English Language Syllabus 2020',CURRENT_TIMESTAMP,'global'),
('r20-speak-p6-small-change','oral_prompt','One Small Change','P6','Environment','https://www.moe.gov.sg/-/media/files/primary/2020-english-language-primary.ashx','owned','published',1,'Original Reading Aloud practice on cause, effect and reflective delivery.','English Mastery original · aligned to MOE English Language Syllabus 2020',CURRENT_TIMESTAMP,'global');

INSERT OR IGNORE INTO content_versions(id,content_id,version,body_json,generation_model,curriculum_version_id,review_status)
VALUES
('r20-speak-p5-library-visit-v1','r20-speak-p5-library-visit',1,'{"mode":"reading_aloud","prompt":"Read the passage aloud clearly. Pause naturally at commas and full stops, and make the final sentence sound thoughtful.","referenceText":"Our class visited the school library to choose books for a new reading corner. Some pupils went straight to the adventure shelf, while others looked for books about animals, space and inventions. I noticed that the librarian was helping a younger pupil find a book that was not too difficult. She explained how to use the pictures, headings and short descriptions to choose a suitable book. Before we left, our teacher reminded us that reading is not a race. A good book gives us time to wonder, learn and think."}','r20-original','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved'),
('r20-speak-p5-helpful-neighbour-v1','r20-speak-p5-helpful-neighbour',1,'{"mode":"reading_aloud","prompt":"Read the passage aloud as a short story. Use a warm tone when describing the neighbour helping the family.","referenceText":"When a heavy rainstorm began, Maya realised that she had left the windows of her flat open. Her mother was still at work, so Maya hurried home after school. Just as she reached the block, she met a neighbour carrying a small umbrella. The neighbour offered to walk with her and helped close the windows before the rain reached the furniture. Maya thanked her and promised to return the kindness one day. Later that evening, Maya thought about how a small act of help could make a difficult afternoon much easier."}','r20-original','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved'),
('r20-speak-p6-school-exhibition-v1','r20-speak-p6-school-exhibition',1,'{"mode":"reading_aloud","prompt":"Read the passage aloud as if you are introducing an exhibition to visitors. Stress the important ideas without rushing.","referenceText":"Our school exhibition began with a simple question: how can students make the neighbourhood a better place? One group studied ways to reduce food waste, another designed a safer crossing near the school, and a third collected stories from older residents. The final exhibition did not present one perfect solution. Instead, it showed how different ideas could work together. Visitors were invited to leave suggestions beside each display. By the end of the day, the students understood that useful projects often begin with careful observation and grow through discussion."}','r20-original','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved'),
('r20-speak-p6-small-change-v1','r20-speak-p6-small-change',1,'{"mode":"reading_aloud","prompt":"Read the passage aloud with a calm, reflective tone. Emphasise the contrast between a small action and its larger effect.","referenceText":"At first, our class wanted to make a dramatic change to the school garden. We imagined building new paths and planting dozens of trees. After speaking to the gardener, however, we realised that the garden needed something simpler. We began by checking which plants were receiving too much water and moved a few pots to better locations. We also started collecting dry leaves for compost. None of these changes looked impressive on their own. After several months, the garden was healthier and easier to care for. We learned that improvement does not always begin with a big idea. Sometimes it begins with noticing one small problem and doing something about it."}','r20-original','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved');

-- Original platform Stimulus Conversation tasks. The stimulus is represented as text so no external image is required.
INSERT OR IGNORE INTO content_items
(id,content_type,title,school_level,topic,source_url,licence,status,active_version,description,source_attribution,published_at,scope)
VALUES
('r20-speak-p5-playground','oral_prompt','A Busy Playground','P5','Community','https://www.moe.gov.sg/-/media/files/primary/2020-english-language-primary.ashx','owned','published',1,'Original stimulus-based oral conversation practice using a school playground scene.','English Mastery original · aligned to MOE English Language Syllabus 2020',CURRENT_TIMESTAMP,'global'),
('r20-speak-p5-classroom-project','oral_prompt','A Classroom Project','P5','Teamwork','https://www.moe.gov.sg/-/media/files/primary/2020-english-language-primary.ashx','owned','published',1,'Original stimulus-based oral conversation practice focused on cooperation and problem solving.','English Mastery original · aligned to MOE English Language Syllabus 2020',CURRENT_TIMESTAMP,'global'),
('r20-speak-p6-community-garden','oral_prompt','The Community Garden','P6','Environment','https://www.moe.gov.sg/-/media/files/primary/2020-english-language-primary.ashx','owned','published',1,'Original stimulus-based oral conversation practice focused on responsibility and community action.','English Mastery original · aligned to MOE English Language Syllabus 2020',CURRENT_TIMESTAMP,'global'),
('r20-speak-p6-school-event','oral_prompt','Helping at a School Event','P6','Responsibility','https://www.moe.gov.sg/-/media/files/primary/2020-english-language-primary.ashx','owned','published',1,'Original stimulus-based oral conversation practice requiring description, opinion and personal response.','English Mastery original · aligned to MOE English Language Syllabus 2020',CURRENT_TIMESTAMP,'global');

INSERT OR IGNORE INTO content_versions(id,content_id,version,body_json,generation_model,curriculum_version_id,review_status)
VALUES
('r20-speak-p5-playground-v1','r20-speak-p5-playground',1,'{"mode":"stimulus","prompt":"Describe what is happening in the scene. Which actions help everyone enjoy the playground safely? Give a reason for your answer.","stimulusAlt":"A school playground during recess: two pupils are waiting for a turn on a slide, a child is helping a younger pupil pick up a dropped water bottle, several pupils are playing a ball game in a marked area, and one pupil is reminding a friend not to run near the steps.","followUpGoals":["describe relevant details","give a clear reason","relate to personal experience","respond to a follow-up question"]}','r20-original','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved'),
('r20-speak-p5-classroom-project-v1','r20-speak-p5-classroom-project',1,'{"mode":"stimulus","prompt":"Look at the scene and explain how the pupils are working together. What could they do if the group cannot agree on the plan?","stimulusAlt":"A classroom with four pupils preparing a group display: one pupil is drawing a poster, another is arranging pictures, a third is writing labels, and two pupils are discussing which design to use while a teacher observes from nearby.","followUpGoals":["identify actions and roles","suggest a solution","explain a reason","give a personal example"]}','r20-original','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved'),
('r20-speak-p6-community-garden-v1','r20-speak-p6-community-garden',1,'{"mode":"stimulus","prompt":"Describe the scene and discuss whether children should take responsibility for caring for shared green spaces. Explain your view.","stimulusAlt":"A community garden beside a block of flats: children are watering plants, an adult is checking a compost bin, one pupil is removing litter from a path, and another child is showing a neighbour a sign explaining which plants are ready to harvest.","followUpGoals":["describe relevant details","state and develop a view","consider another perspective","give a relevant example"]}','r20-original','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved'),
('r20-speak-p6-school-event-v1','r20-speak-p6-school-event',1,'{"mode":"stimulus","prompt":"What are the pupils doing to make the event successful? Which responsibility would you be most willing to take, and why?","stimulusAlt":"A school event in a hall: pupils are welcoming visitors, another pupil is checking a programme, two pupils are arranging chairs, a student is helping a younger child find a classroom, and a teacher is speaking to volunteers near the entrance.","followUpGoals":["interpret several details","choose and justify a responsibility","relate to experience","respond naturally to a different opinion"]}','r20-original','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved');

-- Skill mapping for the new global speaking content.
INSERT OR IGNORE INTO content_skills(content_id,skill_id,coverage) VALUES
('r20-speak-p5-library-visit','S-PRON',1),('r20-speak-p5-library-visit','S-FLUENCY',1),('r20-speak-p5-library-visit','S-PROSODY',1),
('r20-speak-p5-helpful-neighbour','S-PRON',1),('r20-speak-p5-helpful-neighbour','S-FLUENCY',1),('r20-speak-p5-helpful-neighbour','S-PROSODY',1),
('r20-speak-p6-school-exhibition','S-PRON',1),('r20-speak-p6-school-exhibition','S-FLUENCY',1),('r20-speak-p6-school-exhibition','S-PROSODY',1),
('r20-speak-p6-small-change','S-PRON',1),('r20-speak-p6-small-change','S-FLUENCY',1),('r20-speak-p6-small-change','S-PROSODY',1),
('r20-speak-p5-playground','S-SBC-IDEA',1),('r20-speak-p5-playground','S-INTERACT',1),
('r20-speak-p5-classroom-project','S-SBC-IDEA',1),('r20-speak-p5-classroom-project','S-INTERACT',1),
('r20-speak-p6-community-garden','S-SBC-IDEA',1),('r20-speak-p6-community-garden','S-INTERACT',1),
('r20-speak-p6-school-event','S-SBC-IDEA',1),('r20-speak-p6-school-event','S-INTERACT',1);

-- Existing tenants should immediately receive the full global speaking library.
INSERT OR REPLACE INTO tenant_learn_availability(tenant_id,school_level,domain,lesson_limit)
SELECT t.id,l.level,'speak',200
FROM tenants t CROSS JOIN (SELECT 'P5' level UNION ALL SELECT 'P6') l
WHERE t.status='active';
