PRAGMA foreign_keys = ON;

-- PET / Cambridge B1 Preliminary Speaking Part 2 practice.
-- These prompts are deliberately tagged examTrack=PET so they are excluded
-- from the normal three-part Daily Speaking rotation and appear only in the
-- dedicated PET picture-description practice view.

INSERT OR IGNORE INTO content_items
(id,content_type,title,school_level,topic,source_url,licence,status,active_version,description,source_attribution,published_at,scope)
VALUES
('pet-speak-classroom','oral_prompt','A Busy Classroom','S1','School',NULL,'owned','published',1,'PET-style picture description: students working together in a classroom.','English Mastery original PET practice',CURRENT_TIMESTAMP,'global'),
('pet-speak-cooking','oral_prompt','Cooking Together','S1','Home',NULL,'owned','published',1,'PET-style picture description: people preparing food together.','English Mastery original PET practice',CURRENT_TIMESTAMP,'global'),
('pet-speak-shopping','oral_prompt','At the Supermarket','S1','Shopping',NULL,'owned','published',1,'PET-style picture description: people shopping for groceries.','English Mastery original PET practice',CURRENT_TIMESTAMP,'global'),
('pet-speak-football','oral_prompt','Playing Football','S1','Sport',NULL,'owned','published',1,'PET-style picture description: young people playing football outdoors.','English Mastery original PET practice',CURRENT_TIMESTAMP,'global'),
('pet-speak-park','oral_prompt','An Afternoon in the Park','S1','Leisure',NULL,'owned','published',1,'PET-style picture description: different people enjoying a public park.','English Mastery original PET practice',CURRENT_TIMESTAMP,'global'),
('pet-speak-cafe','oral_prompt','Meeting at a Café','S1','Food and Friends',NULL,'owned','published',1,'PET-style picture description: friends talking in a café.','English Mastery original PET practice',CURRENT_TIMESTAMP,'global'),
('pet-speak-travel','oral_prompt','Waiting to Travel','S1','Travel',NULL,'owned','published',1,'PET-style picture description: travellers waiting with luggage.','English Mastery original PET practice',CURRENT_TIMESTAMP,'global'),
('pet-speak-party','oral_prompt','A Birthday Celebration','S1','Celebrations',NULL,'owned','published',1,'PET-style picture description: a small birthday celebration.','English Mastery original PET practice',CURRENT_TIMESTAMP,'global'),
('pet-speak-library','oral_prompt','Studying in the Library','S1','Learning',NULL,'owned','published',1,'PET-style picture description: students reading and studying in a library.','English Mastery original PET practice',CURRENT_TIMESTAMP,'global'),
('pet-speak-beach','oral_prompt','A Day at the Beach','S1','Holidays',NULL,'owned','published',1,'PET-style picture description: people relaxing and playing by the sea.','English Mastery original PET practice',CURRENT_TIMESTAMP,'global');

INSERT OR IGNORE INTO content_versions
(id,content_id,version,body_json,generation_model,curriculum_version_id,review_status)
VALUES
('pet-speak-classroom-v1','pet-speak-classroom',1,
 '{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Here is your photograph. It shows students in a classroom. Please tell us what you can see in the photograph.","stimulusImageUrl":"https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80","stimulusImageAlt":"Students learning together in a classroom.","stimulusAlt":"A classroom with several students working together at desks while a teacher helps nearby. Books, notebooks and classroom materials are visible.","sceneFocus":["people","place","activities","objects","clothes"],"examinerPrompts":["Talk about the people.","Talk about the place.","Talk about other things in the photograph."]}',
 'pet-original','CAMBRIDGE-B1-PRELIMINARY','approved'),
('pet-speak-cooking-v1','pet-speak-cooking',1,
 '{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Here is your photograph. It shows people cooking together. Please tell us what you can see in the photograph.","stimulusImageUrl":"https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1200&q=80","stimulusImageAlt":"People preparing food together in a kitchen.","stimulusAlt":"Two or more people are preparing food in a bright kitchen. Ingredients, bowls and cooking equipment are on the work surface.","sceneFocus":["people","kitchen","food","actions","objects"],"examinerPrompts":["Talk about the people.","Talk about the place.","Talk about what they are doing."]}',
 'pet-original','CAMBRIDGE-B1-PRELIMINARY','approved'),
('pet-speak-shopping-v1','pet-speak-shopping',1,
 '{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Here is your photograph. It shows people shopping. Please tell us what you can see in the photograph.","stimulusImageUrl":"https://images.unsplash.com/photo-1543168256-418811576931?auto=format&fit=crop&w=1200&q=80","stimulusImageAlt":"People choosing food while shopping.","stimulusAlt":"Shoppers are choosing food in a supermarket or market. Shelves or displays contain different products and people are carrying baskets or bags.","sceneFocus":["people","products","shopping actions","place","objects"],"examinerPrompts":["Talk about the people.","Talk about the place.","Talk about other things you can see."]}',
 'pet-original','CAMBRIDGE-B1-PRELIMINARY','approved'),
('pet-speak-football-v1','pet-speak-football',1,
 '{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Here is your photograph. It shows young people playing football. Please tell us what you can see in the photograph.","stimulusImageUrl":"https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1200&q=80","stimulusImageAlt":"Young people playing football outside.","stimulusAlt":"A group of young people are playing football outdoors. They are wearing sports clothes and moving around a pitch or open field.","sceneFocus":["players","sport","clothes","weather","actions"],"examinerPrompts":["Talk about the people.","Talk about the place.","Talk about what is happening."]}',
 'pet-original','CAMBRIDGE-B1-PRELIMINARY','approved'),
('pet-speak-park-v1','pet-speak-park',1,
 '{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Here is your photograph. It shows people spending time in a park. Please tell us what you can see in the photograph.","stimulusImageUrl":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80","stimulusImageAlt":"People enjoying time outdoors in a park.","stimulusAlt":"People are spending time in a green public park. Some are walking or sitting while others are enjoying outdoor activities.","sceneFocus":["people","park","weather","activities","background"],"examinerPrompts":["Talk about the people.","Talk about the place.","Talk about other things in the photograph."]}',
 'pet-original','CAMBRIDGE-B1-PRELIMINARY','approved'),
('pet-speak-cafe-v1','pet-speak-cafe',1,
 '{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Here is your photograph. It shows people in a café. Please tell us what you can see in the photograph.","stimulusImageUrl":"https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80","stimulusImageAlt":"People sitting and talking in a café.","stimulusAlt":"People are sitting at tables in a café, talking and having drinks or snacks. Cups, plates and furniture are visible around them.","sceneFocus":["people","food and drink","furniture","actions","place"],"examinerPrompts":["Talk about the people.","Talk about the place.","Talk about what they are doing."]}',
 'pet-original','CAMBRIDGE-B1-PRELIMINARY','approved'),
('pet-speak-travel-v1','pet-speak-travel',1,
 '{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Here is your photograph. It shows people waiting to travel. Please tell us what you can see in the photograph.","stimulusImageUrl":"https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80","stimulusImageAlt":"Travellers waiting with luggage.","stimulusAlt":"Travellers are waiting in a station or airport with bags and suitcases. Signs, seats and travel information can be seen nearby.","sceneFocus":["travellers","luggage","transport place","signs","actions"],"examinerPrompts":["Talk about the people.","Talk about the place.","Talk about other things you can see."]}',
 'pet-original','CAMBRIDGE-B1-PRELIMINARY','approved'),
('pet-speak-party-v1','pet-speak-party',1,
 '{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Here is your photograph. It shows people at a birthday celebration. Please tell us what you can see in the photograph.","stimulusImageUrl":"https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1200&q=80","stimulusImageAlt":"People enjoying a birthday celebration.","stimulusAlt":"A group of people are celebrating a birthday together. Decorations, food and a cake or presents can be seen while people talk and smile.","sceneFocus":["people","celebration","decorations","food","actions"],"examinerPrompts":["Talk about the people.","Talk about the place.","Talk about other things in the photograph."]}',
 'pet-original','CAMBRIDGE-B1-PRELIMINARY','approved'),
('pet-speak-library-v1','pet-speak-library',1,
 '{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Here is your photograph. It shows people studying in a library. Please tell us what you can see in the photograph.","stimulusImageUrl":"https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80","stimulusImageAlt":"People reading and studying in a library.","stimulusAlt":"Students are reading or studying in a library. Bookshelves, tables, books and study materials fill the room.","sceneFocus":["students","library","books","study activities","objects"],"examinerPrompts":["Talk about the people.","Talk about the place.","Talk about what they are doing."]}',
 'pet-original','CAMBRIDGE-B1-PRELIMINARY','approved'),
('pet-speak-beach-v1','pet-speak-beach',1,
 '{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Here is your photograph. It shows people at the beach. Please tell us what you can see in the photograph.","stimulusImageUrl":"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80","stimulusImageAlt":"People enjoying a day at the beach.","stimulusAlt":"People are spending time at a beach near the sea. Some are relaxing while others are walking, playing or enjoying the water.","sceneFocus":["people","beach","weather","clothes","activities"],"examinerPrompts":["Talk about the people.","Talk about the place.","Talk about other things in the photograph."]}',
 'pet-original','CAMBRIDGE-B1-PRELIMINARY','approved');
