PRAGMA foreign_keys = ON;

-- PET v2: use photographs with people taking part in recognisable activities,
-- with four or five image-specific guiding questions per task.
-- These are practice scaffolds, not official PET Part 2 examiner questions.
-- Add version 2 so already-deployed D1 databases receive the updated content.

INSERT OR IGNORE INTO content_versions (id,content_id,version,body_json,generation_model,curriculum_version_id,review_status)
VALUES ('pet-speak-classroom-v2','pet-speak-classroom',2,'{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Look at the photograph. Describe what the people are doing, then answer the questions below.","stimulusImageUrl":"https://unsplash.com/photos/a-group-of-children-sitting-at-desks-in-a-classroom-hXLkFpvKRys/download?force=true&w=1200","stimulusImageAlt":"Children in a classroom taking part in a lesson.","stimulusAlt":"Children are sitting at their desks while a teacher leads a lesson.","sceneFocus":["main people","main action","setting","visible details"],"examinerPrompts":["Who can you see in the classroom?","What are the children doing at their desks?","What is the teacher doing during the lesson?","What details tell you this is a classroom?"]}','pet-original-v2','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved');
UPDATE content_items SET active_version=2,title='A Classroom Lesson',description='Children are sitting at their desks while a teacher leads a lesson.' WHERE id='pet-speak-classroom' AND active_version <= 2;

INSERT OR IGNORE INTO content_versions (id,content_id,version,body_json,generation_model,curriculum_version_id,review_status)
VALUES ('pet-speak-cooking-v2','pet-speak-cooking',2,'{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Look at the photograph. Describe what the people are doing, then answer the questions below.","stimulusImageUrl":"https://unsplash.com/photos/mother-and-daughter-cook-food-together-in-the-kitchen-oXnbcOcvV5k/download?force=true&w=1200","stimulusImageAlt":"A mother teaching her daughter to prepare vegetables in the kitchen.","stimulusAlt":"A mother is helping her daughter cut vegetables as they prepare food together in a kitchen.","sceneFocus":["main people","main action","setting","visible details"],"examinerPrompts":["Who are the two people in the kitchen?","What are the mother and daughter preparing?","How is the mother helping the girl?","What kitchen items or ingredients can you see?","How do you think they feel while cooking?"]}','pet-original-v2','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved');
UPDATE content_items SET active_version=2,title='Cooking with Mum',description='A mother is helping her daughter cut vegetables as they prepare food together in a kitchen.' WHERE id='pet-speak-cooking' AND active_version <= 2;

INSERT OR IGNORE INTO content_versions (id,content_id,version,body_json,generation_model,curriculum_version_id,review_status)
VALUES ('pet-speak-shopping-v2','pet-speak-shopping',2,'{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Look at the photograph. Describe what the people are doing, then answer the questions below.","stimulusImageUrl":"https://unsplash.com/photos/a-person-selling-fruits-at-an-outdoor-market-52gZQu4zwrM/download?force=true&w=1200","stimulusImageAlt":"A market seller speaking to a customer beside a fruit display.","stimulusAlt":"A fruit seller is talking with a customer at a colourful outdoor market stall.","sceneFocus":["main people","main action","setting","visible details"],"examinerPrompts":["Who are the main people at the fruit stall?","What are the seller and customer doing?","Which kinds of fruit can you see?","What details show this is an outdoor market?"]}','pet-original-v2','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved');
UPDATE content_items SET active_version=2,title='Buying Fruit at the Market',description='A fruit seller is talking with a customer at a colourful outdoor market stall.' WHERE id='pet-speak-shopping' AND active_version <= 2;

INSERT OR IGNORE INTO content_versions (id,content_id,version,body_json,generation_model,curriculum_version_id,review_status)
VALUES ('pet-speak-football-v2','pet-speak-football',2,'{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Look at the photograph. Describe what the people are doing, then answer the questions below.","stimulusImageUrl":"https://unsplash.com/photos/boys-playing-soccer-dmefLgEYM_k/download?force=true&w=1200","stimulusImageAlt":"Children taking part in a football game outdoors.","stimulusAlt":"Children are playing football on a grassy field.","sceneFocus":["main people","main action","setting","visible details"],"examinerPrompts":["Who is playing on the field?","What are the children doing with the football?","What are they wearing?","What can you see around the playing area?","How might the players be feeling?"]}','pet-original-v2','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved');
UPDATE content_items SET active_version=2,title='Playing Football After School',description='Children are playing football on a grassy field.' WHERE id='pet-speak-football' AND active_version <= 2;

INSERT OR IGNORE INTO content_versions (id,content_id,version,body_json,generation_model,curriculum_version_id,review_status)
VALUES ('pet-speak-park-v2','pet-speak-park',2,'{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Look at the photograph. Describe what the people are doing, then answer the questions below.","stimulusImageUrl":"https://unsplash.com/photos/volunteers-cleaning-a-park-with-blue-trash-bags-U20gjfPjtuI/download?force=true&w=1200","stimulusImageAlt":"Volunteers picking up litter with rubbish bags in a green outdoor area.","stimulusAlt":"Young volunteers are collecting rubbish outdoors and putting it in large bags.","sceneFocus":["main people","main action","setting","visible details"],"examinerPrompts":["Who are the people working outdoors?","What are the volunteers doing?","What equipment are they using to collect rubbish?","What details can you see in the background?","Why might they be cleaning this area?"]}','pet-original-v2','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved');
UPDATE content_items SET active_version=2,title='Volunteers Cleaning a Park',description='Young volunteers are collecting rubbish outdoors and putting it in large bags.' WHERE id='pet-speak-park' AND active_version <= 2;

INSERT OR IGNORE INTO content_versions (id,content_id,version,body_json,generation_model,curriculum_version_id,review_status)
VALUES ('pet-speak-cafe-v2','pet-speak-cafe',2,'{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Look at the photograph. Describe what the people are doing, then answer the questions below.","stimulusImageUrl":"https://unsplash.com/photos/friends-are-chatting-and-having-coffee-at-a-cafe-rioA77g2-XU/download?force=true&w=1200","stimulusImageAlt":"Friends sitting together, chatting and laughing at a café.","stimulusAlt":"A group of friends are chatting and laughing together over drinks in a café.","sceneFocus":["main people","main action","setting","visible details"],"examinerPrompts":["Who is sitting together in the café?","What are the friends doing?","What food or drinks can you see?","What suggests they are enjoying their time together?"]}','pet-original-v2','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved');
UPDATE content_items SET active_version=2,title='Friends Talking at a Café',description='A group of friends are chatting and laughing together over drinks in a café.' WHERE id='pet-speak-cafe' AND active_version <= 2;

INSERT OR IGNORE INTO content_versions (id,content_id,version,body_json,generation_model,curriculum_version_id,review_status)
VALUES ('pet-speak-travel-v2','pet-speak-travel',2,'{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Look at the photograph. Describe what the people are doing, then answer the questions below.","stimulusImageUrl":"https://unsplash.com/photos/people-waiting-in-an-airport-terminal-with-large-windows-92tpaLLCi1g/download?force=true&w=1200","stimulusImageAlt":"People waiting for a flight in an airport terminal.","stimulusAlt":"Travellers are sitting and waiting with their luggage in an airport departure lounge.","sceneFocus":["main people","main action","setting","visible details"],"examinerPrompts":["Who can you see in the airport lounge?","What are the travellers doing?","What luggage or travel items can you spot?","What details tell you they are at an airport?","What do you think the travellers are waiting for?"]}','pet-original-v2','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved');
UPDATE content_items SET active_version=2,title='Waiting for a Flight',description='Travellers are sitting and waiting with their luggage in an airport departure lounge.' WHERE id='pet-speak-travel' AND active_version <= 2;

INSERT OR IGNORE INTO content_versions (id,content_id,version,body_json,generation_model,curriculum_version_id,review_status)
VALUES ('pet-speak-party-v2','pet-speak-party',2,'{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Look at the photograph. Describe what the people are doing, then answer the questions below.","stimulusImageUrl":"https://unsplash.com/photos/children-blowing-out-candles-on-a-birthday-cake-O67Yv-QXX9Y/download?force=true&w=1200","stimulusImageAlt":"Children at a birthday party with a cake and candles.","stimulusAlt":"Children are celebrating a birthday and blowing out candles on a cake.","sceneFocus":["main people","main action","setting","visible details"],"examinerPrompts":["Who are the people at the birthday party?","What are the children doing with the cake?","What party decorations or objects can you see?","How do the children seem to feel?","What might happen after the candles are blown out?"]}','pet-original-v2','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved');
UPDATE content_items SET active_version=2,title='Blowing Out Birthday Candles',description='Children are celebrating a birthday and blowing out candles on a cake.' WHERE id='pet-speak-party' AND active_version <= 2;

INSERT OR IGNORE INTO content_versions (id,content_id,version,body_json,generation_model,curriculum_version_id,review_status)
VALUES ('pet-speak-library-v2','pet-speak-library',2,'{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Look at the photograph. Describe what the people are doing, then answer the questions below.","stimulusImageUrl":"https://unsplash.com/photos/students-studying-at-tables-in-a-library-EP8lBWLFLkg/download?force=true&w=1200","stimulusImageAlt":"Students studying and writing at tables inside a library.","stimulusAlt":"Students are sitting at tables and working on their studies in a library.","sceneFocus":["main people","main action","setting","visible details"],"examinerPrompts":["Who is studying in the library?","What are the students doing at the tables?","What study materials can you see?","What features of the room show that it is a library?"]}','pet-original-v2','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved');
UPDATE content_items SET active_version=2,title='Studying in the Library',description='Students are sitting at tables and working on their studies in a library.' WHERE id='pet-speak-library' AND active_version <= 2;

INSERT OR IGNORE INTO content_versions (id,content_id,version,body_json,generation_model,curriculum_version_id,review_status)
VALUES ('pet-speak-beach-v2','pet-speak-beach',2,'{"mode":"stimulus","examTrack":"PET","petPart":2,"targetSeconds":60,"prompt":"Look at the photograph. Describe what the people are doing, then answer the questions below.","stimulusImageUrl":"https://unsplash.com/photos/a-group-of-kids-playing-soccer-on-the-beach-pP4vaAQOkO0/download?force=true&w=1200","stimulusImageAlt":"Children enjoying a game of football beside the sea.","stimulusAlt":"A group of children are playing football together on a sandy beach.","sceneFocus":["main people","main action","setting","visible details"],"examinerPrompts":["Who can you see on the beach?","What game are the children playing?","What details show they are near the sea?","What are the children wearing or carrying?","How might they feel during the game?"]}','pet-original-v2','SG-PRIMARY-ENGLISH-2020-PSLE-2026','approved');
UPDATE content_items SET active_version=2,title='Playing Football on the Beach',description='A group of children are playing football together on a sandy beach.' WHERE id='pet-speak-beach' AND active_version <= 2;
