import{getEnv}from"@/lib/cloudflare";
import{requireTenantSession}from"@/lib/auth/tenant";
import{resolveTenantIntegrations}from"@/lib/settings/tenant-runtime";
import{isLikelyNonContentUrl,validatePublicUrl}from"@/lib/content/extract";
import{canonicalUrl,duplicateSkip,duplicateSourceJob}from"@/lib/content/dedup";
import{parseClozeGenerationConfig,clozeConfigKey,type ClozeGenerationConfig}from"@/lib/content/cloze-config";
import{dispatchJob}from"@/lib/jobs/dispatch";
import{failJob}from"@/lib/jobs/store";
type Domain="reading"|"speaking"|"writing"|"cloze";type BatchItem={title?:string;url?:string};type Prepared={contentId:string|null;jobId:string;title:string;url:string;requestJson:string};
function domainOf(v:unknown):Domain{return v==="speaking"||v==="writing"||v==="cloze"?v:"reading"}function contentType(d:Domain){return d==="speaking"?"oral_prompt":d==="writing"?"writing_prompt":"article"}
export async function POST(request:Request){
 const a=await requireTenantSession(request);if(a.response)return a.response;const s=a.session!,body=await request.json().catch(()=>({}))as Record<string,unknown>,domain=domainOf(body.domain),sourceId=typeof body.sourceId==="string"?body.sourceId:"",rawItems=Array.isArray(body.items)?body.items.filter((x):x is BatchItem=>Boolean(x&&typeof x==="object")):[],schoolLevel=body.schoolLevel==="P5"?"P5":"P6",topic=typeof body.topic==="string"&&body.topic.trim()?body.topic.trim():"Current Affairs";
 if(!sourceId||!rawItems.length)return Response.json({error:"sourceId and at least one item are required"},{status:400});if(rawItems.length>20)return Response.json({error:"A batch can contain at most 20 lessons"},{status:400});
 let clozeConfig:ClozeGenerationConfig|null=null;try{if(domain==="cloze")clozeConfig=parseClozeGenerationConfig(body);}catch(e){return Response.json({error:e instanceof Error?e.message:"Invalid Cloze configuration"},{status:400});}const configKey=clozeConfig?clozeConfigKey(clozeConfig):null;
 const env=await resolveTenantIntegrations(getEnv(),s.tenant_id),source=await env.DB.prepare("SELECT id,name,usage_mode,allowed_host,enabled,domains_json FROM content_sources WHERE id=? AND enabled=1").bind(sourceId).first<{id:string;name:string;usage_mode:string;allowed_host:string;enabled:number;domains_json:string}>();if(!source)return Response.json({error:"Content source not found or disabled"},{status:404});if(!String(source.domains_json||"").includes(`\"${domain}\"`))return Response.json({error:`This source is not enabled for ${domain}`},{status:400});if(!env.MODELBRIDGE_API_KEY||!env.MODELBRIDGE_CHAT_MODEL)return Response.json({error:"This tenant ModelBridge is not configured"},{status:503});
 const skillIds=Array.isArray(body.skillIds)?body.skillIds.filter((x):x is string=>typeof x==="string"):[],rejected:Array<Record<string,unknown>>=[],skipped:Array<Record<string,unknown>>=[],prepared:Prepared[]=[],seen=new Set<string>();
 for(const item of rawItems){const url=typeof item.url==="string"?item.url.trim():"",title=(typeof item.title==="string"?item.title.trim():"Generating lesson…").slice(0,180);if(!url){rejected.push({title:title||"Untitled",status:"rejected",error:"Missing URL"});continue}const key=canonicalUrl(url);if(seen.has(key)){skipped.push({title:title||url,url,status:"skipped",reason:"Duplicate item in this batch"});continue}seen.add(key);try{validatePublicUrl(url,source.allowed_host)}catch(e){rejected.push({title:title||url,url,status:"rejected",error:e instanceof Error?e.message:"Invalid URL"});continue}if(isLikelyNonContentUrl(url)){rejected.push({title:title||url,url,status:"rejected",error:"SOURCE_NOT_CONTENT_PAGE: URL looks like a service, form, login or submission page. Choose an article/reference page instead."});continue}
  const dup=domain==="cloze"?await duplicateSourceJob(env.DB,{url,domain,schoolLevel,scope:"tenant",tenantId:s.tenant_id,configKey}):await duplicateSkip(env.DB,{contentType:contentType(domain),schoolLevel,scope:"tenant",tenantId:s.tenant_id,sourceUrl:url,title});if(dup.skipped){skipped.push({title:title||url,url,status:"skipped",existingId:dup.existingId,existingStatus:dup.existingStatus});continue}
  const contentId=domain==="cloze"?null:`content-${crypto.randomUUID()}`,jobId=`job-${crypto.randomUUID()}`;const clozeFields=clozeConfig?{clozeMinChars:clozeConfig.minChars,clozeMaxChars:clozeConfig.maxChars,clozeBlankCount:clozeConfig.blankCount,clozeConfigKey:configKey}:{};prepared.push({contentId,jobId,title:title||"Generating lesson…",url,requestJson:JSON.stringify({sourceId,url,schoolLevel,topic,skillIds,contentId,domain,...clozeFields})});
 }
 if(!prepared.length){if(skipped.length)return Response.json({ok:true,domain,accepted:0,queued:0,skipped:skipped.length,failed:rejected.length,results:[...skipped,...rejected]});return Response.json({error:"No valid items in this batch",accepted:0,failed:rejected.length,results:rejected},{status:400})}
 const statements:D1PreparedStatement[]=[];for(const p of prepared){if(p.contentId)statements.push(env.DB.prepare("INSERT INTO content_items (id,content_type,title,school_level,topic,source_url,licence,status,active_version,description,source_attribution,generation_job_id,generation_stage,tenant_id,scope) VALUES (?,?,?,?,?,?,?,'generating',1,?,?,?,?,?,'tenant')").bind(p.contentId,contentType(domain),p.title,schoolLevel,topic,p.url,source.usage_mode||"reference_only","Task created. Waiting to fetch source…",`${source.name} · generation in progress`,p.jobId,"queued",s.tenant_id));statements.push(env.DB.prepare("INSERT INTO generation_jobs (id,job_type,entity_type,entity_id,source_id,status,stage,progress,request_json,created_by,max_retries,tenant_id,scope) VALUES (?,?,?,?,?,'queued','queued',0,?,?,2,?,'tenant')").bind(p.jobId,domain==="reading"?"reading_import":"source_lesson_import",domain==="cloze"?"source_item":"content",p.contentId||p.jobId,sourceId,p.requestJson,s.user_id,s.tenant_id))}await env.DB.batch(statements);
 const dispatched:string[]=[],dispatchFailed:string[]=[];for(const p of prepared){try{await dispatchJob(p.jobId,env);dispatched.push(p.jobId)}catch(e){dispatchFailed.push(p.jobId);await failJob(env.DB,p.jobId,e)}}const results=[...prepared.map(p=>({title:p.title,url:p.url,contentId:p.contentId,jobId:p.jobId,status:dispatchFailed.includes(p.jobId)?"failed":"queued"})),...skipped,...rejected];return Response.json({ok:true,domain,accepted:prepared.length,queued:dispatched.length,skipped:skipped.length,failed:rejected.length+dispatchFailed.length,results},{status:202});
}
