import { PageIntro } from "@/components/ui";
type RoadmapStatus="done"|"next"|"partial"|"later";
type RoadmapGroup={title:string;items:Array<[string,RoadmapStatus]>};
const groups:RoadmapGroup[]=[
 {title:"V0.1 · Foundation",items:[["Cloudflare Workers + D1 + R2","done"],["39-node P5/P6 PSLE Skill Graph","done"],["Student Listen/Speak/Read/Write shell","done"],["Syllabus monitor + review jobs","done"]]},
 {title:"V0.2 · Reading learning loop",items:[["Admin authentication","done"],["Internet reading source discovery","done"],["ModelBridge age adaptation","done"],["Draft review / publish","done"],["D1-backed student reading","done"],["Question scoring / XP / mastery","done"]]},
 {title:"V0.3 · Listening learning loop",items:[["Expanded PSLE-suitable reading sources","done"],["YouTube channel discovery","done"],["Podcast RSS/Atom discovery","done"],["Authentic vs guided listening integrity","done"],["Listening lesson review / publish","done"],["D1-backed student listening","done"]]},
 {title:"V0.4 · Speaking + vocabulary + adaptive practice",items:[["Personal word / phrase vocabulary + SRS","done"],["Select text → explain → save","done"],["STT → ModelBridge conversation → TTS","done"],["Pronunciation / fluency assessment","done"],["Owned-audio dictation + shadowing","done"],["Daily / weekly adaptive planner + streak","done"]]},
 {title:"V0.5 · Accounts + Writing + Paper 2 + Diagnostics",items:[["Tenant Admin + Student profiles","done"],["Student login + PIN","done"],["Authenticated learning ownership","done"],["Student progress dashboard","done"],["Continuous + Situational Writing workspace","done"],["Hint-first AI writing evaluation","done"],["10-type Paper 2 question engine","done"],["Admin AI question generation + validation","done"],["Paper 2 practice sets","done"],["P5/P6 diagnostic assessment","done"],["Persistent async source / AI job model","done"],["Cloudflare Queue background runner","done"],["Generation status + failure + delete/cancel","done"],["Batch multi-select lesson creation","done"],["Dedicated Question Bank + 28 source registry","done"],["Specialised Oral / Reading / Cloze / Writing practice","done"],["Specialised Exam sessions with selectable item count","done"],["Question Bank auto-expansion batches","done"],["Persistent source brief → serial AI generation","done"],["Structure validation + duplicate detection + quality score","done"],["Bulk Question Bank review / publish / reject / retry","done"]]},
 {title:"Next milestones",items:[["Full four-paper PSLE mock assembly","next"],["Writing score calibration with teacher-marked samples","next"],["Tenant Admin weekly reporting","later"],["Secondary G1/G2/G3 curriculum expansion","later"]]},
];
export default function RoadmapPage(){return <><PageIntro eyebrow="Admin · Product" title="Implementation roadmap" description="Progress against the original Listen / Speak / Read / Write, task, mastery and PSLE-assessment design. Completed means a real data path exists, not only a mock screen."/><div className="roadmapGrid">{groups.map(g=><section className="card roadmapGroup" key={g.title}><div className="cardHeader"><h2>{g.title}</h2></div>{g.items.map(([label,status])=><div className="roadmapRow" key={label}><span className={`roadmapState ${status}`}>{status==="done"?"✓":status==="next"?"→":status==="partial"?"◐":"○"}</span><strong>{label}</strong><small>{status}</small></div>)}</section>)}</div></>}
