"use client";
import { useEffect, useMemo, useState } from "react";

type Field={configured:boolean;source:"admin"|"worker"|"none";value?:string;hint?:string;managed?:boolean;decryptError?:boolean;warning?:string};
type Payload={fields:Record<string,Field>;bootstrap:{settingsMasterKey:boolean;adminAccessToken:boolean;adminMonitorToken:boolean;queue:boolean;d1:boolean;r2:boolean}};
const empty={MODELBRIDGE_BASE_URL:"",MODELBRIDGE_CHAT_MODEL:"",MODELBRIDGE_STT_MODEL:"",STT_PROVIDER:"auto",MODELBRIDGE_TTS_MODEL:"",TTS_PROVIDER:"auto",MODELBRIDGE_TTS_VOICE:"alloy",AZURE_SPEECH_REGION:"",PRONUNCIATION_PROVIDER:"auto",SMTP_ENABLED:"false",SMTP_HOST:"",SMTP_PORT:"587",SMTP_SECURITY:"starttls",SMTP_AUTH:"login",SMTP_USERNAME:"",SMTP_FROM_EMAIL:"",SMTP_FROM_NAME:"English Mastery",SMTP_NOTIFY_TO:""};
function Status({field}:{field?:Field}){return <><span className={`integrationStatus ${field?.configured?"configured":"missing"}`}>{field?.configured?`Configured · ${field.source}`:"Not configured"}{field?.hint?` · ${field.hint}`:""}</span>{field?.warning&&<div className="fieldWarning">{field.warning}</div>}</>}
export function AdminIntegrationsSettings(){
 const [data,setData]=useState<Payload|null>(null),[values,setValues]=useState<Record<string,string>>(empty),[secrets,setSecrets]=useState<Record<string,string>>({}),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[testMsg,setTestMsg]=useState("");
 async function load(){const r=await fetch("/api/platform/settings/integrations",{cache:"no-store"});const b=await r.json() as Payload&{error?:string};if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);setData(b);setValues(v=>({...v,...Object.fromEntries(Object.entries(b.fields).filter(([,f])=>typeof f.value==="string").map(([k,f])=>[k,f.value||""]))}));}
 useEffect(()=>{load().catch(e=>setMsg(e instanceof Error?e.message:"Failed to load"))},[]);
 const hasFallback=useMemo(()=>Boolean(data&&Object.values(data.fields).some(f=>f.source==="worker")),[data]);
 const hasDecryptRepair=useMemo(()=>Boolean(data&&Object.values(data.fields).some(f=>f.decryptError&&f.source==="worker")),[data]);
 async function save(){setBusy(true);setMsg("");try{const cleanSecrets=Object.fromEntries(Object.entries(secrets).filter(([,v])=>v.trim()));const r=await fetch("/api/platform/settings/integrations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({values,secrets:cleanSecrets})});const b=await r.json() as Payload&{error?:string};if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);await load();setSecrets({});setMsg("Settings saved. New requests and background jobs will use them immediately.");}catch(e){setMsg(e instanceof Error?e.message:"Save failed")}finally{setBusy(false)}}
 async function migrate(){setBusy(true);try{const r=await fetch("/api/platform/settings/integrations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({migrateWorkerFallbacks:true})});const b=await r.json() as Payload&{migrated?:string[];error?:string};if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);setMsg(`Migrated/repaired ${b.migrated?.length||0} Worker values into the managed settings vault using the current SETTINGS_MASTER_KEY.`);await load();}catch(e){setMsg(e instanceof Error?e.message:"Migration failed")}finally{setBusy(false)}}
 async function clearManaged(key:string){if(!confirm(`Remove the Admin-managed override for ${key}? A legacy Worker fallback may become active again.`))return;setBusy(true);try{const r=await fetch("/api/platform/settings/integrations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clear:[key]})});const b=await r.json() as {error?:string};if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);await load();setMsg(`${key} managed override removed.`);}catch(e){setMsg(e instanceof Error?e.message:"Remove failed")}finally{setBusy(false)}}
 async function test(name:string){setTestMsg("Testing…");try{const r=await fetch("/api/platform/settings/integrations/test",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({integration:name})});const b=await r.json() as {ok?:boolean;detail?:string;error?:string};if(!r.ok||!b.ok)throw new Error(b.error||`HTTP ${r.status}`);setTestMsg(`✓ ${b.detail||"Connection successful"}`);}catch(e){setTestMsg(`✕ ${e instanceof Error?e.message:"Test failed"}`)}}
 const f=data?.fields||{};
 return <div className="integrationSettingsWrap">
  {!data?.bootstrap.settingsMasterKey&&<div className="notice errorNotice">Managed settings vault is not bootstrapped. Run <code>./scripts/deploy.sh update</code> once to create SETTINGS_MASTER_KEY.</div>}
  {hasFallback&&<div className="notice warnNotice">{hasDecryptRepair?"A managed credential cannot be decrypted with the current SETTINGS_MASTER_KEY. The web Worker is silently using a legacy Worker fallback; background Workers cannot use that fallback unless they also have it.":"Some values still come from Cloudflare Worker secrets/vars."} <button className="button smallButton secondary" disabled={busy} onClick={migrate}>{hasDecryptRepair?"Repair managed credentials":"Migrate existing Worker values"}</button></div>}
  {msg&&<div className="notice">{msg}</div>}{testMsg&&<div className="notice">{testMsg}</div>}
  <section className="card integrationCard"><div className="cardHeader"><h2>ModelBridge</h2><Status field={f.MODELBRIDGE_API_KEY}/></div><div className="formGrid threeCols">
   <label>Base URL<input value={values.MODELBRIDGE_BASE_URL||""} onChange={e=>setValues({...values,MODELBRIDGE_BASE_URL:e.target.value})}/></label>
   <label>Chat model<input value={values.MODELBRIDGE_CHAT_MODEL||""} onChange={e=>setValues({...values,MODELBRIDGE_CHAT_MODEL:e.target.value})}/></label>
   <label>API key <Status field={f.MODELBRIDGE_API_KEY}/><input type="password" placeholder={f.MODELBRIDGE_API_KEY?.configured?"Leave blank to keep current key":"Enter ModelBridge API key"} value={secrets.MODELBRIDGE_API_KEY||""} onChange={e=>setSecrets({...secrets,MODELBRIDGE_API_KEY:e.target.value})}/></label>
   <label>STT provider<select value={values.STT_PROVIDER||"auto"} onChange={e=>setValues({...values,STT_PROVIDER:e.target.value})}><option value="auto">Auto</option><option value="modelbridge">ModelBridge</option><option value="browser">Browser fallback</option></select></label><label>STT model<input value={values.MODELBRIDGE_STT_MODEL||""} onChange={e=>setValues({...values,MODELBRIDGE_STT_MODEL:e.target.value})} placeholder="Optional"/></label>
   <label>TTS provider<select value={values.TTS_PROVIDER||"auto"} onChange={e=>setValues({...values,TTS_PROVIDER:e.target.value})}><option value="auto">Auto</option><option value="modelbridge">ModelBridge</option><option value="browser">Browser fallback</option></select></label><label>TTS model<input value={values.MODELBRIDGE_TTS_MODEL||""} onChange={e=>setValues({...values,MODELBRIDGE_TTS_MODEL:e.target.value})} placeholder="Optional"/></label>
   <label>TTS voice<input value={values.MODELBRIDGE_TTS_VOICE||"alloy"} onChange={e=>setValues({...values,MODELBRIDGE_TTS_VOICE:e.target.value})}/></label>
  </div><div className="rowActions"><button className="button secondary" onClick={()=>test("modelbridge")}>Test chat</button><button className="button secondary" onClick={()=>test("tts")}>Test TTS</button>{f.MODELBRIDGE_API_KEY?.source==="admin"&&<button className="button ghost smallButton" onClick={()=>clearManaged("MODELBRIDGE_API_KEY")}>Remove managed API key</button>}</div></section>
  <section className="card integrationCard"><div className="cardHeader"><h2>YouTube Data API v3</h2><Status field={f.YOUTUBE_API_KEY}/></div><label>API key <input type="password" placeholder={f.YOUTUBE_API_KEY?.configured?"Leave blank to keep current key":"Enter YouTube API key"} value={secrets.YOUTUBE_API_KEY||""} onChange={e=>setSecrets({...secrets,YOUTUBE_API_KEY:e.target.value})}/></label><div className="rowActions"><button className="button secondary" onClick={()=>test("youtube")}>Test YouTube</button>{f.YOUTUBE_API_KEY?.source==="admin"&&<button className="button ghost smallButton" onClick={()=>clearManaged("YOUTUBE_API_KEY")}>Remove managed key</button>}</div></section>
  <section className="card integrationCard"><div className="cardHeader"><h2>Pronunciation provider</h2><Status field={f.AZURE_SPEECH_KEY}/></div><div className="formGrid threeCols"><label>Provider<select value={values.PRONUNCIATION_PROVIDER||"auto"} onChange={e=>setValues({...values,PRONUNCIATION_PROVIDER:e.target.value})}><option value="auto">Auto</option><option value="azure">Azure Speech</option><option value="heuristic">Free heuristic</option></select></label><label>Azure Speech region<input value={values.AZURE_SPEECH_REGION||""} onChange={e=>setValues({...values,AZURE_SPEECH_REGION:e.target.value})} placeholder="e.g. southeastasia"/></label><label>Azure Speech key <input type="password" placeholder={f.AZURE_SPEECH_KEY?.configured?"Leave blank to keep current key":"Optional"} value={secrets.AZURE_SPEECH_KEY||""} onChange={e=>setSecrets({...secrets,AZURE_SPEECH_KEY:e.target.value})}/></label></div><div className="rowActions">{f.AZURE_SPEECH_KEY?.source==="admin"&&<button className="button ghost smallButton" onClick={()=>clearManaged("AZURE_SPEECH_KEY")}>Remove managed key</button>}</div><p className="sourceHint">Without Azure Speech, Reading Aloud continues to use the free recognition-based practice estimate.</p></section>
  <section className="card integrationCard"><div className="cardHeader"><div><h2>SMTP email</h2><div className="tableSub">All system email notifications use this SMTP connection, including new-tenant welcome mail and Tenant Admin password reset links.</div></div><Status field={f.SMTP_PASSWORD}/></div><div className="formGrid threeCols">
   <label>Enabled<select value={values.SMTP_ENABLED||"false"} onChange={e=>setValues({...values,SMTP_ENABLED:e.target.value})}><option value="false">Disabled</option><option value="true">Enabled</option></select></label>
   <label>SMTP host<input value={values.SMTP_HOST||""} onChange={e=>setValues({...values,SMTP_HOST:e.target.value})} placeholder="smtp.example.com"/></label>
   <label>Port<input type="number" min="1" max="65535" value={values.SMTP_PORT||"587"} onChange={e=>setValues({...values,SMTP_PORT:e.target.value})}/></label>
   <label>Security<select value={values.SMTP_SECURITY||"starttls"} onChange={e=>setValues({...values,SMTP_SECURITY:e.target.value})}><option value="starttls">STARTTLS (recommended / 587)</option><option value="tls">TLS (typically 465)</option><option value="none">None</option></select></label>
   <label>Authentication<select value={values.SMTP_AUTH||"login"} onChange={e=>setValues({...values,SMTP_AUTH:e.target.value})}><option value="login">AUTH LOGIN</option><option value="plain">AUTH PLAIN</option><option value="none">No authentication</option></select></label>
   <label>Username<input value={values.SMTP_USERNAME||""} onChange={e=>setValues({...values,SMTP_USERNAME:e.target.value})} autoComplete="username"/></label>
   <label>Password <Status field={f.SMTP_PASSWORD}/><input type="password" autoComplete="new-password" placeholder={f.SMTP_PASSWORD?.configured?"Leave blank to keep current password":"Enter SMTP password"} value={secrets.SMTP_PASSWORD||""} onChange={e=>setSecrets({...secrets,SMTP_PASSWORD:e.target.value})}/></label>
   <label>From email<input type="email" value={values.SMTP_FROM_EMAIL||""} onChange={e=>setValues({...values,SMTP_FROM_EMAIL:e.target.value})} placeholder="no-reply@example.com"/></label>
   <label>From name<input value={values.SMTP_FROM_NAME||"English Mastery"} onChange={e=>setValues({...values,SMTP_FROM_NAME:e.target.value})}/></label>
   <label style={{gridColumn:"span 2"}}>Default notification recipients<input value={values.SMTP_NOTIFY_TO||""} onChange={e=>setValues({...values,SMTP_NOTIFY_TO:e.target.value})} placeholder="admin@example.com, ops@example.com"/></label>
  </div><div className="rowActions"><button className="button secondary" onClick={()=>test("smtp")}>Send test email</button>{f.SMTP_PASSWORD?.source==="admin"&&<button className="button ghost smallButton" onClick={()=>clearManaged("SMTP_PASSWORD")}>Remove managed password</button>}</div><p className="sourceHint">Cloudflare Workers blocks outbound SMTP port 25. Use port 587 with STARTTLS or port 465 with TLS.</p></section>
  <section className="card integrationCard"><div className="cardHeader"><h2>System bootstrap</h2><span>Read-only</span></div><div className="bootstrapGrid"><div><span>Settings master key</span><strong>{data?.bootstrap.settingsMasterKey?"Configured":"Missing"}</strong></div><div><span>Admin access token</span><strong>{data?.bootstrap.adminAccessToken?"Configured":"Missing"}</strong></div><div><span>Monitor token</span><strong>{data?.bootstrap.adminMonitorToken?"Configured":"Missing"}</strong></div><div><span>Task Queue</span><strong>{data?.bootstrap.queue?"Bound":"Missing"}</strong></div><div><span>D1</span><strong>{data?.bootstrap.d1?"Bound":"Missing"}</strong></div><div><span>R2</span><strong>{data?.bootstrap.r2?"Bound":"Missing"}</strong></div></div><p className="sourceHint">Bootstrap secrets are intentionally not editable here. They protect the admin session and the encrypted integration vault.</p></section>
  <div className="settingsSticky"><button className="button primary" disabled={busy||!data?.bootstrap.settingsMasterKey} onClick={save}>{busy?"Saving…":"Save integration settings"}</button></div>
 </div>
}
