"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import Link from "next/link";
type Source={id:string;name:string;source_type:"youtube_channel"|"podcast_rss";base_url:string;provider_ref?:string|null;topic?:string|null;default_level:"P5"|"P6";enabled:number};
type Item={id:string;title:string;url:string;provider:"youtube"|"podcast";description?:string;publishedAt?:string;mediaUrl?:string;thumbnailUrl?:string;durationSeconds?:number;madeForKids?:boolean|null;embeddable?:boolean;companionUrl?:string};
type Skill={id:string;name:string;domain:string;school_level:string};
type ContentRow={id:string;title:string;school_level:string;topic?:string;status:string;media_kind:string;provider:string;question_basis:string;question_count:number;generation_job_id?:string|null;generation_stage?:string|null;generation_error?:string|null;generation_progress?:number|null};
type JobResponse={job?:{status:string;stage:string;progress:number;result?:{items?:Item[]};error?:string|null}};
async function waitForJob(jobId:string,onProgress?:(s:string)=>void){for(let i=0;i<45;i++){await new Promise(r=>setTimeout(r,900));const res=await fetch(`/api/platform/jobs/${encodeURIComponent(jobId)}`);const b=await res.json().catch(()=>({})) as JobResponse;if(!res.ok)throw new Error("Task status unavailable");const j=b.job;if(!j)throw new Error("Task not found");onProgress?.(`${j.stage} · ${j.progress}%`);if(j.status==="succeeded")return j;if(j.status==="failed"||j.status==="cancelled")throw new Error(j.error||`Task ${j.status}`);}throw new Error("Task is still running. It remains in the library and can be checked later.");}
export function AdminListeningManager(){
 const[sources,setSources]=useState<Source[]>([]),[youtubeEnabled,setYoutubeEnabled]=useState(false),[skills,setSkills]=useState<Skill[]>([]),[contents,setContents]=useState<ContentRow[]>([]),[items,setItems]=useState<Item[]>([]),[selectedSource,setSelectedSource]=useState(""),selectedSourceRef=useRef(""),[selectedKeys,setSelectedKeys]=useState<string[]>([]),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const[libraryStatus,setLibraryStatus]=useState("all"),[selectedLessons,setSelectedLessons]=useState<string[]>([]),[sourceStatus,setSourceStatus]=useState("all");
 const[discoveryQuery,setDiscoveryQuery]=useState(""),[discoveryOrder,setDiscoveryOrder]=useState("date"),[discoveryLimit,setDiscoveryLimit]=useState(25);
 const[discoveryFilters,setDiscoveryFilters]=useState({publishedAfter:"",publishedBefore:"",minMinutes:"",maxMinutes:"",madeForKids:"all"});
 const[create,setCreate]=useState({schoolLevel:"P6",topic:"Listening Practice",skillIds:["L-MAIN","L-DETAIL","L-INFER"] as string[],useCompanion:false,teacherTranscript:""});const[newSource,setNewSource]=useState({name:"",sourceType:"youtube_channel",baseUrl:"",topic:"Science",defaultLevel:"P6"});
 async function load(){const[a,b,c]=await Promise.all([fetch("/api/platform/listening/sources"),fetch("/api/curriculum/skills"),fetch("/api/platform/listening/content")]);if(a.status===401){setMsg("Administrator sign-in required.");return;}const ab=await a.json() as {sources?:Source[];youtubeEnabled?:boolean};const bb=await b.json() as {skills?:Skill[]};const cb=await c.json() as {contents?:ContentRow[]};setSources(ab.sources||[]);setYoutubeEnabled(Boolean(ab.youtubeEnabled));setSkills(bb.skills||[]);setContents(cb.contents||[]);setSelectedSource(v=>{const next=v||ab.sources?.[0]?.id||"";selectedSourceRef.current=next;return next});}
 useEffect(()=>{void load();const t=setInterval(()=>{void load()},3500);return()=>clearInterval(t)},[]);
 const listeningSkills=useMemo(()=>skills.filter(s=>s.id.startsWith("L-")),[skills]);const src=sources.find(s=>s.id===selectedSource);const selectedItems=useMemo(()=>items.filter(i=>selectedKeys.includes(`${i.provider}:${i.id}`)),[items,selectedKeys]);
 const libraryStatuses=useMemo(()=>[...new Set(contents.map(c=>c.status))].sort(),[contents]);
 const filteredContents=useMemo(()=>contents.filter(c=>libraryStatus==="all"||c.status===libraryStatus),[contents,libraryStatus]);
 const filteredSources=useMemo(()=>sources.filter(s=>sourceStatus==="all"||(sourceStatus==="enabled"?Boolean(s.enabled):!s.enabled)),[sources,sourceStatus]);
 const selectedDrafts=filteredContents.filter(c=>selectedLessons.includes(c.id)&&c.status==="draft").length;
 useEffect(()=>setSelectedLessons([]),[libraryStatus]);
 useEffect(()=>{const visible=sources.filter(s=>sourceStatus==="all"||(sourceStatus==="enabled"?Boolean(s.enabled):!s.enabled));if(visible.some(s=>s.id===selectedSource))return;const next=visible[0];const id=next?.id||"";setSelectedSource(id);selectedSourceRef.current=id;setItems([]);setSelectedKeys([]);if(next)setCreate(v=>({...v,schoolLevel:next.default_level||"P6",topic:next.topic||"Listening Practice"}));},[sources,sourceStatus,selectedSource]);
 function fmt(sec?:number){if(!sec)return"";return`${Math.floor(sec/60)}:${String(sec%60).padStart(2,"0")}`}
 function toggleSkill(id:string){setCreate(v=>({...v,skillIds:v.skillIds.includes(id)?v.skillIds.filter(x=>x!==id):[...v.skillIds,id].slice(-6)}))}
 function keyOf(item:Item){return`${item.provider}:${item.id}`}
 function toggleItem(item:Item){const key=keyOf(item);setSelectedKeys(v=>v.includes(key)?v.filter(x=>x!==key):[...v,key])}
 function selectAll(){setSelectedKeys(items.map(keyOf))}
 async function discover(){if(!selectedSource)return;const sourceAtStart=selectedSource;setBusy(true);setSelectedKeys([]);setMsg("Discovery task queued…");const r=await fetch(`/api/platform/listening/sources/${encodeURIComponent(sourceAtStart)}/discover`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:discoveryQuery,maxResults:discoveryLimit,order:discoveryOrder,publishedAfter:discoveryFilters.publishedAfter,publishedBefore:discoveryFilters.publishedBefore,minDurationSeconds:discoveryFilters.minMinutes===""?undefined:Math.max(0,Math.round(Number(discoveryFilters.minMinutes)*60)),maxDurationSeconds:discoveryFilters.maxMinutes===""?undefined:Math.max(0,Math.round(Number(discoveryFilters.maxMinutes)*60)),madeForKids:discoveryFilters.madeForKids})});const b=await r.json().catch(()=>({})) as {jobId?:string;error?:string};if(!r.ok||!b.jobId){setBusy(false);setItems([]);setMsg(b.error||"Discovery failed");return;}try{const j=await waitForJob(b.jobId,s=>setMsg(`Discovering · ${s}`));if(selectedSourceRef.current===sourceAtStart){setItems(j.result?.items||[]);setMsg(`${j.result?.items?.length||0} eligible items discovered.`);}else{setMsg("Discovery for the previous source completed and remains in Work Queue. Current source was not overwritten.");}}catch(e){setMsg(e instanceof Error?e.message:"Discovery failed");}finally{setBusy(false)}}
 async function createDrafts(){if(selectedItems.length===0)return;setBusy(true);setMsg(`Creating ${selectedItems.length} persistent lesson records…`);const multi=selectedItems.length>1;const endpoint=multi?"/api/platform/listening/import/batch":"/api/platform/listening/import";const payload=multi?{sourceId:selectedSource,items:selectedItems,schoolLevel:create.schoolLevel,topic:create.topic,skillIds:create.skillIds,useCompanion:create.useCompanion}:{sourceId:selectedSource,item:selectedItems[0],...create};const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const b=await r.json().catch(()=>({})) as {error?:string;accepted?:number;skipped?:number;failed?:number;status?:string};setBusy(false);if(!r.ok){setMsg(b.error||"Could not create listening tasks");return;}setMsg(multi?`${b.accepted??0} lessons added to Lesson Library and queued${b.skipped?`; ${b.skipped} duplicate(s) skipped`:""}${b.failed?`; ${b.failed} failed validation`:""}.`:b.status==="skipped"?`Duplicate skipped. ${selectedItems[0].title} already exists in the Lesson Library.`:`Generation queued. ${selectedItems[0].title} is now in the Lesson Library.`);setSelectedKeys([]);setCreate(v=>({...v,teacherTranscript:""}));await load();}
 async function addSource(e:React.FormEvent){e.preventDefault();setBusy(true);const r=await fetch("/api/platform/listening/sources",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(newSource)});const b=await r.json().catch(()=>({})) as {error?:string};setBusy(false);if(!r.ok){setMsg(b.error||"Could not add source");return;}setMsg("Listening source added.");setNewSource({name:"",sourceType:"youtube_channel",baseUrl:"",topic:"Science",defaultLevel:"P6"});await load()}
 async function toggleSource(source:Source){
  setBusy(true);
  const r=await fetch("/api/platform/listening/sources",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:source.id,enabled:!Boolean(source.enabled)})});
  const b=await r.json().catch(()=>({})) as {error?:string};
  setBusy(false);
  setMsg(r.ok?`${source.name} ${source.enabled?"disabled":"enabled"}.`:b.error||"Could not update source");
  await load();
 }
 async function publish(id:string){if(!confirm("Publish this listening lesson and any draft questions to students?"))return;const r=await fetch(`/api/platform/content/${id}/publish`,{method:"POST"});const b=await r.json().catch(()=>({})) as {error?:string};setMsg(r.ok?"Listening lesson published.":b.error||"Publish failed");if(r.ok)await load()}
 async function removeJob(c:ContentRow){if(!c.generation_job_id||!confirm("Delete this finished/failed generation task record?"))return;const r=await fetch(`/api/platform/jobs/${c.generation_job_id}`,{method:"DELETE"});setMsg(r.ok?"Task record deleted.":"Delete failed.");await load();}
 function toggleLesson(id:string){setSelectedLessons(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 function selectFilteredLessons(){setSelectedLessons(filteredContents.map(c=>c.id))}
 async function publishSelected(){const ids=filteredContents.filter(c=>selectedLessons.includes(c.id)&&c.status==="draft").map(c=>c.id);if(!ids.length||!confirm(`Publish ${ids.length} selected draft listening lesson${ids.length===1?"":"s"}?`))return;setBusy(true);let changed=0;for(const id of ids){const r=await fetch(`/api/platform/content/${id}/publish`,{method:"POST"});if(r.ok)changed++;}setBusy(false);setSelectedLessons([]);setMsg(`${changed}/${ids.length} selected draft listening lesson${ids.length===1?"":"s"} published.`);await load();}
 async function deleteSelectedLessons(){const ids=filteredContents.filter(c=>selectedLessons.includes(c.id)).map(c=>c.id);if(!ids.length||!confirm(`Delete ${ids.length} selected listening lesson${ids.length===1?"":"s"}? They will be removed from the lesson library and any queued/running generation jobs will be cancelled.`))return;setBusy(true);const r=await fetch("/api/platform/listening/content",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids})});const b=await r.json().catch(()=>({})) as {deleted?:number;error?:string};setBusy(false);if(!r.ok){setMsg(b.error||"Could not delete selected lessons");return;}setSelectedLessons([]);setMsg(`${b.deleted||0}/${ids.length} selected listening lessons deleted.`);await load();}
 return <>{msg.includes("sign-in")&&<div className="notice warnNotice">{msg} <Link href="/platform/login">Sign in</Link></div>}<div className="notice" style={{marginTop:20}}><strong>Listening sources are configurable.</strong> Add any approved YouTube channel or podcast feed below. Nothing in the listening workflow depends on a hard-coded publisher. Choose a channel, optionally search inside that channel, review the returned videos, select the ones you want, and then create lessons.</div><div className="listeningAdminGrid"><section className="card"><div className="cardHeader"><div><h2>Listening content sources</h2><div className="tableSub">Discover up to 50 eligible videos from the selected channel.</div></div><span>{filteredSources.length} / {sources.length} sources</span></div><div className="formGrid"><label>Status<select value={sourceStatus} onChange={e=>setSourceStatus(e.target.value)}><option value="all">All sources</option><option value="enabled">Enabled</option><option value="disabled">Off</option></select></label><label className="fieldLabel">Source<select value={selectedSource} onChange={e=>{selectedSourceRef.current=e.target.value;setSelectedSource(e.target.value);setItems([]);setSelectedKeys([]);setDiscoveryQuery("");setDiscoveryFilters({publishedAfter:"",publishedBefore:"",minMinutes:"",maxMinutes:"",madeForKids:"all"});const s=sources.find(x=>x.id===e.target.value);setCreate(v=>({...v,schoolLevel:s?.default_level||"P6",topic:s?.topic||"Listening Practice"}))}}>{filteredSources.map(s=><option value={s.id} key={s.id}>{s.name} · {s.source_type==="youtube_channel"?"YouTube":"Podcast"}</option>)}</select></label></div>{src&&<div className="tableSub" style={{marginBottom:10}}>{src.base_url}</div>}{src&&!src.enabled&&<div className="notice warnNotice">This source is Off. Enable it before discovery.</div>}{src?.source_type==="youtube_channel"&&<>
 <div className="formGrid"><label>Search inside channel<input value={discoveryQuery} onChange={e=>setDiscoveryQuery(e.target.value)} placeholder="e.g. climate, animals, science" /></label><label>Sort<select value={discoveryOrder} onChange={e=>setDiscoveryOrder(e.target.value)}><option value="date">Newest first</option><option value="relevance">Relevance</option><option value="viewCount">Most viewed</option></select></label></div>
 <div className="formGrid"><label>Published from<input type="date" value={discoveryFilters.publishedAfter} onChange={e=>setDiscoveryFilters(v=>({...v,publishedAfter:e.target.value}))}/></label><label>Published to<input type="date" value={discoveryFilters.publishedBefore} onChange={e=>setDiscoveryFilters(v=>({...v,publishedBefore:e.target.value}))}/></label></div>
 <div className="formGrid"><label>Min duration (min)<input type="number" min="0" max="120" step="1" value={discoveryFilters.minMinutes} onChange={e=>setDiscoveryFilters(v=>({...v,minMinutes:e.target.value}))} placeholder="e.g. 2"/></label><label>Max duration (min)<input type="number" min="0" max="120" step="1" value={discoveryFilters.maxMinutes} onChange={e=>setDiscoveryFilters(v=>({...v,maxMinutes:e.target.value}))} placeholder="e.g. 15"/></label></div>
 <div className="formGrid"><label>Made for Kids<select value={discoveryFilters.madeForKids} onChange={e=>setDiscoveryFilters(v=>({...v,madeForKids:e.target.value}))}><option value="all">All</option><option value="yes">Yes only</option><option value="no">No / not marked</option></select></label><label>Results<select value={discoveryLimit} onChange={e=>setDiscoveryLimit(Number(e.target.value))}><option value={20}>20</option><option value={30}>30</option><option value={40}>40</option><option value={50}>50</option></select></label></div>
 <div className="rowActions"><button type="button" className="button ghost smallButton" onClick={()=>setDiscoveryFilters({publishedAfter:"",publishedBefore:"",minMinutes:"",maxMinutes:"",madeForKids:"all"})}>Clear filters</button><span className="tableSub">Filters are applied during discovery. The selected YouTube channel remains the only search scope; no hard-coded publisher catalog is used.</span></div>
 </>}{src?.source_type==="youtube_channel"&&!youtubeEnabled&&<div className="notice warnNotice">Platform YouTube API access is not available. Configure it in Platform Settings.</div>}<button className="button primary" disabled={busy||!selectedSource||!src?.enabled||(src?.source_type==="youtube_channel"&&!youtubeEnabled)} onClick={discover}>{busy?"Working…":discoveryQuery?`Search channel for “${discoveryQuery}”`:`Discover latest ${src?.source_type==="youtube_channel"?"videos":"items"}`}</button><div className="sourceHint">YouTube search is scoped to the configured channel. Search is optional; without a keyword the latest uploads are shown. You select the actual content to import—there is no fixed story catalog.</div></section><section className="card"><div className="cardHeader"><div><h2>Manage sources</h2><div className="tableSub">Platform Admin can add or turn off sources at any time.</div></div><span>YouTube or RSS/Atom</span></div><div className="sourceList">{sources.map(s=><div className="sourceListRow" key={s.id}><div><strong>{s.name}</strong><div className="tableSub">{s.source_type==="youtube_channel"?"YouTube channel":"Podcast feed"} · {s.enabled?"Enabled":"Off"}</div></div><button className="button ghost smallButton" disabled={busy} onClick={()=>toggleSource(s)}>{s.enabled?"Disable":"Enable"}</button></div>)}</div><div className="cardHeader" style={{marginTop:16}}><h3>Add source</h3><span>Custom source</span></div><form className="stackForm" onSubmit={addSource}><label>Type<select value={newSource.sourceType} onChange={e=>setNewSource({...newSource,sourceType:e.target.value})}><option value="youtube_channel">YouTube channel</option><option value="podcast_rss">Podcast RSS / Atom</option></select></label><label>Name<input required value={newSource.name} onChange={e=>setNewSource({...newSource,name:e.target.value})}/></label><label>{newSource.sourceType==="youtube_channel"?"Channel @handle / URL":"Feed URL"}<input required value={newSource.baseUrl} onChange={e=>setNewSource({...newSource,baseUrl:e.target.value})}/></label><div className="formGrid"><label>Topic<input value={newSource.topic} onChange={e=>setNewSource({...newSource,topic:e.target.value})}/></label><label>Default level<select value={newSource.defaultLevel} onChange={e=>setNewSource({...newSource,defaultLevel:e.target.value})}><option>P5</option><option>P6</option></select></label></div><button className="button secondary" disabled={busy}>Add listening source</button></form></section></div>
 {items.length>0&&<section className="card listeningDiscovery"><div className="cardHeader"><div><h2>Discovered items</h2><div className="tableSub">Select multiple items and create lessons in one batch. Review remains one lesson at a time.</div></div><div className="rowActions"><span>{selectedItems.length}/{items.length} selected</span><button className="button ghost smallButton" onClick={selectAll}>Select all</button><button className="button ghost smallButton" onClick={()=>setSelectedKeys([])}>Clear</button></div></div><div className="mediaDiscoveryGrid">{items.map(item=>{const chosen=selectedKeys.includes(keyOf(item));return <article className={chosen?"mediaDiscoverCard selectedMedia":"mediaDiscoverCard"} key={keyOf(item)}><label className="checkRow batchCheck"><input type="checkbox" checked={chosen} onChange={()=>toggleItem(item)}/>Select</label><div className="mediaThumb">{item.thumbnailUrl?<img src={item.thumbnailUrl} alt=""/>:<span>{item.provider==="youtube"?"▶":"♫"}</span>}</div><div><div className="activityKicker">{item.provider}{item.madeForKids===true?" · Made for Kids":""}</div><h3>{item.title}</h3><p>{item.description?.slice(0,180)||"No description supplied."}</p><small>{fmt(item.durationSeconds)}{item.publishedAt?` · ${new Date(item.publishedAt).toLocaleDateString()}`:""}</small></div></article>})}</div></section>}
 {selectedItems.length>0&&<section className="card createListeningCard"><div className="cardHeader"><h2>Create listening lessons</h2><span>{selectedItems.length} selected</span></div><div className="formGrid"><label>Level<select value={create.schoolLevel} onChange={e=>setCreate({...create,schoolLevel:e.target.value})}><option>P5</option><option>P6</option></select></label><label>Topic<input value={create.topic} onChange={e=>setCreate({...create,topic:e.target.value})}/></label></div><div className="fieldLabel"><span>PSLE listening skills</span><div className="skillPicker">{listeningSkills.map(s=><button type="button" key={s.id} className={create.skillIds.includes(s.id)?"skillPick active":"skillPick"} onClick={()=>toggleSkill(s.id)}>{s.name}</button>)}</div></div>{selectedItems.some(i=>i.provider==="podcast"&&i.companionUrl)&&<label className="checkRow"><input type="checkbox" checked={create.useCompanion} onChange={e=>setCreate({...create,useCompanion:e.target.checked})}/>Use publisher companion page where available</label>}{selectedItems.length===1?<label>Optional authorised transcript<textarea value={create.teacherTranscript} onChange={e=>setCreate({...create,teacherTranscript:e.target.value})}/></label>:<div className="notice">Authorised transcript is available only for a single-item create. Batch lessons use metadata and optional publisher companion pages.</div>}<div className="notice"><strong>Batch persistent workflow:</strong> all {selectedItems.length} lesson rows are created first with <em>generating</em> status, then each receives its own queue job. You can leave immediately and review drafts later.</div><button className="button primary" disabled={busy} onClick={createDrafts}>{busy?"Queueing…":`Create & queue ${selectedItems.length} lesson${selectedItems.length>1?"s":""}`}</button></section>}
 <section className="card" style={{marginTop:20}}><div className="cardHeader"><div><h2>Listening lesson library</h2><div className="tableSub">Filter by status, then select all matching lessons for bulk actions.</div></div><span>{filteredContents.length} / {contents.length} items</span></div>
 <div className="rowActions" style={{marginBottom:12}}><label>Status <select value={libraryStatus} onChange={e=>setLibraryStatus(e.target.value)}><option value="all">All statuses</option>{libraryStatuses.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label><button className="button ghost smallButton" disabled={!filteredContents.length} onClick={selectFilteredLessons}>Select filtered</button><button className="button ghost smallButton" onClick={()=>setSelectedLessons([])}>Clear</button><button className="button primary smallButton" disabled={!selectedDrafts||busy} onClick={publishSelected}>Publish selected drafts ({selectedDrafts})</button><button className="button ghost smallButton" disabled={!selectedLessons.length||busy} onClick={deleteSelectedLessons}>Delete selected ({selectedLessons.length})</button><span>{selectedLessons.length} selected</span></div>
 <div className="contentTableWrap"><table className="monitorTable"><thead><tr><th></th><th>Lesson</th><th>Media</th><th>Basis</th><th>Status</th><th>Questions</th><th>Action</th></tr></thead><tbody>{filteredContents.map(c=><tr key={c.id}><td><input aria-label={`Select ${c.title}`} type="checkbox" checked={selectedLessons.includes(c.id)} onChange={()=>toggleLesson(c.id)}/></td><td><strong>{c.title}</strong><div className="tableSub">{c.school_level} · {c.topic||"Listening"}{c.generation_stage?` · ${c.generation_stage}`:""}</div>{c.generation_error&&<div className="tableSub">{c.generation_error}</div>}</td><td>{c.media_kind} · {c.provider}</td><td>{c.question_basis}</td><td><span className={c.status==="published"?"statusPill published":"statusPill"}>{c.status}{c.status==="generating"&&typeof c.generation_progress==="number"?` ${c.generation_progress}%`:""}</span></td><td>{c.question_count}</td><td><div className="rowActions">{(c.status==="draft"||c.status==="published")&&<Link className="button ghost smallButton" href={`/platform/listening/${c.id}`}>Review</Link>}{c.status==="draft"&&<button className="button primary smallButton" onClick={()=>publish(c.id)}>Publish</button>}{c.status==="published"&&<Link className="button ghost smallButton" href={`/learn/listen/${c.id}`}>Student view</Link>}{c.generation_job_id&&c.status!=="published"&&<button className="button ghost smallButton" onClick={()=>removeJob(c)}>Delete task</button>}</div></td></tr>)}</tbody></table></div></section></>;
}
