"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {fetchStudentProgressCalendar,type StudentProgressCalendar} from "@/lib/client/progress-calendar";

type Data=StudentProgressCalendar;
function monthShift(month:string,delta:number){const[y,m]=month.split("-").map(Number),d=new Date(Date.UTC(y,m-1+delta,1));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}`}
function monthLabel(month:string){const[y,m]=month.split("-").map(Number);return new Intl.DateTimeFormat("en-SG",{month:"long",year:"numeric",timeZone:"Asia/Singapore"}).format(new Date(Date.UTC(y,m-1,1)))}
function studyLabel(seconds:number){if(seconds<60)return seconds>0?"<1m study":"0m study";const mins=Math.floor(seconds/60),h=Math.floor(mins/60),m=mins%60;return h?`${h}h${m?` ${m}m`:""} study`:`${m}m study`}
function idleLabel(count:number){return `${Math.max(0,count)} idle${count===1?"":"s"}`}
export function LearningProgressCalendar(){
 const now=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Singapore",year:"numeric",month:"2-digit"}).format(new Date()),[month,setMonth]=useState(now),[data,setData]=useState<Data|null>(null),[error,setError]=useState("");
 useEffect(()=>{let active=true;const load=()=>{setError("");fetchStudentProgressCalendar(month).then(b=>{if(active)setData(b)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Could not load progress calendar")})};load();const timer=month===now?setInterval(load,60_000):null;return()=>{active=false;if(timer)clearInterval(timer)}},[month,now]);
 const cells=useMemo(()=>{const[y,m]=month.split("-").map(Number),first=new Date(Date.UTC(y,m-1,1)),days=new Date(Date.UTC(y,m,0)).getUTCDate(),offset=(first.getUTCDay()+6)%7,map=new Map((data?.days||[]).map(d=>[d.date,d]));return [...Array(offset).fill(null),...Array.from({length:days},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,"0")}`;return{date,day:i+1,record:map.get(date)}})]},[month,data]);
 return <section className="card learningCalendar"><div className="calendarHeader"><div><div className="activityKicker">Daily progress</div><h2>{monthLabel(month)}</h2><p>Each day shows passed learning tasks, effective study time and idle episodes. A full 60 seconds without activity is excluded from study time and counts as one idle.</p></div><div className="rowActions"><button className="button ghost" onClick={()=>setMonth(m=>monthShift(m,-1))}>←</button><button className="button ghost" disabled={month===now} onClick={()=>setMonth(now)}>Today</button><button className="button ghost" disabled={month>=now} onClick={()=>setMonth(m=>monthShift(m,1))}>→</button></div></div>{error?<div className="notice warnNotice">{error}</div>:<><div className="calendarWeekdays">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(x=><span key={x}>{x}</span>)}</div><div className="calendarGrid">{cells.map((cell,i)=>cell?(cell.record?.total?<Link href={`/learn/history?date=${encodeURIComponent(cell.date)}`} key={cell.date} className={`calendarDay ${cell.date===data?.today?"today":""} ${cell.record?.percent===100?"complete":cell.record?.done?"partial":""}`} title={`${cell.record.done}/${cell.record.total} done · ${studyLabel(cell.record?.studySeconds||0)} · ${idleLabel(cell.record?.idleCount||0)} · View learning record`}><div className="calendarDayTop"><strong>{cell.day}</strong>{cell.date===data?.today&&<span>Today</span>}</div><div className="calendarProgress"><span style={{width:`${cell.record.percent}%`}}/></div><small>{cell.record.done}/{cell.record.total} · {cell.record.percent}%</small>{Boolean(cell.record?.studySeconds||cell.record?.idleCount)&&<div className="calendarStudyMeta"><small className="calendarStudyTime">⏱ {studyLabel(cell.record?.studySeconds||0)}</small><small className="calendarIdleCount">Idle {cell.record?.idleCount||0}×</small></div>}</Link>:<div key={cell.date} className={`calendarDay ${cell.date===data?.today?"today":""}`} title={`${studyLabel(cell.record?.studySeconds||0)} · ${idleLabel(cell.record?.idleCount||0)}`}><div className="calendarDayTop"><strong>{cell.day}</strong>{cell.date===data?.today&&<span>Today</span>}</div><small className="calendarEmpty">{cell.record?.studySeconds||cell.record?.idleCount?"No assigned tasks":"—"}</small>{Boolean(cell.record?.studySeconds||cell.record?.idleCount)&&<div className="calendarStudyMeta"><small className="calendarStudyTime">⏱ {studyLabel(cell.record?.studySeconds||0)}</small><small className="calendarIdleCount">Idle {cell.record?.idleCount||0}×</small></div>}</div>):<div className="calendarBlank" key={`blank-${i}`}/>)}</div></>}</section>
}
