"use client";
import {useEffect,useMemo,useState} from "react";

type Source={id:string;name:string;url:string;provider:string;source_kind:string;categories_json:string;usage_mode:string;licence_note?:string;priority:number};
function categories(s:Source){try{return JSON.parse(s.categories_json||"[]") as string[]}catch{return []}}
export function ReferenceSourcePanel({tenant=false,category,title}:{tenant?:boolean;category:"oral"|"writing"|"cloze"|"reading_comprehension";title:string}){
 const [rows,setRows]=useState<Source[]>([]),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({name:"",url:"",provider:"",sourceKind:`${category}_reference`,usageMode:"reference_only",licenceNote:"",priority:70});
 async function load(){const r=await fetch(tenant?"/api/admin/question-bank/sources":"/api/platform/question-bank/sources",{cache:"no-store"});const b=await r.json().catch(()=>({})) as {sources?:Source[]};if(r.ok)setRows(b.sources||[])}
 useEffect(()=>{void load()},[tenant,category]);
 const filtered=useMemo(()=>rows.filter(r=>categories(r).includes(category)),[rows,category]);
 async function add(e:React.FormEvent){e.preventDefault();if(tenant)return;setBusy(true);setMsg("");const r=await fetch("/api/platform/question-bank/sources",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,categories:[category]})});const b=await r.json().catch(()=>({})) as {error?:string};setBusy(false);setMsg(r.ok?"Reference source added.":b.error||"Could not add source");if(r.ok){setForm({name:"",url:"",provider:"",sourceKind:`${category}_reference`,usageMode:"reference_only",licenceNote:"",priority:70});await load()}}
 return <section className="card" style={{marginBottom:20}}><div className="cardHeader"><div><h2>{title}</h2><div className="tableSub">Reference sources guide topic, format and level. Protected source text is not copied into generated learner content.</div></div><span>{filtered.length} sources</span></div>
  <div className="contentTableWrap"><table className="monitorTable"><thead><tr><th>Source</th><th>Type</th><th>Usage</th></tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td><strong>{s.name}</strong><div className="tableSub">{s.provider}</div><a href={s.url} target="_blank" rel="noreferrer">Open source ↗</a></td><td>{s.source_kind}</td><td><span className="statusPill">{s.usage_mode}</span><div className="tableSub">{s.licence_note||""}</div></td></tr>)}</tbody></table></div>
  {!tenant&&<details style={{marginTop:16}}><summary>Add {title.toLowerCase()}</summary><form className="stackForm" onSubmit={add} style={{marginTop:12}}><div className="formGrid"><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Provider<input required value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}/></label></div><label>URL<input required type="url" value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/></label><div className="formGrid"><label>Source kind<input value={form.sourceKind} onChange={e=>setForm({...form,sourceKind:e.target.value})}/></label><label>Priority<input type="number" min="1" max="100" value={form.priority} onChange={e=>setForm({...form,priority:Number(e.target.value)||70})}/></label></div><label>Licence / usage note<textarea value={form.licenceNote} onChange={e=>setForm({...form,licenceNote:e.target.value})}/></label><button className="button secondary" disabled={busy}>{busy?"Saving…":"Add source"}</button></form></details>}{msg&&<div className="notice" style={{marginTop:12}}>{msg}</div>}</section>
}
