"use client";
import { useEffect,useMemo,useState } from "react";
type Level="P1-P4"|"P5"|"P6"|"S1"|"S2"|"S3"|"S4";
type Activity="listening"|"speaking"|"reading"|"writing"|"vocabulary"|"grammar"|"cloze";
type Difficulty="adaptive"|"easy"|"medium"|"hard";
type WordBook={id:string;name:string;code:string|null;stage:string|null;itemCount:number};
type Row={learnerStage:Level;activity:Activity;contentStage:Level;questionCount:number;difficulty:Difficulty;vocabularyReviewWindowDays:number;vocabularyReviewRepetitions:number;vocabularyCollectionId:string|null};
const levels:Level[]=["P1-P4","P5","P6","S1","S2","S3","S4"],activities:Activity[]=["listening","speaking","reading","writing","vocabulary","grammar","cloze"];
const labels:Record<Activity,string>={listening:"Listening",speaking:"Speaking",reading:"Reading",writing:"Writing",vocabulary:"Vocabulary",grammar:"Grammar",cloze:"Cloze"};
const defaults:Record<Activity,number>={listening:5,speaking:3,reading:10,writing:1,vocabulary:10,grammar:10,cloze:10};
const displayLevel=(value:Level)=>value==="P1-P4"?"P1–P4":value;
export function TenantPracticeSettings(){
 const[level,setLevel]=useState<Level>("P6"),[rows,setRows]=useState<Row[]>([]),[wordBooks,setWordBooks]=useState<WordBook[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 async function load(){const r=await fetch("/api/admin/practice-settings",{cache:"no-store"}),b=await r.json().catch(()=>({}))as{settings?:Row[];vocabularyCollections?:WordBook[]};setRows(b.settings||[]);setWordBooks(b.vocabularyCollections||[])}
 useEffect(()=>{void load()},[]);
 const current=useMemo(()=>activities.map(activity=>{const found=rows.find(r=>r.learnerStage===level&&r.activity===activity);return found||{learnerStage:level,activity,contentStage:level,questionCount:defaults[activity],difficulty:"adaptive" as Difficulty,vocabularyReviewWindowDays:7,vocabularyReviewRepetitions:2,vocabularyCollectionId:activity==="vocabulary"?(wordBooks.find(b=>b.stage===level)?.id||wordBooks[0]?.id||null):null}}),[rows,level,wordBooks]);
 function update(activity:Activity,patch:Partial<Row>){setRows(old=>{const rest=old.filter(r=>!(r.learnerStage===level&&r.activity===activity));const base=current.find(r=>r.activity===activity)!;return[...rest,{...base,...patch}]})}
 async function save(){setBusy(true);setMsg("");const data=activities.map(activity=>rows.find(r=>r.learnerStage===level&&r.activity===activity)||current.find(r=>r.activity===activity)!);const r=await fetch("/api/admin/practice-settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({learnerStage:level,settings:data})}),b=await r.json().catch(()=>({}))as{error?:string};setBusy(false);setMsg(r.ok?`${displayLevel(level)} practice settings saved.`:b.error||"Could not save practice settings");if(r.ok)await load()}
 return <>
  <div className="tabs settingsStageTabs">{levels.map(x=><button type="button" key={x} className={level===x?"active":""} onClick={()=>setLevel(x)}>{displayLevel(x)}</button>)}</div>
  <section className="card settingsTableCard">
   <div className="cardHeader"><div><h2>{displayLevel(level)} practice policy</h2><p>Configure each practice area in one compact table. Vocabulary book and review frequency apply only to Vocabulary Practice.</p></div></div>
   <div className="settingsTableWrap"><table className="dataTable settingsTable practiceSettingsTable"><thead><tr><th>Practice</th><th>Content stage</th><th>Questions / items</th><th>Difficulty</th><th>Word book</th><th>Review window</th><th>Required reviews</th></tr></thead><tbody>{current.map(row=><tr key={row.activity}><td><strong>{labels[row.activity]}</strong></td><td><select aria-label={`${labels[row.activity]} content stage`} value={row.contentStage} onChange={e=>update(row.activity,{contentStage:e.target.value as Level})}>{levels.map(x=><option key={x} value={x}>{displayLevel(x)}</option>)}</select></td><td><input aria-label={`${labels[row.activity]} items per practice`} type="number" min={1} max={50} value={row.questionCount} onChange={e=>update(row.activity,{questionCount:Math.max(1,Math.min(50,Number(e.target.value)||1))})}/></td><td><select aria-label={`${labels[row.activity]} difficulty`} value={row.difficulty} onChange={e=>update(row.activity,{difficulty:e.target.value as Difficulty})}><option value="adaptive">Adaptive</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></td><td>{row.activity==="vocabulary"?<select aria-label="Vocabulary practice word book" value={row.vocabularyCollectionId||""} onChange={e=>update(row.activity,{vocabularyCollectionId:e.target.value||null})}>{wordBooks.map(b=><option key={b.id} value={b.id}>{b.name} · {b.itemCount}</option>)}</select>:<span className="settingsDash">—</span>}</td><td>{row.activity==="vocabulary"?<div className="settingsNumberWithUnit"><input aria-label="Vocabulary review window days" type="number" min={1} max={30} value={row.vocabularyReviewWindowDays} onChange={e=>update(row.activity,{vocabularyReviewWindowDays:Math.max(1,Math.min(30,Number(e.target.value)||7))})}/><span>days</span></div>:<span className="settingsDash">—</span>}</td><td>{row.activity==="vocabulary"?<div className="settingsNumberWithUnit"><input aria-label="Vocabulary required reviews inside window" type="number" min={0} max={10} value={row.vocabularyReviewRepetitions} onChange={e=>update(row.activity,{vocabularyReviewRepetitions:Math.max(0,Math.min(10,Number(e.target.value)||0))})}/><span>times</span></div>:<span className="settingsDash">—</span>}</td></tr>)}</tbody></table></div>
   <div className="sourceHint settingsTableHint">Vocabulary Practice is locked to the selected system or Tenant-managed word book. Example: 7 days + 2 reviews means a recently practised term is prioritised on two additional practice days inside that window.</div>
  </section>
  <div className="rowActions settingsSaveRow"><button className="button primary" disabled={busy||!current.find(r=>r.activity==="vocabulary")?.vocabularyCollectionId} onClick={()=>void save()}>{busy?"Saving…":`Save ${displayLevel(level)} practice settings`}</button>{msg&&<span className="formStatus">{msg}</span>}</div>
 </>;
}
