"use client";
import Link from "next/link";
import {useEffect,useMemo,useRef,useState} from "react";
type Book={id:string;name:string;code?:string|null;description:string;collectionType:"system"|"custom";scope:"system"|"tenant";manageable:boolean;stage:string|null;itemCount:number;createdAt:string;updatedAt:string;studentVisible:boolean};
type BookItem={id:string;term:string;partOfSpeech:string|null;definition:string;itemOrder:number;synonyms:string[]};
type Mode="new"|"existing";
export function TenantVocabularyManager(){
 const[books,setBooks]=useState<Book[]>([]),[mode,setMode]=useState<Mode>("new"),[name,setName]=useState(""),[description,setDescription]=useState(""),[stage,setStage]=useState("P6"),[existingId,setExistingId]=useState(""),[text,setText]=useState(""),[sourceName,setSourceName]=useState("editor"),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[kind,setKind]=useState<"info"|"success"|"error">("info"),[manageId,setManageId]=useState<string|null>(null),[items,setItems]=useState<BookItem[]>([]),[query,setQuery]=useState(""),[itemTotal,setItemTotal]=useState(0),[editName,setEditName]=useState(""),[editDescription,setEditDescription]=useState(""),[editStage,setEditStage]=useState("P6");const fileRef=useRef<HTMLInputElement|null>(null);
 const managedBooks=useMemo(()=>books.filter(b=>b.manageable),[books]);
 async function load(){const r=await fetch("/api/admin/vocabulary/collections",{cache:"no-store"}),b=await r.json().catch(()=>({})) as {collections?:Book[];error?:string};if(!r.ok)throw new Error(b.error||"Could not load word books");const next=b.collections||[];setBooks(next);const editable=next.filter(x=>x.manageable);setExistingId(v=>v&&editable.some(x=>x.id===v)?v:editable[0]?.id||"");}
 useEffect(()=>{void load().catch(e=>{setKind("error");setMsg(e instanceof Error?e.message:"Could not load word books")})},[]);
 const lineCount=useMemo(()=>text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).length,[text]);
 async function createEmpty(){if(busy)return;setBusy(true);setMsg("");try{const r=await fetch("/api/admin/vocabulary/collections",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,description,stage})}),b=await r.json().catch(()=>({})) as {id?:string;error?:string};if(!r.ok||!b.id)throw new Error(b.error||"Could not create word book");setName("");setDescription("");await load();setExistingId(b.id);setMode("existing");setKind("success");setMsg("Empty Tenant word book created. Students can use it immediately; imports can be queued later.");}catch(e){setKind("error");setMsg(e instanceof Error?e.message:"Could not create word book")}finally{setBusy(false)}}
 async function queueImport(){if(busy)return;if(!text.trim()){setKind("error");setMsg("Paste vocabulary or load a TXT / CSV file first.");return}if(mode==="new"&&!name.trim()){setKind("error");setMsg("Enter a name for the new word book.");return}if(mode==="existing"&&!existingId){setKind("error");setMsg("Choose an existing Tenant word book.");return}setBusy(true);setMsg("Saving import task to the persistent Work Queue…");try{const r=await fetch("/api/admin/vocabulary/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode,name,description,stage,collectionId:existingId,text,sourceName})}),b=await r.json().catch(()=>({})) as {jobId?:string;collectionId?:string;total?:number;error?:string};if(!r.ok||!b.jobId)throw new Error(b.error||"Could not queue vocabulary import");setText("");setSourceName("editor");if(mode==="new"){setName("");setDescription("");setMode("existing");if(b.collectionId)setExistingId(b.collectionId)}await load();setKind("success");setMsg(`Vocabulary import queued · ${b.total||0} unique terms · job ${b.jobId}. It continues if you refresh or leave this page.`);}catch(e){setKind("error");setMsg(e instanceof Error?e.message:"Could not queue vocabulary import")}finally{setBusy(false)}}
 async function loadFile(file:File){try{const raw=await file.text();setText(raw);setSourceName(file.name);setKind("info");setMsg(`Loaded ${file.name}. The server will parse and deduplicate it when the background task is created.`);}catch{setKind("error");setMsg("Could not read that file.")}}
 async function openBook(book:Book,q=""){setManageId(book.id);setQuery(q);setEditName(book.name);setEditDescription(book.description||"");setEditStage(book.stage||"P6");const u=new URL(`/api/admin/vocabulary/collections/${encodeURIComponent(book.id)}`,window.location.origin);if(q)u.searchParams.set("q",q);const r=await fetch(u.pathname+u.search,{cache:"no-store"}),b=await r.json().catch(()=>({})) as {items?:BookItem[];total?:number;error?:string};if(!r.ok){setKind("error");setMsg(b.error||"Could not load word book");return}setItems(b.items||[]);setItemTotal(b.total||0);}
 async function saveBook(){if(!manageId)return;const r=await fetch(`/api/admin/vocabulary/collections/${encodeURIComponent(manageId)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:editName,description:editDescription,stage:editStage})}),b=await r.json().catch(()=>({})) as {error?:string};setKind(r.ok?"success":"error");setMsg(r.ok?"Word book details updated.":b.error||"Update failed");if(r.ok){await load();const updated={...books.find(x=>x.id===manageId)!,name:editName,description:editDescription,stage:editStage};await openBook(updated,query)}}
 async function remove(book:Book){if(!book.manageable)return;if(!confirm(`Delete “${book.name}”?`))return;const r=await fetch(`/api/admin/vocabulary/collections/${encodeURIComponent(book.id)}`,{method:"DELETE"}),b=await r.json().catch(()=>({})) as {error?:string};setKind(r.ok?"success":"error");setMsg(r.ok?`Deleted “${book.name}”.`:b.error||"Delete failed");if(r.ok){if(manageId===book.id){setManageId(null);setItems([])}await load();}}

 async function setSystemVisibility(book:Book,visible:boolean){if(book.collectionType!=="system"||busy)return;setBusy(true);try{const r=await fetch("/api/admin/vocabulary/system-visibility",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({collectionId:book.id,visible})}),b=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(b.error||"Could not update student visibility");setBooks(current=>current.map(x=>x.id===book.id?{...x,studentVisible:visible}:x));setKind("success");setMsg(`${book.name} is now ${visible?"visible":"hidden"} in student accounts.`);}catch(e){setKind("error");setMsg(e instanceof Error?e.message:"Could not update student visibility")}finally{setBusy(false)}}
 async function removeItem(item:BookItem){if(!manageId||!confirm(`Remove “${item.term}” from this word book?`))return;const r=await fetch(`/api/admin/vocabulary/collections/${encodeURIComponent(manageId)}/items/${encodeURIComponent(item.id)}`,{method:"DELETE"}),b=await r.json().catch(()=>({})) as {error?:string};setKind(r.ok?"success":"error");setMsg(r.ok?`Removed “${item.term}”.`:b.error||"Remove failed");if(r.ok){await load();const book=books.find(x=>x.id===manageId);if(book)await openBook(book,query)}}
 return <>
  <section className="card customWordbookBuilder"><div className="cardHeader"><div><span className="eyebrow">Tenant vocabulary</span><h2>Word book import</h2><p>Imports are persistent background jobs. They reuse the Tenant Work Queue, execute in FIFO order, and the runner permits only one job at a time.</p></div><div className="rowActions"><Link className="button secondary" href="/admin/learn-settings">Use for daily learning</Link><Link className="button secondary" href="/admin/jobs">Open Work Queue</Link></div></div>
   <div className="tabs"><button className={mode==="new"?"active":""} onClick={()=>setMode("new")}>New word book</button><button className={mode==="existing"?"active":""} disabled={!managedBooks.length} onClick={()=>setMode("existing")}>Add to existing</button></div>
   <div className="wordbookImportPanel">{mode==="new"?<div className="formGrid"><label><span className="fieldLabel">New word book name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. P6 Advanced Vocabulary"/></label><label><span className="fieldLabel">Stage</span><select value={stage} onChange={e=>setStage(e.target.value)}>{["P1-P4","P5","P6","S1","S2","S3","S4"].map(x=><option key={x}>{x}</option>)}</select></label><label className="wideField"><span className="fieldLabel">Description</span><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Optional description"/></label></div>:<label><span className="fieldLabel">Existing Tenant word book</span><select value={existingId} onChange={e=>setExistingId(e.target.value)}>{managedBooks.map(b=><option key={b.id} value={b.id}>{b.name} · {b.itemCount} terms</option>)}</select></label>}
    <textarea value={text} onChange={e=>{setText(e.target.value);setSourceName("editor")}} placeholder={'word,synonyms\nimportant,significant;crucial\ncareful,cautious;attentive\ncarry out,perform;conduct'}/><div className="tableSub">{lineCount?`${lineCount} non-empty source lines loaded. Final unique count is determined by the server.`:"TXT: one term per line. CSV: word/phrase in column 1, synonyms in later columns or separated by ; | /."}</div>
    <div className="rowActions"><input ref={fileRef} type="file" accept=".txt,.csv,text/plain,text/csv" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void loadFile(f);e.currentTarget.value=""}}/><button className="button secondary" disabled={busy} onClick={()=>fileRef.current?.click()}>Load TXT / CSV</button>{mode==="new"&&<button className="button secondary" disabled={busy||!name.trim()} onClick={()=>void createEmpty()}>Create empty word book</button>}<button className="button primary" disabled={busy||!text.trim()} onClick={()=>void queueImport()}>{busy?"Queueing…":mode==="new"?"Create & queue import":"Queue import"}</button></div>
   </div>{msg&&<div className={kind==="error"?"notice warnNotice":kind==="success"?"notice successNotice":"notice"}>{msg}</div>}
  </section>
  <section><div className="sectionHeading"><div><span>Vocabulary library</span><h2>Existing word books</h2><p>All custom word books are Tenant-owned. They can be incrementally imported, inspected, renamed and cleaned up. Platform System books are read-only, but Tenant Admin controls whether each one is visible in student accounts. P1-P4, P5 and P6 are visible by default; other System books are hidden until enabled. Daily Learning assignment is configured separately in Learning Settings.</p></div></div>{!books.length?<div className="emptyState">No word books available.</div>:<div className="wordbookGrid">{books.map(b=><article className="card wordbookCard" key={b.id}><div className="wordbookTop"><span className="entryTypePill">{b.manageable?"TENANT":"SYSTEM"}</span>{b.stage&&<span className="stageMini">{b.stage}</span>}</div><h3>{b.name}</h3><p>{b.description||"Vocabulary collection."}</p><div className="wordbookStats"><div><strong>{b.itemCount}</strong><span>terms</span></div></div>{b.collectionType==="system"&&<label className="systemVisibilityControl"><input type="checkbox" checked={b.studentVisible} disabled={busy} onChange={e=>void setSystemVisibility(b,e.target.checked)}/><span><strong>Visible to students</strong><small>{b.studentVisible?"Students can browse this System word book.":"Hidden from normal student word-book browsing."}</small></span></label>}<div className="rowActions"><button className="button secondary smallButton" onClick={()=>void openBook(b)}>View terms</button>{b.manageable&&<><button className="button secondary smallButton" onClick={()=>{setMode("existing");setExistingId(b.id);window.scrollTo({top:0,behavior:"smooth"})}}>Add terms</button><button className="button ghost smallButton dangerText" onClick={()=>void remove(b)}>Delete</button></>}</div></article>)}</div>}</section>
  {manageId&&(()=>{const b=books.find(x=>x.id===manageId);if(!b)return null;return <section className="card"><div className="cardHeader"><div><span className="eyebrow">{b.manageable?"Tenant word book":"System word book"}</span><h2>{b.name}</h2><p>{itemTotal} matching term{itemTotal===1?"":"s"}. System books are read-only.</p></div><button className="button ghost" onClick={()=>{setManageId(null);setItems([])}}>Close</button></div>{b.manageable&&<div className="formGrid"><label><span className="fieldLabel">Name</span><input value={editName} onChange={e=>setEditName(e.target.value)}/></label><label><span className="fieldLabel">Stage</span><select value={editStage} onChange={e=>setEditStage(e.target.value)}>{["P1-P4","P5","P6","S1","S2","S3","S4"].map(x=><option key={x}>{x}</option>)}</select></label><label className="wideField"><span className="fieldLabel">Description</span><input value={editDescription} onChange={e=>setEditDescription(e.target.value)}/></label><div className="rowActions"><button className="button primary" onClick={()=>void saveBook()}>Save details</button><button className="button secondary" onClick={()=>{setMode("existing");setExistingId(b.id);window.scrollTo({top:0,behavior:"smooth"})}}>Add more terms</button></div></div>}<div className="rowActions"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this word book"/><button className="button secondary" onClick={()=>void openBook(b,query)}>Search</button>{query&&<button className="button ghost" onClick={()=>void openBook(b,"")}>Clear</button>}</div><div className="contentTableWrap"><table className="monitorTable"><thead><tr><th>Term / phrase</th><th>Part of speech</th><th>Definition</th><th>Imported synonyms</th>{b.manageable&&<th>Action</th>}</tr></thead><tbody>{items.map(i=><tr key={i.id}><td><strong>{i.term}</strong></td><td>{i.partOfSpeech||"—"}</td><td>{i.definition||"—"}</td><td>{i.synonyms.length?i.synonyms.join("; "):"—"}</td>{b.manageable&&<td><button className="button ghost smallButton dangerText" onClick={()=>void removeItem(i)}>Remove</button></td>}</tr>)}</tbody></table></div>{itemTotal>items.length&&<div className="tableSub">Showing the first {items.length} matching entries. Narrow the search to inspect a specific term.</div>}</section>})()}
 </>;
}
