"use client";
import { Fragment, useEffect, useMemo, useState } from "react";

type JobStatus = "queued" | "running" | "succeeded" | "failed" | "cancelled";
type Job = {id:string;job_type:string;entity_type?:string|null;entity_id?:string|null;status:JobStatus;stage:string;progress:number;error?:string|null;result_json?:string|null;retry_count:number;max_retries:number;created_at:string;enqueued_at?:string|null;started_at?:string|null;completed_at?:string|null;updated_at:string;queue_position?:number|null};
type QueueResponse={jobs?:Job[];stats?:{queued:number;running:number;succeeded:number;failed:number;timedOut?:number};policy?:{timeoutMinutes:number;scope?:string;updatedAt?:string|null}};
type JobLog={id:string;level:string;event_type:string;stage?:string|null;message:string;details?:unknown;created_at:string};type JobDetail={job?:Job&{request?:unknown;result?:unknown};logs?:JobLog[]};
type Filter="active"|"completed"|"failed"|"all";
function when(value?:string|null){if(!value)return "—";const iso=value.includes("T")?value:`${value.replace(" ","T")}Z`,d=new Date(iso);return Number.isNaN(d.getTime())?value:d.toLocaleString("en-SG",{timeZone:"Asia/Singapore",dateStyle:"medium",timeStyle:"medium"});}
function isTimedOut(j:Job){return j.status==="failed"&&j.stage==="timed_out"}
function label(j:Job){return isTimedOut(j)?"Timed out":j.status==="succeeded"?"Completed":j.status==="queued"?"Queued":j.status==="running"?"Running":j.status==="failed"?"Failed":"Cancelled"}
function statusClass(j:Job){return `queueStatus ${isTimedOut(j)?"failed":j.status}`}
function taskName(jobType:string){return jobType==="vocabulary_import"?"Vocabulary import":jobType}
function importSummary(j:Job){if(j.job_type!=="vocabulary_import"||!j.result_json)return null;try{const r=JSON.parse(j.result_json) as {processed?:number;total?:number;added?:number;updated?:number;skipped?:number;duplicates?:number;failed?:number;wordBook?:string};return `${r.wordBook||"Word book"} · ${r.processed||0}/${r.total||0} processed · +${r.added||0} added · ${r.updated||0} updated · ${r.skipped||0} skipped${r.duplicates?` (${r.duplicates} duplicates)`:""}${r.failed?` · ${r.failed} failed`:""}`;}catch{return null}}
export function WorkQueueManager({apiBase}:{apiBase:string}){
 const[jobs,setJobs]=useState<Job[]>([]),[stats,setStats]=useState({queued:0,running:0,succeeded:0,failed:0,timedOut:0}),[msg,setMsg]=useState(""),[filter,setFilter]=useState<Filter>("active"),[loading,setLoading]=useState(true),[openId,setOpenId]=useState<string|null>(null),[details,setDetails]=useState<Record<string,JobDetail>>({}),[timeout,setTimeoutMinutes]=useState(120),[savingTimeout,setSavingTimeout]=useState(false);
 async function load(){const r=await fetch(apiBase,{cache:"no-store"}),b=await r.json().catch(()=>({})) as QueueResponse;if(r.ok){setJobs(b.jobs||[]);setStats({queued:b.stats?.queued||0,running:b.stats?.running||0,succeeded:b.stats?.succeeded||0,failed:b.stats?.failed||0,timedOut:b.stats?.timedOut||0});if(b.policy?.timeoutMinutes)setTimeoutMinutes(b.policy.timeoutMinutes)}setLoading(false);}
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(),3000);return()=>window.clearInterval(t)},[apiBase]);
 async function saveTimeout(){setSavingTimeout(true);const r=await fetch(apiBase,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({taskTimeoutMinutes:timeout})}),b=await r.json().catch(()=>({})) as {error?:string;policy?:{timeoutMinutes:number}};setSavingTimeout(false);if(!r.ok){setMsg(b.error||"Could not save queue timeout.");return}if(b.policy)setTimeoutMinutes(b.policy.timeoutMinutes);setMsg(`Task timeout saved: ${b.policy?.timeoutMinutes||timeout} minutes.`);}
 async function remove(j:Job){if(j.status!=="succeeded"&&j.status!=="failed")return;if(!confirm(`Delete this ${label(j).toLowerCase()} task from Work Queue history? Generated learning content is kept.`))return;const r=await fetch(`${apiBase}/${encodeURIComponent(j.id)}`,{method:"DELETE"}),b=await r.json().catch(()=>({})) as {error?:string};setMsg(r.ok?"Task history deleted.":b.error||"Delete failed.");await load();}
 async function retry(j:Job){if(j.status!=="failed")return;const timedOut=isTimedOut(j),r=await fetch(`${apiBase}/${encodeURIComponent(j.id)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(timedOut?{action:"retrigger"}:{action:"retry"})}),b=await r.json().catch(()=>({})) as {error?:string;id?:string};setMsg(r.ok?(timedOut?`Timed-out task retriggered as ${b.id||"a new task"}. Original audit history was kept.`:"Task re-entered the end of the FIFO queue."):b.error||"Retry failed.");await load();}
 async function toggleDetails(j:Job){if(openId===j.id){setOpenId(null);return}setOpenId(j.id);const r=await fetch(`${apiBase}/${encodeURIComponent(j.id)}`,{cache:"no-store"}),b=await r.json().catch(()=>({})) as JobDetail;if(r.ok)setDetails(v=>({...v,[j.id]:b}));}
 function pretty(v:unknown){try{return JSON.stringify(v,null,2)}catch{return String(v)}}
 const shown=useMemo(()=>jobs.filter(j=>filter==="all"||filter==="active"&&(j.status==="queued"||j.status==="running")||filter==="completed"&&j.status==="succeeded"||filter==="failed"&&j.status==="failed"),[jobs,filter]);
 return <>
  <section className="card"><div className="cardHeader"><div><h2>Queue runtime policy</h2><p>Running tasks that exceed this limit are marked Timed out. Default: 120 minutes.</p></div><span>5–1440 min</span></div><div className="rowActions"><label><span className="fieldLabel">Task timeout (minutes)</span><input type="number" min={5} max={1440} value={timeout} onChange={e=>setTimeoutMinutes(Math.max(5,Math.min(1440,Number(e.target.value)||120)))}/></label><button className="button primary" disabled={savingTimeout} onClick={()=>void saveTimeout()}>{savingTimeout?"Saving…":"Save timeout"}</button></div></section>
  <div className="queueStats"><button className={filter==="active"?"queueStat active":"queueStat"} onClick={()=>setFilter("active")}><span>Active</span><strong>{stats.running+stats.queued}</strong><small>{stats.running} running · {stats.queued} queued</small></button><button className={filter==="completed"?"queueStat active":"queueStat"} onClick={()=>setFilter("completed")}><span>Completed</span><strong>{stats.succeeded}</strong><small>finished successfully</small></button><button className={filter==="failed"?"queueStat active":"queueStat"} onClick={()=>setFilter("failed")}><span>Failed / timeout</span><strong>{stats.failed}</strong><small>{stats.timedOut} timed out · can retry/delete</small></button><button className={filter==="all"?"queueStat active":"queueStat"} onClick={()=>setFilter("all")}><span>Visible history</span><strong>{jobs.length}</strong><small>latest 200 tasks</small></button></div>
  <section className="card workQueueCard"><div className="cardHeader"><div><h2>Work Queue</h2><p className="queueHelp">FIFO by queue-entry time. One job runs at a time; ordinary retries re-enter at the end. Timed-out tasks are retriggered as a new audited job.</p></div><span>{msg||"Auto-refresh · 3s"}</span></div>
  {loading?<div className="emptyState">Loading work queue…</div>:!shown.length?<div className="emptyState">No tasks in this view.</div>:<div className="contentTableWrap"><table className="monitorTable workQueueTable"><thead><tr><th>Task</th><th>Status / order</th><th>Queue time</th><th>Run time</th><th>Action</th></tr></thead><tbody>{shown.map(j=><Fragment key={j.id}><tr><td><strong>{taskName(j.job_type)}</strong>{importSummary(j)&&<div className="tableSub">{importSummary(j)}</div>}<div className="tableSub">{j.entity_type||"task"}{j.entity_id?` · ${j.entity_id}`:""}</div>{j.error&&<div className="queueError">{j.error}</div>}</td><td><span className={statusClass(j)}>{label(j)}</span>{j.status==="queued"&&<div className="tableSub"><strong>#{j.queue_position||"—"}</strong> in global FIFO queue</div>}<div className="tableSub">{j.stage} · {j.progress}%{j.retry_count?` · retry ${j.retry_count}/${j.max_retries}`:""}</div></td><td><div>{when(j.enqueued_at||j.created_at)}</div>{j.enqueued_at&&j.enqueued_at!==j.created_at&&<div className="tableSub">Created {when(j.created_at)}</div>}</td><td>{j.status==="running"?<><div>Started {when(j.started_at)}</div><div className="queueProgress"><span style={{width:`${Math.max(0,Math.min(100,j.progress))}%`}}/></div></>:j.status==="succeeded"||j.status==="failed"?<div>Finished {when(j.completed_at)}</div>:<span className="tableSub">Waiting</span>}</td><td><div className="rowActions"><button className="button ghost smallButton" onClick={()=>void toggleDetails(j)}>{openId===j.id?"Hide logs":"Details / Logs"}</button>{j.status==="failed"&&(isTimedOut(j)||j.retry_count<j.max_retries)&&<button className="button secondary smallButton" onClick={()=>void retry(j)}>{isTimedOut(j)?"Retrigger":"Retry"}</button>}{(j.status==="succeeded"||j.status==="failed")&&<button className="button ghost smallButton" onClick={()=>void remove(j)}>Delete</button>}</div></td></tr>{openId===j.id&&<tr className="jobLogRow"><td colSpan={5}><div className="jobLogPanel"><div className="jobLogHeader"><strong>Task diagnostic log</strong><span>Secrets are redacted · timestamps SGT</span></div>{!details[j.id]?<div className="emptyState">Loading logs…</div>:<><details><summary>Job request</summary><pre>{pretty(details[j.id].job?.request)}</pre></details>{details[j.id].job?.result!==undefined&&details[j.id].job?.result!==null&&<details><summary>Job result</summary><pre>{pretty(details[j.id].job?.result)}</pre></details>}<div className="jobTimeline">{(details[j.id].logs||[]).map(log=><div className={`jobLogEvent ${log.level}`} key={log.id}><div><strong>{log.event_type}</strong><span>{when(log.created_at)}{log.stage?` · ${log.stage}`:""}</span></div><p>{log.message}</p>{log.details!==undefined&&log.details!==null&&<pre>{pretty(log.details)}</pre>}</div>)}</div></>}</div></td></tr>}</Fragment>)}</tbody></table></div>}
  <div className="notice queuePolicy"><strong>Queue policy:</strong> Running tasks are checked against the configured timeout by the queue worker watchdog every 5 minutes. Timed-out/Completed/Failed history can be deleted. Retrigger keeps the timed-out record and creates a fresh FIFO job.</div></section>
 </>;
}
