import {getEnv} from "@/lib/cloudflare";
import {ensureLearnerSession,learnerCookie} from "@/lib/student/session";
import {isScienceGrade,isScienceTheme,safeJson} from "@/lib/science/catalog";
export async function GET(request:Request){const env=getEnv(),session=await ensureLearnerSession(request,env.DB),u=new URL(request.url);const grade=isScienceGrade(u.searchParams.get("grade"))?u.searchParams.get("grade")!:null,theme=isScienceTheme(u.searchParams.get("theme"))?u.searchParams.get("theme")!:null,topicId=(u.searchParams.get("topic")||"").trim()||null;
 const clauses=["t.status='published'"];const binds:unknown[]=[];if(grade){clauses.push("t.grade=?");binds.push(grade)}if(theme){clauses.push("t.theme=?");binds.push(theme)}
 const topics=await env.DB.prepare(`SELECT t.id,t.grade,t.theme,t.title,t.summary,t.learning_points_json,COUNT(DISTINCT v.id) vocabulary_count,COUNT(DISTINCT q.id) question_count,COALESCE((SELECT AVG(p.mastery) FROM science_vocabulary sv LEFT JOIN science_vocabulary_progress p ON p.vocabulary_id=sv.id AND p.child_id=? WHERE sv.topic_id=t.id),0) vocab_mastery,COALESCE((SELECT COUNT(DISTINCT a.question_id)*100.0/NULLIF(COUNT(DISTINCT sq.id),0) FROM science_questions sq LEFT JOIN science_question_attempts a ON a.question_id=sq.id AND a.child_id=? AND a.correct=1 WHERE sq.topic_id=t.id AND sq.status='published'),0) question_coverage FROM science_topics t LEFT JOIN science_vocabulary v ON v.topic_id=t.id LEFT JOIN science_questions q ON q.topic_id=t.id AND q.status='published' WHERE ${clauses.join(" AND ")} GROUP BY t.id ORDER BY CASE t.grade WHEN 'P3' THEN 1 WHEN 'P4' THEN 2 WHEN 'P5' THEN 3 ELSE 4 END,t.sort_order`).bind(session.childId,session.childId,...binds).all<{id:string;grade:string;theme:string;title:string;summary:string;learning_points_json:string;vocabulary_count:number;question_count:number;vocab_mastery:number;question_coverage:number}>();
 const mapped=topics.results.map(t=>({...t,learningPoints:safeJson<string[]>(t.learning_points_json,[]),completionPercent:Math.round((Number(t.vocab_mastery||0)+Number(t.question_coverage||0))/2)}));let detail:null|Record<string,unknown>=null;
 if(topicId){const topic=mapped.find(t=>t.id===topicId);if(topic){const vocab=await env.DB.prepare("SELECT v.id,v.term,v.definition,v.example,COALESCE(p.mastery,0) mastery,COALESCE(p.attempts,0) attempts FROM science_vocabulary v LEFT JOIN science_vocabulary_progress p ON p.vocabulary_id=v.id AND p.child_id=? WHERE v.topic_id=? ORDER BY v.sort_order,v.term").bind(session.childId,topicId).all();const questions=await env.DB.prepare("SELECT id,question_type,prompt,options_json,explanation,difficulty FROM science_questions WHERE topic_id=? AND status='published' ORDER BY sort_order,id").bind(topicId).all<{id:string;question_type:string;prompt:string;options_json:string|null;explanation:string;difficulty:number}>();detail={...topic,vocabulary:vocab.results,questions:questions.results.map(q=>({...q,options:safeJson<string[]>(q.options_json,[])}))};}}
 const response=Response.json({grades:["P3","P4","P5","P6"],themes:["Diversity","Cycles","Systems","Interactions","Energy"],topics:mapped,detail});if(session.isNew)response.headers.set("Set-Cookie",learnerCookie(session.sessionId));return response;}
