"use client";
import { type ReactNode, useRef, useState } from "react";
import type { VocabularyDetail } from "@/lib/vocabulary/types";
import { VocabularyDetailCard } from "@/components/vocabulary/vocabulary-detail-card";
import { CustomWordbookPicker } from "@/components/vocabulary/custom-wordbook-picker";

type SelectionData={term:string;context:string;left:number;top:number};
function cleanSelection(text:string){return text.trim().replace(/\s+/g," ").replace(/^[\s“”'‘’.,;:!?()[\]{}-]+|[\s“”'‘’.,;:!?()[\]{}-]+$/g,"").slice(0,90)}
function contextFromSelection(sel:Selection){const node=sel.anchorNode;const element=node?.nodeType===Node.ELEMENT_NODE?node as Element:node?.parentElement;const holder=element?.closest("p,li,blockquote,.selectableText")||element;return (holder?.textContent||"").trim().replace(/\s+/g," ").slice(0,700)}

export function SelectionVocabulary({children,contentId,schoolLevel="P6",className=""}:{children:ReactNode;contentId?:string;schoolLevel?:string;className?:string}){
 const ref=useRef<HTMLDivElement|null>(null);const[selection,setSelection]=useState<SelectionData|null>(null);const[detail,setDetail]=useState<VocabularyDetail|null>(null);const[loading,setLoading]=useState(false);const[saved,setSaved]=useState(false);const[collectionId,setCollectionId]=useState("");const[error,setError]=useState("");
 function capture(){setTimeout(()=>{const sel=window.getSelection();if(!sel||sel.isCollapsed||!sel.rangeCount||!ref.current)return;const range=sel.getRangeAt(0);if(!ref.current.contains(range.commonAncestorContainer))return;const term=cleanSelection(sel.toString());const words=term.split(/\s+/).filter(Boolean);if(!term)return;if(words.length>12||term.length>90){setError("Select a word or phrase of up to 12 words.");return;}const rect=range.getBoundingClientRect();setSelection({term,context:contextFromSelection(sel),left:Math.max(12,Math.min(window.innerWidth-220,rect.left+rect.width/2-90)),top:Math.max(68,rect.top-54)});setDetail(null);setSaved(false);setCollectionId("");setError("")},10)}
 async function explain(){if(!selection)return;setLoading(true);setError("");try{const r=await fetch("/api/student/vocabulary/enrich",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({term:selection.term,context:selection.context,schoolLevel})});const b=await r.json() as {detail?:VocabularyDetail;error?:string};if(!r.ok||!b.detail)throw new Error(b.error||"Could not explain selection");setDetail(b.detail)}catch(e){setError(e instanceof Error?e.message:"Could not explain selection")}finally{setLoading(false)}}
 async function save(){if(!detail||!selection)return;setLoading(true);setError("");try{const r=await fetch("/api/student/vocabulary",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({term:detail.term,detail,sourceContentId:contentId||null,sourceSentence:selection.context,collectionId:collectionId||null})});const b=await r.json() as {ok?:boolean;error?:string};if(!r.ok)throw new Error(b.error||"Could not save vocabulary");setSaved(true)}catch(e){setError(e instanceof Error?e.message:"Could not save vocabulary")}finally{setLoading(false)}}
 function close(){setSelection(null);setDetail(null);setSaved(false);setCollectionId("");setError("");window.getSelection()?.removeAllRanges()}
 return <><div ref={ref} className={className} onMouseUp={capture} onTouchEnd={capture}>{children}</div>{selection&&!detail?<div className="selectionPopover" style={{left:selection.left,top:selection.top}}><strong>{selection.term}</strong><button onClick={explain} disabled={loading}>{loading?"Explaining…":"Explain & save"}</button><button className="iconClose" onClick={close}>×</button></div>:null}{selection&&detail?<div className="vocabDrawerBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="vocabDrawer"><button className="drawerClose" onClick={close}>×</button><VocabularyDetailCard detail={detail}/>{!saved?<CustomWordbookPicker value={collectionId} onChange={setCollectionId} disabled={loading}/>:<div className="notice successNotice">Saved to My vocabulary{collectionId?" and the selected custom word book":""}.</div>}{error&&<div className="notice warnNotice">{error}</div>}<div className="drawerActions"><button className="button primary" onClick={save} disabled={loading||saved}>{saved?"Saved ✓":loading?"Saving…":collectionId?"Add to word book":"Add to my vocabulary"}</button><a className="button secondary" href="/vocabulary">Open vocabulary</a></div></div></div>:null}{selection&&!detail&&error?<div className="selectionError">{error}</div>:null}</>;
}
