"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { PronounceButton } from "@/components/vocabulary/pronounce-button";
import type { PronunciationResult, VocabularyDetail } from "@/lib/vocabulary/types";
import {getSpeechRecognitionCtor, type SpeechRecognitionLike} from "@/lib/browser/speech-recognition";

type Collection={id:string;name:string;code:string|null;itemCount:number;masteredCount:number;completionPercent:number;averageMastery:number;active:boolean;dailyTarget:number;cefrLevel:string|null};
type Item={id:string;detail:VocabularyDetail;mastery:number;pronunciationScore:number;recognitionScore:number;listeningScore:number;spellingScore:number;usageScore:number};
type Mode="pronounce"|"dictation"|"meaning"|"cloze";
type DailyGroup="new"|"review";

const modes:Mode[]=["pronounce","dictation","meaning","cloze"];
const labels:Record<Mode,string>={pronounce:"Chinese meaning · listen & read aloud",dictation:"Listen & spell",meaning:"Choose the English definition",cloze:"Complete the sentence"};

function encodeWav(samples:Float32Array,sampleRate:number){
 const buffer=new ArrayBuffer(44+samples.length*2),view=new DataView(buffer);const write=(o:number,s:string)=>{for(let i=0;i<s.length;i++)view.setUint8(o+i,s.charCodeAt(i));};
 write(0,"RIFF");view.setUint32(4,36+samples.length*2,true);write(8,"WAVE");write(12,"fmt ");view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);write(36,"data");view.setUint32(40,samples.length*2,true);
 for(let i=0;i<samples.length;i++){const s=Math.max(-1,Math.min(1,samples[i]));view.setInt16(44+i*2,s<0?s*0x8000:s*0x7fff,true);}return new Blob([buffer],{type:"audio/wav"});
}
function downsample(chunks:Float32Array[],sourceRate:number,targetRate=16000){
 const total=chunks.reduce((n,x)=>n+x.length,0),input=new Float32Array(total);let off=0;for(const c of chunks){input.set(c,off);off+=c.length;}if(sourceRate===targetRate)return input;
 const ratio=sourceRate/targetRate,len=Math.max(1,Math.round(input.length/ratio)),out=new Float32Array(len);for(let i=0;i<len;i++){const start=Math.floor(i*ratio),end=Math.min(input.length,Math.floor((i+1)*ratio));let sum=0,count=0;for(let j=start;j<end;j++){sum+=input[j];count++;}out[i]=count?sum/count:0;}return out;
}

export function VocabularyDailyTrainer({practiceMode=false}:{practiceMode?:boolean}){
 const[collections,setCollections]=useState<Collection[]>([]),[collectionId,setCollectionId]=useState(""),[target,setTarget]=useState(10),[newTarget,setNewTarget]=useState(10),[reviewTarget,setReviewTarget]=useState(10),[spellingRepetitions,setSpellingRepetitions]=useState(3),[group,setGroup]=useState<DailyGroup>("new"),[dictationRound,setDictationRound]=useState(1),[policyLocked,setPolicyLocked]=useState(false),[items,setItems]=useState<Item[]>([]),[i,setI]=useState(0),[phase,setPhase]=useState(0),[answer,setAnswer]=useState(""),[feedback,setFeedback]=useState<{correct:boolean;message:string}|null>(null),[wrong,setWrong]=useState(0),[score,setScore]=useState(0),[started,setStarted]=useState(false),[complete,setComplete]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[heard,setHeard]=useState(""),[pronBusy,setPronBusy]=useState(false),[pronError,setPronError]=useState(""),[pronResult,setPronResult]=useState<PronunciationResult|null>(null);
 const streamRef=useRef<MediaStream|null>(null),ctxRef=useRef<AudioContext|null>(null),processorRef=useRef<ScriptProcessorNode|null>(null),sourceRef=useRef<MediaStreamAudioSourceNode|null>(null),chunksRef=useRef<Float32Array[]>([]),recognitionRef=useRef<SpeechRecognitionLike|null>(null),timerRef=useRef<ReturnType<typeof setInterval>|null>(null),startRef=useRef(0),rateRef=useRef(48000),heardRef=useRef("");

 async function loadSettings(){const r=await fetch(`/api/student/vocabulary/training/settings${practiceMode?"?practice=1":""}`),b=await r.json() as {activeCollectionId?:string|null;dailyTarget?:number;newTarget?:number;reviewTarget?:number;spellingRepetitions?:number;collections?:Collection[];policyLocked?:boolean};const cs=b.collections||[];setCollections(cs);setCollectionId(b.activeCollectionId||cs[0]?.id||"");setTarget(b.dailyTarget||10);setNewTarget(b.newTarget||b.dailyTarget||10);setReviewTarget(Math.max(0,b.reviewTarget??10));setSpellingRepetitions(Math.max(1,b.spellingRepetitions||3));setPolicyLocked(Boolean(b.policyLocked))}
 useEffect(()=>{void loadSettings()},[]);
 const collection=collections.find(c=>c.id===collectionId)||null,item=items[i],mode=modes[phase];
 const definition=item?.detail.meanings?.[0]?.simple||item?.detail.meanings?.[0]?.definition||"";
 const chineseMeaning=item?.detail.meanings?.[0]?.chinese||item?.detail.meanings?.find(m=>/[\u3400-\u9fff]/.test(m.simple||""))?.simple||item?.detail.meanings?.find(m=>/[\u3400-\u9fff]/.test(m.contextMeaning||""))?.contextMeaning||"中文释义待词库补全";
 const example=item?.detail.examples?.[0]?.sentence||"";
 const cloze=useMemo(()=>{if(!item)return"";const term=item.detail.term.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return example&&new RegExp(term,"i").test(example)?example.replace(new RegExp(term,"i"),"________"):definition},[item,example,definition]);
 const options=useMemo(()=>{if(!item)return[];const correct=definition,others=items.filter(x=>x.id!==item.id).map(x=>x.detail.meanings?.[0]?.simple||x.detail.meanings?.[0]?.definition||"").filter(x=>x&&x!==correct);const opts=[correct,...others.slice((i*3)%Math.max(1,others.length),((i*3)%Math.max(1,others.length))+3)];while(opts.length<4&&others.length)opts.push(others[opts.length%others.length]);const unique=[...new Set(opts)].slice(0,4);return unique.sort((a,b)=>((a.length+i)%7)-((b.length+i)%7))},[item,items,definition,i]);


 function speak(text:string){if(typeof window==="undefined"||!text||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-GB";u.rate=.9;window.speechSynthesis.speak(u);}
 useEffect(()=>{if(!started||!item)return;if(mode==="pronounce"||mode==="meaning")speak(item.detail.term)},[started,item?.id,mode]);

 function stopCaptureOnly(){
  if(timerRef.current)clearInterval(timerRef.current);timerRef.current=null;try{recognitionRef.current?.stop();}catch{}recognitionRef.current=null;
  processorRef.current?.disconnect();sourceRef.current?.disconnect();streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;
  const ctx=ctxRef.current;if(ctx)void ctx.close().catch(()=>{});ctxRef.current=null;processorRef.current=null;sourceRef.current=null;setRecording(false);
 }
 useEffect(()=>()=>stopCaptureOnly(),[]);
 useEffect(()=>{if(mode!=="pronounce"||!item){stopCaptureOnly();setHeard("");heardRef.current="";setPronError("");setPronResult(null)}},[mode,item?.id]);

 async function saveSettings(id=collectionId){if(!id||policyLocked)return;await fetch("/api/student/vocabulary/training/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({collectionId:id})});await loadSettings()}
 async function start(selectedGroup:DailyGroup=group){if(!collectionId)return;setGroup(selectedGroup);setBusy(true);setError("");if(!practiceMode&&!policyLocked)await saveSettings(collectionId);const selectedTarget=practiceMode?target:(selectedGroup==="new"?newTarget:reviewTarget);const r=await fetch(`/api/student/vocabulary/training?collection=${encodeURIComponent(collectionId)}&count=${selectedTarget}&group=${selectedGroup}${practiceMode?"&practice=1":""}`),b=await r.json() as {items?:Item[];error?:string;collection?:Collection|null;dailyTarget?:number;spellingRepetitions?:number};setBusy(false);if(!r.ok){setError(b.error||"Could not start vocabulary practice");return}if(b.collection?.id)setCollectionId(b.collection.id);if(b.dailyTarget)setTarget(b.dailyTarget);const loaded=b.items||[];setItems(loaded);setI(0);setPhase(0);setDictationRound(1);setAnswer("");setFeedback(null);setWrong(0);setScore(0);if(!loaded.length&&!practiceMode){await fetch("/api/student/vocabulary/training/complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({collectionId,group:selectedGroup})});setComplete(true);setStarted(false);return}setComplete(false);setStarted(true)}
 function norm(s:string){return s.toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9'\s-]/g,"").replace(/\s+/g," ").trim()}
 async function record(correct:boolean,response=""){if(!item)return;await fetch("/api/student/vocabulary/training",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({collectionId,vocabularyId:item.id,mode,correct,response})});if(correct)setScore(x=>x+1)}
 async function submit(value=answer){if(!item||feedback||mode==="pronounce")return;let correct=false;if(mode==="meaning")correct=value===definition;else correct=norm(value)===norm(item.detail.term);await record(correct,value);if(correct){setFeedback({correct:true,message:"Correct — retrieve it once more in the next mode."});setWrong(0)}else{setWrong(x=>x+1);setFeedback({correct:false,message:`Answer: ${item.detail.term}. Read it, listen again, then retrieve it from memory.`})}}

 async function startPronunciation(){
  if(!item||pronBusy||recording)return;setPronError("");setPronResult(null);setFeedback(null);setHeard("");heardRef.current="";chunksRef.current=[];
  try{
   if(!navigator.mediaDevices?.getUserMedia)throw new Error("Microphone recording is not supported in this browser.");
   const stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true}});streamRef.current=stream;
   const ctx=new AudioContext();ctxRef.current=ctx;rateRef.current=ctx.sampleRate;const source=ctx.createMediaStreamSource(stream),processor=ctx.createScriptProcessor(4096,1,1);sourceRef.current=source;processorRef.current=processor;processor.onaudioprocess=e=>chunksRef.current.push(new Float32Array(e.inputBuffer.getChannelData(0)));source.connect(processor);processor.connect(ctx.destination);
   const Ctor=getSpeechRecognitionCtor();if(Ctor){const rec=new Ctor();rec.lang="en-SG";rec.interimResults=true;rec.continuous=true;rec.onresult=e=>{let final="",temp="";for(let n=0;n<e.results.length;n++){const t=e.results[n][0]?.transcript||"";if(e.results[n].isFinal)final+=`${t} `;else temp+=t;}const all=`${final} ${temp}`.trim();heardRef.current=all;setHeard(all);};rec.onerror=()=>{};try{rec.start();recognitionRef.current=rec}catch{}}
   startRef.current=Date.now();setSeconds(0);timerRef.current=setInterval(()=>setSeconds(Math.max(1,Math.round((Date.now()-startRef.current)/1000))),500);setRecording(true);
  }catch(e){stopCaptureOnly();setPronError(e instanceof Error?e.message:"Could not start microphone");}
 }
 async function stopAndMatch(){
  if(!recording||!item)return;setRecording(false);if(timerRef.current)clearInterval(timerRef.current);timerRef.current=null;try{recognitionRef.current?.stop();}catch{}await new Promise(resolve=>setTimeout(resolve,180));recognitionRef.current=null;processorRef.current?.disconnect();sourceRef.current?.disconnect();
  const samples=downsample(chunksRef.current,rateRef.current,16000),wav=encodeWav(samples,16000),ctx=ctxRef.current;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(ctx)await ctx.close().catch(()=>{});ctxRef.current=null;processorRef.current=null;sourceRef.current=null;
  if(wav.size<=44){setPronError("No usable speech was recorded. Please try again.");return}
  setPronBusy(true);setPronError("");try{
   const form=new FormData();form.append("audio",wav,"vocabulary-pronunciation.wav");form.append("browserTranscript",heardRef.current);form.append("durationMs",String(Math.max(1000,Date.now()-startRef.current)));form.append("collectionId",collectionId);form.append("vocabularyId",item.id);
   const r=await fetch("/api/student/vocabulary/training/pronunciation",{method:"POST",body:form});const body=await r.json() as PronunciationResult&{error?:string};if(!r.ok)throw new Error(body.error||"Pronunciation match failed");
   setPronResult(body);setHeard(body.transcript||heardRef.current);heardRef.current=body.transcript||heardRef.current;
   if(body.progress)setItems(current=>current.map(x=>x.id===item.id?{...x,mastery:Number(body.progress?.mastery ?? x.mastery),pronunciationScore:Number(body.progress?.pronunciation_score ?? x.pronunciationScore)}:x));
   if(body.passed){setScore(x=>x+1);setWrong(0);setFeedback({correct:true,message:`Matched ${body.matchScore}%. Pronunciation ${Math.round(body.assessment.pronunciation)}%. You can continue.`})}
   else{setWrong(x=>x+1);setFeedback({correct:false,message:`Match ${body.matchScore}% · pronunciation ${Math.round(body.assessment.pronunciation)}%. Say “${item.detail.term}” again before continuing.`})}
  }catch(e){setPronError(e instanceof Error?e.message:"Pronunciation match failed");}finally{setPronBusy(false)}
 }
 async function next(){
  if(!feedback||!item)return;
  if(!feedback.correct){setFeedback(null);setAnswer("");setPronResult(null);setHeard("");heardRef.current="";if(mode==="pronounce")return;if(wrong<2)return;}
  if(mode==="dictation"&&feedback.correct&&dictationRound<spellingRepetitions){setDictationRound(r=>r+1);setFeedback(null);setAnswer("");setWrong(0);speak(item.detail.term);return;}
  setFeedback(null);setAnswer("");setWrong(0);setPronResult(null);setHeard("");heardRef.current="";setDictationRound(1);
  if(phase<modes.length-1){setPhase(p=>p+1);return}if(i<items.length-1){setI(x=>x+1);setPhase(0);return}setComplete(true);setStarted(false);if(!practiceMode)await fetch("/api/student/vocabulary/training/complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({collectionId,group})});await loadSettings();
 }

 if(!started&&!complete)return <div className="vocabDailySetup"><section className="card dailyVocabHero"><span className="eyebrow">Daily vocabulary</span><h2>New learning + scheduled review</h2><p>Both groups use the same four-stage mastery flow: Chinese meaning + automatic pronunciation/read-aloud → repeated dictation → English-definition choice → cloze.</p><div className="dailyBookControls"><label>Word book<select value={collectionId} disabled={policyLocked} onChange={e=>setCollectionId(e.target.value)}>{collections.map(c=><option value={c.id} key={c.id}>{c.name} · {c.completionPercent}%</option>)}</select></label>{policyLocked&&<div className="sourceHint"><strong>Assigned by Tenant Admin</strong> · Students cannot change the word book.</div>}{!practiceMode&&<div className="dailyVocabularyGroups"><button className="button primary" disabled={busy||!collectionId||!collection?.itemCount} onClick={()=>void start("new")}>{busy&&group==="new"?"Preparing…":`New learning · ${newTarget}`}</button><button className="button secondary" disabled={busy||!collectionId||reviewTarget===0} onClick={()=>void start("review")}>{busy&&group==="review"?"Preparing…":`Review · ${reviewTarget}`}</button><div className="sourceHint">Dictation repeats <strong>{spellingRepetitions}×</strong> per word. Review words are scheduled by Review window / Required reviews.</div></div>}{practiceMode&&<button className="button primary" disabled={busy||!collectionId||!collection?.itemCount} onClick={()=>void start("new")}>{busy?"Preparing…":"Start vocabulary practice"}</button>}</div>{error&&<div className="notice warnNotice">{error}</div>}</section></div>;
 if(complete)return <section className="card resultHero"><span className="eyebrow">Vocabulary session complete</span><h1>{items.length} words</h1><p>You completed the {group==="new"?"new-learning":"review"} group for {items.length} words. Correct retrievals: {score}. Your word-book mastery percentage has been updated.</p><div className="rowActions" style={{justifyContent:"center"}}><button className="button primary" onClick={()=>{setComplete(false);void start(group)}}>Practise another set</button><a className="button secondary" href="/learn">Back to Learn</a></div></section>;
 if(!item)return <div className="emptyState">This word book has no words yet.</div>;
 return <div className="dailyTrainer"><div className="sessionTop"><div><span className="eyebrow">{collection?.name}</span><h1>{labels[mode]}</h1></div><div><div className="progressBar"><span style={{width:`${((i*modes.length+phase)/(Math.max(1,items.length*modes.length)))*100}%`}}/></div><small>{i+1}/{items.length} words · step {phase+1}/4</small></div></div><article className="card retrievalCard"><div className="retrievalMeta"><span>{item.detail.entryType}</span><strong>{Math.round(item.mastery)}% mastered</strong></div>
  {mode==="pronounce"&&<><div className="definitionPrompt" style={{fontSize:"1.45rem",fontWeight:800}}>{chineseMeaning}</div><div className="retrievalWord">{item.detail.term}</div>{item.detail.phonetic&&<div className="phoneticBig">{item.detail.phonetic}</div>}<PronounceButton text={item.detail.term}/><p className="retrievalHint">The word is read automatically when this step opens. Read the Chinese meaning, listen, then repeat the target word or phrase. The recording must match the target before this step can be completed.</p><div className="vocabPronunciationControls"><button className={`recordBig ${recording?"recording":""}`} disabled={pronBusy||Boolean(feedback?.correct)} onClick={recording?()=>void stopAndMatch():()=>void startPronunciation()}>{recording?"■ Stop & check":"● Record pronunciation"}</button><span>{recording?`${seconds}s · recording`:pronBusy?"Matching your speech…":"Microphone required"}</span></div>{heard&&<div className="vocabHeard"><span>We heard</span><strong>{heard}</strong></div>}{pronResult&&<div className="vocabPronScores"><span>Match <b>{pronResult.matchScore}%</b></span><span>Pronunciation <b>{Math.round(pronResult.assessment.pronunciation)}%</b></span><span>Accuracy <b>{Math.round(pronResult.assessment.accuracy)}%</b></span><span>Completeness <b>{Math.round(pronResult.assessment.completeness)}%</b></span></div>}{pronError&&<div className="notice errorNotice retrievalFeedback">{pronError}</div>}</>}
  {mode==="meaning"&&<><div className="retrievalWord">{item.detail.term}</div><PronounceButton text={item.detail.term} compact/><p className="retrievalHint">The word is read automatically when this step opens. Choose the correct English definition.</p><div className="choiceGrid">{options.map(o=><button disabled={Boolean(feedback)} key={o} onClick={()=>void submit(o)}>{o}</button>)}</div></>}
  {mode==="dictation"&&<><div className="audioOnlyPrompt"><PronounceButton text={item.detail.term}/><strong>Listen. Type exactly what you hear. · {dictationRound}/{spellingRepetitions}</strong></div><input className="retrievalInput" autoFocus value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&answer.trim())void submit()}} placeholder="Type the word or phrase…"/><button className="button primary" disabled={!answer.trim()||Boolean(feedback)} onClick={()=>void submit()}>Check spelling</button></>}
  {mode==="cloze"&&<><p className="clozePrompt">{cloze}</p><input className="retrievalInput" autoFocus value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&answer.trim())void submit()}} placeholder="Complete the missing word or phrase…"/><button className="button primary" disabled={!answer.trim()||Boolean(feedback)} onClick={()=>void submit()}>Check in context</button></>}
  {feedback&&<div className={feedback.correct?"notice successNotice retrievalFeedback":"notice warnNotice retrievalFeedback"}><strong>{feedback.correct?"Retrieved":"Repeat this item"}</strong><p>{feedback.message}</p>{!feedback.correct&&<PronounceButton text={item.detail.term}/>}<button className="button primary smallButton" onClick={()=>void next()}>{feedback.correct?"Next step":mode==="pronounce"?"Record again":wrong>=2?"Review & continue":"Try again"}</button></div>}
 </article><div className="trainingDimensions"><span>Pronunciation {Math.round(item.pronunciationScore)}%</span><span>Meaning {Math.round(item.recognitionScore)}%</span><span>Listening {Math.round(item.listeningScore)}%</span><span>Spelling {Math.round(item.spellingScore)}%</span><span>Usage {Math.round(item.usageScore)}%</span></div></div>;
}
