"use client";
import { useState } from "react";
import type { VocabularyDetail } from "@/lib/vocabulary/types";
import { VocabularyDetailCard } from "@/components/vocabulary/vocabulary-detail-card";
import { CustomWordbookPicker } from "@/components/vocabulary/custom-wordbook-picker";

export function VocabularyAddButton({term,context="",contentId,schoolLevel="P6"}:{term:string;context?:string;contentId?:string;schoolLevel?:string}){
 const[detail,setDetail]=useState<VocabularyDetail|null>(null);const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[saved,setSaved]=useState(false);const[collectionId,setCollectionId]=useState("");const[error,setError]=useState("");
 async function start(){setOpen(true);setBusy(true);setSaved(false);setCollectionId("");setError("");try{const r=await fetch("/api/student/vocabulary/enrich",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({term,context,schoolLevel})});const b=await r.json() as {detail?:VocabularyDetail;error?:string};if(!r.ok||!b.detail)throw new Error(b.error||"Could not explain vocabulary");setDetail(b.detail)}catch(e){setError(e instanceof Error?e.message:"Could not explain vocabulary")}finally{setBusy(false)}}
 async function save(){if(!detail)return;setBusy(true);setError("");try{const r=await fetch("/api/student/vocabulary",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({term,detail,sourceContentId:contentId||null,sourceSentence:context,collectionId:collectionId||null})});const b=await r.json() as {error?:string};if(!r.ok)throw new Error(b.error||"Could not save vocabulary");setSaved(true)}catch(e){setError(e instanceof Error?e.message:"Could not save vocabulary")}finally{setBusy(false)}}
 return <><button className="miniVocabButton" type="button" onClick={start}>＋ Vocabulary</button>{open?<div className="vocabDrawerBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="vocabDrawer"><button className="drawerClose" onClick={()=>setOpen(false)}>×</button>{busy&&!detail?<div className="emptyState">Building a detailed vocabulary card…</div>:detail?<VocabularyDetailCard detail={detail}/>:null}{detail&&!saved?<CustomWordbookPicker value={collectionId} onChange={setCollectionId} disabled={busy}/>:null}{saved&&<div className="notice successNotice">Saved to My vocabulary{collectionId?" and the selected custom word book":""}.</div>}{error&&<div className="notice warnNotice">{error}</div>}<div className="drawerActions">{detail&&<button className="button primary" onClick={save} disabled={busy||saved}>{saved?"Saved ✓":busy?"Saving…":collectionId?"Add to word book":"Add to my vocabulary"}</button>}<button className="button secondary" onClick={()=>setOpen(false)}>Close</button></div></div></div>:null}</>;
}
