"use client";
import { useEffect, useMemo, useState } from "react";
import { StageSelector } from "@/components/language/stage-selector";
import { StudentVocabularyManager } from "@/components/student-vocabulary-manager";
import { PronounceButton } from "@/components/vocabulary/pronounce-button";
import { VocabularyDetailCard } from "@/components/vocabulary/vocabulary-detail-card";
import { VocabularyWordbooks } from "@/components/vocabulary/vocabulary-wordbooks";
import type { VocabularyDetail } from "@/lib/vocabulary/types";
import type { LearningStage } from "@/lib/language/stages";

type CatalogItem={id:string;detail:VocabularyDetail;stages:LearningStage[];mastery:number;seenCount:number;correctCount:number;saved:boolean};
type ChoiceQuestion={vocabularyId:string;term:string;entryType:string;prompt:string;options:string[]};
type Passage={id:string;title:string;body:string;targetTerms:string[];questions:Array<{prompt:string;options:string[]}>};
type Tab="dictionary"|"wordbooks"|"practice"|"reading"|"mine";
type Collection={id:string;name:string;code:string|null;collectionType:"system"|"custom";cefrLevel:string|null;stage:string|null;itemCount:number;completionPercent:number;active:boolean;dailyTarget:number};

export function VocabularyLearningHub(){
 const[stage,setStage]=useState<LearningStage>("P6"),[tab,setTab]=useState<Tab>("dictionary"),[query,setQuery]=useState(""),[type,setType]=useState<"all"|"word"|"phrase">("all"),[items,setItems]=useState<CatalogItem[]>([]),[selected,setSelected]=useState<CatalogItem|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[collections,setCollections]=useState<Collection[]>([]),[collectionId,setCollectionId]=useState<string|null>(null);
 const[questions,setQuestions]=useState<ChoiceQuestion[]>([]),[qIndex,setQIndex]=useState(0),[feedback,setFeedback]=useState<{correct:boolean;correctAnswer?:string;explanation?:string}|null>(null),[practiceScore,setPracticeScore]=useState(0);
 const[passages,setPassages]=useState<Passage[]>([]),[passage,setPassage]=useState<Passage|null>(null),[readingFeedback,setReadingFeedback]=useState<Record<number,{correct:boolean;explanation?:string}>>({});
 const[lookupBusy,setLookupBusy]=useState(false);
 useEffect(()=>{fetch("/api/student/language-stage").then(r=>r.json() as Promise<{vocabularyStage?:LearningStage}>).then(b=>b.vocabularyStage&&setStage(b.vocabularyStage)).catch(()=>{})},[]);
 async function loadCollections(){try{const r=await fetch("/api/student/vocabulary/collections"),b=await r.json() as {collections?:Collection[]};setCollections(b.collections||[])}catch{}}
 useEffect(()=>{void loadCollections()},[]);
 async function persistStage(next:LearningStage){setStage(next);setCollectionId(null);setSelected(null);setQuestions([]);setPassage(null);setReadingFeedback({});await fetch("/api/student/language-stage",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({module:"vocabulary",stage:next})}).catch(()=>{});}
 useEffect(()=>{if(tab!=="dictionary")return;const ctl=new AbortController(),timer=setTimeout(async()=>{setLoading(true);setError("");try{const p=new URLSearchParams({stage,type});if(collectionId)p.set("collection",collectionId);if(query.trim())p.set("q",query.trim());const r=await fetch(`/api/student/vocabulary/catalog?${p}`,{signal:ctl.signal}),b=await r.json() as {items?:CatalogItem[];error?:string};if(!r.ok)throw new Error(b.error||"Could not load dictionary");setItems(b.items||[])}catch(e){if((e as Error).name!=="AbortError")setError(e instanceof Error?e.message:"Could not load dictionary")}finally{setLoading(false)}},180);return()=>{clearTimeout(timer);ctl.abort()}},[stage,query,type,tab,collectionId]);
 useEffect(()=>{if(tab!=="reading")return;fetch(`/api/student/vocabulary/reinforcement?mode=reading&stage=${encodeURIComponent(stage)}`).then(r=>r.json() as Promise<{passages?:Passage[]}>).then(b=>{setPassages(b.passages||[]);setPassage((b.passages||[])[0]||null);setReadingFeedback({})}).catch(()=>setError("Could not load reading practice"))},[stage,tab]);
 const stageCount=useMemo(()=>items.filter(x=>x.stages.includes(stage)).length,[items,stage]);
 const activeCollection=useMemo(()=>collections.find(c=>c.id===collectionId)||null,[collections,collectionId]);
 async function save(item:CatalogItem){const r=await fetch("/api/student/vocabulary",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({term:item.detail.term,detail:item.detail})});if(!r.ok){const b=await r.json().catch(()=>({})) as {error?:string};setError(b.error||"Could not save vocabulary");return;}setItems(xs=>xs.map(x=>x.id===item.id?{...x,saved:true}:x));setSelected(v=>v?.id===item.id?{...v,saved:true}:v);}
 async function explainUnknown(){
  const term=query.trim().replace(/\s+/g," ");if(!term)return;setLookupBusy(true);setError("");
  try{const r=await fetch("/api/student/vocabulary/enrich",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({term,context:"",schoolLevel:stage})}),b=await r.json() as {detail?:VocabularyDetail;error?:string};if(!r.ok||!b.detail)throw new Error(b.error||"Could not explain this term");setSelected({id:`lookup:${term.toLowerCase()}`,detail:b.detail,stages:[stage],mastery:0,seenCount:0,correctCount:0,saved:false});}
  catch(e){setError(e instanceof Error?e.message:"Could not explain this term")}finally{setLookupBusy(false)}
 }
 async function startPractice(){setError("");setFeedback(null);setPracticeScore(0);setQIndex(0);const r=await fetch(`/api/student/vocabulary/reinforcement?mode=choice&stage=${encodeURIComponent(stage)}&count=10`),b=await r.json() as {questions?:ChoiceQuestion[];error?:string};if(!r.ok){setError(b.error||"Could not start practice");return;}setQuestions(b.questions||[]);}
 async function answerChoice(selectedAnswer:string){const q=questions[qIndex];if(!q||feedback)return;const r=await fetch("/api/student/vocabulary/reinforcement",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"choice",stage,vocabularyId:q.vocabularyId,selected:selectedAnswer})}),b=await r.json() as {correct:boolean;correctAnswer?:string;explanation?:string;error?:string};if(!r.ok){setError(b.error||"Could not score answer");return;}setFeedback(b);if(b.correct)setPracticeScore(x=>x+1);}
 function nextChoice(){setFeedback(null);setQIndex(i=>Math.min(i+1,questions.length));}
 async function answerReading(p:Passage,index:number,optionIndex:number){if(readingFeedback[index])return;const r=await fetch("/api/student/vocabulary/reinforcement",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"reading",stage,passageId:p.id,questionIndex:index,optionIndex})}),b=await r.json() as {correct:boolean;explanation?:string;error?:string};if(!r.ok){setError(b.error||"Could not score reading answer");return;}setReadingFeedback(x=>({...x,[index]:b}));}
 return <>
  <section className="languageStageBar card"><div><span className="eyebrow">Singapore curriculum-aligned</span><h2>Choose your learning stage</h2><p>Switch level without changing your Student account. Search can still find words across the full P1–S4 dictionary.</p></div><StageSelector value={stage} onChange={persistStage}/></section>
  <div className="languageTabs" role="tablist">{([['dictionary','Dictionary'],['wordbooks','Word books'],['practice','Quick choices'],['reading','Reading boost'],['mine','My vocabulary']] as const).map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {error&&<div className="notice warnNotice">{error}</div>}
  {tab==="dictionary"&&<div className="collectionStrip card"><button className={!collectionId?"active":""} onClick={()=>setCollectionId(null)}>Stage · {stage}</button>{collections.map(c=><button key={c.id} className={collectionId===c.id?"active":""} onClick={()=>setCollectionId(c.id)}>{c.code||c.name}{c.cefrLevel?` · ${c.cefrLevel}`:""}</button>)}</div>}
  {tab==="dictionary"&&<section><div className="vocabToolbar card languageToolbar"><div className="vocabSearch"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search any catalogued word, phrase, meaning or example…"/></div><div className="vocabFilters">{(['all','word','phrase'] as const).map(x=><button key={x} className={type===x?"active":""} onClick={()=>setType(x)}>{x}</button>)}</div><div className="dictionaryMeta">{query.trim()?`${items.length} matches`:(activeCollection?`${items.length} entries in ${activeCollection.name}`:`${stageCount} core entries for ${stage}`)}</div></div>{loading?<div className="emptyState">Searching the dictionary…</div>:!items.length?<div className="emptyState"><h3>No catalog match</h3><p>This term is not in the curated stage catalogue. You can still use the dictionary assistant to explain it and save it to My vocabulary.</p>{query.trim()&&<button className="button primary" onClick={explainUnknown} disabled={lookupBusy}>{lookupBusy?"Explaining…":`Explain “${query.trim()}”`}</button>}</div>:<div className="dictionaryGrid">{items.map(item=><article className="dictionaryCard card" key={item.id}><div className="vocabCardTop"><span className="entryTypePill">{item.detail.entryType}</span><span className="stageMini">{item.stages.length?item.stages.join(" · "):(activeCollection?.code||activeCollection?.cefrLevel||"Word book")}</span></div><div className="dictionaryTerm"><h3>{item.detail.term}</h3><PronounceButton text={item.detail.term} compact/></div>{item.detail.partOfSpeech&&<div className="muted">{item.detail.partOfSpeech}</div>}<p>{item.detail.meanings[0]?.simple||item.detail.meanings[0]?.definition}</p>{item.detail.examples[0]?.sentence&&<blockquote>{item.detail.examples[0].sentence}</blockquote>}<div className="dictionaryActions"><button className="button ghost smallButton" onClick={()=>setSelected(item)}>Open dictionary card</button><button className={item.saved?"button secondary smallButton":"button primary smallButton"} onClick={()=>save(item)} disabled={item.saved}>{item.saved?"Saved":"＋ Save"}</button></div>{item.seenCount>0&&<div className="catalogProgress"><span style={{width:`${Math.max(4,item.mastery)}%`}}/><small>{Math.round(item.mastery)}% reinforcement mastery</small></div>}</article>)}</div>}</section>}
  {tab==="wordbooks"&&<VocabularyWordbooks onOpen={id=>{setCollectionId(id);setTab("dictionary");setQuery("");void loadCollections()}}/>}
  {tab==="practice"&&<section className="card practiceFocus"><div className="sectionHeading"><div><span>Vocabulary reinforcement · {stage}</span><h2>Meaning & context choices</h2><p>Short retrieval practice strengthens the stage vocabulary you are learning.</p></div><button className="button primary" onClick={startPractice}>{questions.length?"Restart 10 questions":"Start 10 questions"}</button></div>{questions.length>0&&qIndex<questions.length&&<div className="quizPanel"><div className="quizProgress">Question {qIndex+1} / {questions.length} · Score {practiceScore}</div><h3>{questions[qIndex].prompt}</h3><PronounceButton text={questions[qIndex].term}/><div className="choiceGrid">{questions[qIndex].options.map((option,i)=><button key={`${qIndex}-${i}`} disabled={Boolean(feedback)} onClick={()=>answerChoice(option)}>{option}</button>)}</div>{feedback&&<div className={feedback.correct?"notice successNotice":"notice warnNotice"}><strong>{feedback.correct?"Correct":"Not yet"}</strong>{!feedback.correct&&feedback.correctAnswer&&<p>Answer: {feedback.correctAnswer}</p>}<p>{feedback.explanation}</p><button className="button primary smallButton" onClick={nextChoice}>Next</button></div>}</div>}{questions.length>0&&qIndex>=questions.length&&<div className="emptyState"><h3>Set complete · {practiceScore}/{questions.length}</h3><p>Your vocabulary mastery has been updated from these retrieval attempts.</p><button className="button primary" onClick={startPractice}>Practise another set</button></div>}</section>}
  {tab==="reading"&&<section className="readingReinforcement"><div className="readingPassageList card"><span className="eyebrow">Reading boost · {stage}</span><h3>Short passages</h3>{passages.map(p=><button className={passage?.id===p.id?"active":""} onClick={()=>{setPassage(p);setReadingFeedback({})}} key={p.id}>{p.title}<small>{p.targetTerms.slice(0,4).join(" · ")}</small></button>)}</div>{passage?<article className="card readingPracticeArticle"><div className="eyebrow">Target vocabulary</div><div className="chips">{passage.targetTerms.map(t=><span className="chip" key={t}>{t}</span>)}</div><h2>{passage.title}</h2><div className="readingBody">{passage.body}</div>{passage.questions.map((q,qi)=><section className="readingQuestion" key={qi}><h4>{qi+1}. {q.prompt}</h4><div className="choiceGrid compact">{q.options.map((opt,oi)=><button disabled={Boolean(readingFeedback[qi])} onClick={()=>answerReading(passage,qi,oi)} key={oi}>{opt}</button>)}</div>{readingFeedback[qi]&&<div className={readingFeedback[qi].correct?"inlineFeedback correct":"inlineFeedback"}>{readingFeedback[qi].correct?"Correct. ":"Review the passage. "}{readingFeedback[qi].explanation}</div>}</section>)}</article>:<div className="emptyState">No passage for this stage yet.</div>}</section>}
  {tab==="mine"&&<StudentVocabularyManager schoolLevel={stage}/>}
  {selected&&<div className="vocabDrawerBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="vocabDrawer wide"><button className="drawerClose" onClick={()=>setSelected(null)}>×</button><div className="eyebrow">Dictionary · {selected.stages.length?selected.stages.join(" / "):(activeCollection?.name||"Word book")}</div><VocabularyDetailCard detail={selected.detail}/><div className="drawerActions"><button className={selected.saved?"button secondary":"button primary"} onClick={()=>save(selected)} disabled={selected.saved}>{selected.saved?"Already in My vocabulary":"Save to My vocabulary"}</button><button className="button secondary" onClick={()=>setSelected(null)}>Close</button></div></div></div>}
 </>;
}
