import {appendJobLog,getJob} from "@/lib/jobs/store";

export const DEFAULT_TASK_TIMEOUT_MINUTES=120;
export function clampTaskTimeoutMinutes(value:unknown){const n=Math.round(Number(value));return Number.isFinite(n)?Math.max(5,Math.min(1440,n)):DEFAULT_TASK_TIMEOUT_MINUTES;}
function scopeKey(tenantId?:string|null){return tenantId?{scopeType:"tenant" as const,scopeId:tenantId}:{scopeType:"platform" as const,scopeId:"platform"};}
export async function getQueueRuntimePolicy(db:D1Database,tenantId?:string|null){const s=scopeKey(tenantId);const row=await db.prepare("SELECT task_timeout_minutes,updated_at FROM queue_runtime_policy WHERE scope_type=? AND scope_id=?").bind(s.scopeType,s.scopeId).first<{task_timeout_minutes:number;updated_at:string}>().catch(()=>null);return{timeoutMinutes:clampTaskTimeoutMinutes(row?.task_timeout_minutes??DEFAULT_TASK_TIMEOUT_MINUTES),updatedAt:row?.updated_at||null,scope:s.scopeType};}
export async function setQueueRuntimePolicy(db:D1Database,tenantId:string|null|undefined,value:unknown,updatedBy?:string|null){const s=scopeKey(tenantId),timeout=clampTaskTimeoutMinutes(value);await db.prepare("INSERT INTO queue_runtime_policy(scope_type,scope_id,task_timeout_minutes,updated_by,updated_at) VALUES (?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(scope_type,scope_id) DO UPDATE SET task_timeout_minutes=excluded.task_timeout_minutes,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP").bind(s.scopeType,s.scopeId,timeout,updatedBy||null).run();return getQueueRuntimePolicy(db,tenantId);}
function utcMillis(value:string|null|undefined){if(!value)return NaN;const clean=value.includes("T")?value:`${value.replace(" ","T")}Z`;return Date.parse(clean);}
async function timeOutJob(db:D1Database,id:string,timeoutMinutes:number){const job=await getJob(db,id);if(!job||job.status!=="running")return false;const message=`Task exceeded the configured ${timeoutMinutes}-minute execution timeout.`;const changed=await db.prepare("UPDATE generation_jobs SET status='failed',stage='timed_out',error=?,completed_at=COALESCE(completed_at,CURRENT_TIMESTAMP),updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='running' AND deleted_at IS NULL").bind(message,id).run();if(!changed.meta.changes)return false;await appendJobLog(db,id,{level:"error",eventType:"job_timed_out",stage:"timed_out",message,details:{timeoutMinutes,startedAt:job.started_at,progress:job.progress}});
 if(job.entity_type==="content"&&job.entity_id)await db.prepare("UPDATE content_items SET status='failed',generation_stage='timed_out',generation_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status!='published'").bind(message,job.entity_id).run().catch(()=>null);
 if(job.entity_type==="writing_submission"&&job.entity_id)await db.prepare("UPDATE writing_submissions SET status='failed',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='evaluating'").bind(job.entity_id).run().catch(()=>null);
 if(job.entity_type==="learning_summary"&&job.entity_id)await db.prepare("UPDATE learning_summary_attempts SET status='failed',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='evaluating'").bind(job.entity_id).run().catch(()=>null);
 if(job.entity_type==="specialised_item"&&job.entity_id)await db.prepare("UPDATE specialised_session_items SET status='failed',feedback_json=? WHERE id=? AND status='evaluating'").bind(JSON.stringify({error:message}),job.entity_id).run().catch(()=>null);
 return true;}

export async function sweepTimedOutJobs(db:D1Database,args:{tenantId?:string|null;allScopes?:boolean}={}){
 const all=args.allScopes===true;let sql="SELECT id,tenant_id,scope,started_at FROM generation_jobs WHERE status='running' AND deleted_at IS NULL";const binds:string[]=[];if(!all){if(args.tenantId){sql+=" AND tenant_id=? AND scope='tenant'";binds.push(args.tenantId)}else sql+=" AND scope='global' AND tenant_id IS NULL";}const stmt=db.prepare(sql),rows=binds.length?await stmt.bind(...binds).all<{id:string;tenant_id:string|null;scope:string;started_at:string|null}>():await stmt.all<{id:string;tenant_id:string|null;scope:string;started_at:string|null}>();
 const cache=new Map<string,number>(),now=Date.now();let timedOut=0;
 for(const row of rows.results){const key=row.tenant_id||"__platform__";let timeout=cache.get(key);if(timeout===undefined){timeout=(await getQueueRuntimePolicy(db,row.tenant_id)).timeoutMinutes;cache.set(key,timeout);}const started=utcMillis(row.started_at);if(Number.isFinite(started)&&now-started>=timeout*60_000){if(await timeOutJob(db,row.id,timeout))timedOut++;}}
 return{checked:rows.results.length,timedOut};
}
