import { getEnv } from "@/lib/cloudflare";
import { requireTenantSession } from "@/lib/auth/tenant";
import { LEARNING_STAGES, isLearningStage } from "@/lib/language/stages";
import { clampVocabularySpecialistDailyWords, getVocabularySpecialistPolicy } from "@/lib/vocabulary-specialist/policy";
function parse<T>(s:string|null,f:T[]=[]):T[]{try{const v=s?JSON.parse(s):f;return Array.isArray(v)?v as T[]:f}catch{return f}}
export async function GET(request:Request){const auth=await requireTenantSession(request);if(auth.response)return auth.response;const db=getEnv().DB,tenantId=auth.session!.tenant_id,url=new URL(request.url),sessionId=url.searchParams.get("sessionId");
 if(sessionId){const s=await db.prepare(`SELECT s.*,c.nickname FROM vocabulary_specialist_sessions s JOIN child_profiles c ON c.id=s.child_id WHERE s.id=? AND s.tenant_id=?`).bind(sessionId,tenantId).first<any>();if(!s)return Response.json({error:"Practice record not found"},{status:404});const qs=(await db.prepare("SELECT id,item_order,term,stem,options_json,answer_index,selected_index,correct,explanation,generated_at,answered_at FROM vocabulary_specialist_question_attempts WHERE session_id=? ORDER BY item_order").bind(sessionId).all<any>()).results;const ca=(await db.prepare("SELECT id,answers_json,correctness_json,correct_count,total_count,passed,created_at FROM vocabulary_specialist_cloze_attempts WHERE session_id=? ORDER BY created_at").bind(sessionId).all<any>()).results;return Response.json({detail:{session:{...s,cloze_blanks:parse(s.cloze_blanks_json)},questions:qs.map(q=>({...q,options:parse(q.options_json),correct:Boolean(q.correct)})),clozeAttempts:ca.map(a=>({...a,answers:parse(a.answers_json),correctness:parse(a.correctness_json),passed:Boolean(a.passed)}))}})}
 const policies=await Promise.all(LEARNING_STAGES.map(stage=>getVocabularySpecialistPolicy(db,tenantId,stage)));const students=(await db.prepare(`SELECT c.id,c.nickname,c.school_level,COUNT(w.id) word_count FROM child_profiles c LEFT JOIN vocabulary_specialist_wordbook w ON w.child_id=c.id WHERE c.tenant_id=? GROUP BY c.id ORDER BY lower(c.nickname)`).bind(tenantId).all<any>()).results;const sessions=(await db.prepare(`SELECT s.id,s.child_id,c.nickname,s.task_date,s.school_level,s.daily_target,s.status,s.words_completed,s.started_at,s.passed_at,COUNT(DISTINCT q.id) question_count,COALESCE(SUM(CASE WHEN q.correct=1 THEN 1 ELSE 0 END),0) mcq_correct,(SELECT COUNT(*) FROM vocabulary_specialist_cloze_attempts ca WHERE ca.session_id=s.id) cloze_attempts FROM vocabulary_specialist_sessions s JOIN child_profiles c ON c.id=s.child_id LEFT JOIN vocabulary_specialist_question_attempts q ON q.session_id=s.id WHERE s.tenant_id=? GROUP BY s.id ORDER BY s.task_date DESC,s.started_at DESC LIMIT 200`).bind(tenantId).all<any>()).results;return Response.json({stages:LEARNING_STAGES,policies,students:students.map(x=>({...x,word_count:Number(x.word_count)})),sessions:sessions.map(x=>({...x,daily_target:Number(x.daily_target),words_completed:Number(x.words_completed),question_count:Number(x.question_count),mcq_correct:Number(x.mcq_correct),cloze_attempts:Number(x.cloze_attempts)}))});}
export async function PUT(request:Request){const auth=await requireTenantSession(request);if(auth.response)return auth.response;const db=getEnv().DB,tenantId=auth.session!.tenant_id,body=await request.json().catch(()=>({})) as Record<string,unknown>;if(!isLearningStage(body.learnerStage))return Response.json({error:"Choose a valid learner stage"},{status:400});const dailyWords=clampVocabularySpecialistDailyWords(body.dailyWords);await db.prepare(`INSERT INTO tenant_vocabulary_specialist_policy(tenant_id,learner_stage,daily_words,updated_at) VALUES(?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(tenant_id,learner_stage) DO UPDATE SET daily_words=excluded.daily_words,updated_at=CURRENT_TIMESTAMP`).bind(tenantId,body.learnerStage,dailyWords).run();return Response.json({ok:true,learnerStage:body.learnerStage,dailyWords});}
