import Link from "next/link";
import { PageIntro } from "@/components/ui";
export default function AdminPage(){return <><PageIntro eyebrow="Operations" title="English Mastery administration" description="Run source ingestion, persistent AI generation jobs, writing and Paper 2 content, diagnostics, publication and curriculum monitoring."/><div className="activityGrid adminHomeGrid">
<Link className="activityCard tone-violet" href="/platform/tenants"><div className="activityKicker">Multi-tenant</div><h3>Tenants</h3><p>Provision schools and organisations with isolated staff, courses, assignments and ModelBridge credentials.</p><span className="cardArrow">→</span></Link>
<Link className="activityCard" href="/platform/sources?tab=reading"><div className="activityKicker">Reading sources</div><h3>Internet sources</h3><p>Discover suitable science, Singapore, nature, history and community references.</p><span className="cardArrow">→</span></Link>
<Link className="activityCard tone-green" href="/platform/sources?tab=library"><div className="activityKicker">Reading</div><h3>Lesson library</h3><p>Generation tasks appear immediately, then move through generating, draft and published states.</p><span className="cardArrow">→</span></Link>
<Link className="activityCard tone-violet" href="/platform/sources?tab=listening"><div className="activityKicker">Listening</div><h3>Listening studio</h3><p>Discover YouTube/podcast media or upload owned audio. Async lessons persist before source/AI work begins.</p><span className="cardArrow">→</span></Link>
<Link className="activityCard tone-amber" href="/platform/writing"><div className="activityKicker">Writing</div><h3>Writing prompts</h3><p>Create P5/P6 situational and continuous-writing tasks with hint-first AI review.</p><span className="cardArrow">→</span></Link>
<Link className="activityCard" href="/platform/questions"><div className="activityKicker">Paper 2</div><h3>Question bank</h3><p>Generate validated draft questions, inspect answers and explanations, then publish.</p><span className="cardArrow">→</span></Link>
<Link className="activityCard tone-green" href="/platform/jobs"><div className="activityKicker">Background work</div><h3>Work Queue</h3><p>Track queued, running, completed and failed tasks in FIFO order. Delete only terminal task history.</p><span className="cardArrow">→</span></Link>
<Link className="activityCard tone-amber" href="/platform/syllabus-monitor"><div className="activityKicker">Curriculum</div><h3>Syllabus monitor</h3><p>Track official MOE/SEAB changes and create review jobs.</p><span className="cardArrow">→</span></Link>
<Link className="activityCard" href="/platform/roadmap"><div className="activityKicker">Product</div><h3>Implementation roadmap</h3><p>See completed capabilities against the original product design and next milestones.</p><span className="cardArrow">→</span></Link>
<Link className="activityCard tone-violet" href="/platform/settings/integrations"><div className="activityKicker">Settings</div><h3>Integrations</h3><p>Configure ModelBridge, YouTube, STT/TTS and pronunciation providers without Wrangler commands.</p><span className="cardArrow">→</span></Link>
</div><div className="notice" style={{marginTop:20}}><strong>V0.6 platform rule:</strong> background source retrieval and AI generation create their database job/entity first. Navigation, source switching or a slow provider cannot make the task disappear; later processing updates status only.</div></>}
