"use client";
import Link from"next/link";
import{useEffect,useState}from"react";
import{useRouter}from"next/navigation";
type Me={role:"student"|"admin"|"guest";child?:{id:string;nickname:string;school_level:string;target_al:string;exam_year:number|null}|null;account?:{login_name:string|null;last_login_at:string|null}|null;tenant?:{id:string;name:string|null;slug:string|null}|null};
export function AccountEntry(){
 const r=useRouter(),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[me,setMe]=useState<Me|null>(null),[student,setStudent]=useState({loginName:"",pin:""});
 async function load(){setLoading(true);try{const res=await fetch("/api/auth/me",{cache:"no-store"});setMe(await res.json() as Me)}catch{setMe({role:"guest"})}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function signIn(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg("");const res=await fetch("/api/auth/student/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(student)});const b=await res.json().catch(()=>({}))as{error?:string};setBusy(false);if(!res.ok){setMsg(b.error||"Sign-in failed");return;}await load();r.refresh();}
 async function signOut(){setBusy(true);setMsg("");const res=await fetch("/api/auth/student/logout",{method:"POST"});setBusy(false);if(!res.ok){setMsg("Sign out failed");return;}setMe({role:"guest"});r.refresh();}
 const isStudent=me?.role==="student"&&me.child;
 return <div style={{maxWidth:760,margin:"0 auto"}}><div className="sectionHeading"><div><span>Account</span><h1>{isStudent?"Student account":"English Mastery sign in"}</h1><p>{isStudent?"View the currently signed-in student account. Tenant Admin sign-in remains available below.":"Students use a login name + PIN. Tenant Admin uses tenant slug + email + password."}</p></div></div>{msg&&<div className="notice warnNotice">{msg}</div>}
 {loading?<section className="card"><div className="emptyState">Loading account…</div></section>:isStudent?<section className="card"><div className="cardHeader"><div><h2>{me.child!.nickname}</h2><span>Signed in as Student</span></div><span className="statusPill published">Active</span></div><div className="bootstrapGrid"><div><span>Login name</span><strong>{me.account?.login_name||"—"}</strong></div><div><span>School level</span><strong>{me.child!.school_level}</strong></div><div><span>Target AL</span><strong>{me.child!.target_al}</strong></div><div><span>Exam year</span><strong>{me.child!.exam_year||"—"}</strong></div><div><span>Organisation</span><strong>{me.tenant?.name||"—"}</strong></div><div><span>Last login</span><strong>{me.account?.last_login_at?new Date(me.account.last_login_at).toLocaleString():"—"}</strong></div></div><div className="rowActions" style={{marginTop:16}}><Link className="button primary" href="/">Continue learning</Link><button className="button secondary" disabled={busy} onClick={()=>void signOut()}>{busy?"Signing out…":"Sign out"}</button></div></section>:<section className="card"><div className="cardHeader"><h2>Student login</h2><span>No email required</span></div><form className="stackForm" onSubmit={signIn}><label>Login name<input autoComplete="username" value={student.loginName} onChange={e=>setStudent({...student,loginName:e.target.value})}/></label><label>PIN<input type="password" inputMode="numeric" autoComplete="current-password" value={student.pin} onChange={e=>setStudent({...student,pin:e.target.value})}/></label><button className="button primary" disabled={busy}>Sign in as Student</button></form></section>}
 <section className="card" style={{marginTop:16}}><div className="cardHeader"><h2>Tenant Admin</h2><span>Partner workspace</span></div><p>The Tenant Admin manages students, resources, courses, practice, assignments and tenant ModelBridge settings.</p><div className="rowActions"><Link className="button secondary" href="/admin/login">Open Admin sign in</Link><Link className="button primary" href="/register">Create an organisation</Link></div></section></div>;
}
