"use client";
import{useEffect,useMemo,useState}from"react";

type Source={id:string;name:string;url:string;provider:string;source_kind:string;categories_json:string;usage_mode:string;licence_note?:string;priority:number};
type Skill={id:string;name:string;domain:string;school_level:string;difficulty:number};
type Batch={id:string;source_name:string;school_level:string;category:string;subcategory:string;topic:string;difficulty:number;requested_count:number;status:string;source_stage?:string;source_error?:string|null;item_count:number;generating_count:number;review_count:number;approved_count:number;duplicate_count:number;failed_count:number;rejected_count:number;created_at:string};
type Draft={id:string;question_type:string;school_level:string;difficulty:number;stem_json:string;answer_json:string;explanation_json:string|null;status:string;marks:number;source_name:string;category:string;subcategory:string;batch_id:string;generation_job_id:string|null;review_status:string;quality_score:number|null;quality_json:string|null;duplicate_of_question_id:string|null;generation_error:string|null;skill_ids?:string};
type Data={sources:Source[];skills:Skill[];batches:Batch[];drafts:Draft[];subcategories:Record<string,string[]>};
const domainFor:Record<string,string>={oral:"speaking",reading_comprehension:"reading",cloze:"reading",writing:"writing"};
const labels:Record<string,string>={oral:"Oral",reading_comprehension:"Reading comprehension",cloze:"Cloze",writing:"Writing"};
function json<T>(text:string|undefined|null,fallback:T):T{try{return JSON.parse(text||"")as T}catch{return fallback;}}
export function TenantQuestionBank({mode="questions"}:{mode?:"cloze"|"questions"}){
 const[data,setData]=useState<Data>({sources:[],skills:[],batches:[],drafts:[],subcategories:{}}),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[reviewFilter,setReviewFilter]=useState("all"),[form,setForm]=useState({sourceId:"qsrc-internal",schoolLevel:"P6",category:mode==="cloze"?"cloze":"reading_comprehension",subcategory:"mixed",skillId:"R-INFER",topic:"Singapore school and community life",difficulty:3,count:10});
 async function load(){const r=await fetch("/api/admin/question-bank/generate"),b=await r.json().catch(()=>({}))as Partial<Data>;if(r.ok)setData({sources:b.sources||[],skills:b.skills||[],batches:b.batches||[],drafts:b.drafts||[],subcategories:b.subcategories||{}});}
 useEffect(()=>{void load();const t=setInterval(()=>void load(),4000);return()=>clearInterval(t)},[]);
 const allowedCategories=mode==="cloze"?["cloze"]:["oral","reading_comprehension","writing"];
 const scopedSources=useMemo(()=>data.sources.filter(s=>json<string[]>(s.categories_json,[]).some(c=>allowedCategories.includes(c))),[data.sources,mode]);
 const compatibleSources=useMemo(()=>scopedSources.filter(s=>json<string[]>(s.categories_json,[]).includes(form.category)),[scopedSources,form.category]);
 const compatibleSkills=useMemo(()=>data.skills.filter(s=>s.domain===domainFor[form.category]),[data.skills,form.category]);
 const subcats=data.subcategories[form.category]||[];
 useEffect(()=>{if(!compatibleSources.some(s=>s.id===form.sourceId)&&compatibleSources[0])setForm(v=>({...v,sourceId:compatibleSources[0].id}));},[form.sourceId,compatibleSources]);
 useEffect(()=>{if(!subcats.includes(form.subcategory)&&subcats[0])setForm(v=>({...v,subcategory:subcats[0]}));},[form.subcategory,subcats]);
 useEffect(()=>{if(!compatibleSkills.some(s=>s.id===form.skillId)&&compatibleSkills[0])setForm(v=>({...v,skillId:compatibleSkills[0].id}));},[form.skillId,compatibleSkills]);
 async function generate(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg("");const r=await fetch("/api/admin/question-bank/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),b=await r.json().catch(()=>({}))as{batchId?:string;created?:number;dispatched?:number;error?:string};setBusy(false);setMsg(r.ok?`Batch ${b.batchId} created: ${b.created} draft slots persisted, ${b.dispatched} queued.`:b.error||"Could not create batch");await load();}
 async function bulk(action:string,ids=[...selected]){if(!ids.length)return;if((action==="delete"||action==="reject")&&!confirm(`${action} ${ids.length} selected Question Bank item(s)?`))return;setBusy(true);const r=await fetch("/api/admin/question-bank/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,questionIds:ids})}),b=await r.json().catch(()=>({}))as{changed?:number;failed?:number;error?:string};setBusy(false);setMsg(r.ok||b.changed?`${action}: ${b.changed||0} changed${b.failed?`, ${b.failed} skipped/failed`:""}.`:b.error||`${action} failed`);setSelected(new Set());await load();}
 const scopedDrafts=useMemo(()=>data.drafts.filter(d=>allowedCategories.includes(d.category)),[data.drafts,mode]);
 const scopedBatches=useMemo(()=>data.batches.filter(b=>allowedCategories.includes(b.category)),[data.batches,mode]);
 const reviewStatuses=useMemo(()=>[...new Set(scopedDrafts.map(d=>d.review_status))].sort(),[scopedDrafts]);
 const filteredDrafts=useMemo(()=>scopedDrafts.filter(d=>reviewFilter==="all"||d.review_status===reviewFilter),[scopedDrafts,reviewFilter]);
 const selectedCount=selected.size;
 useEffect(()=>setSelected(new Set()),[reviewFilter]);
 function toggle(id:string){setSelected(prev=>{const n=new Set(prev);n.has(id)?n.delete(id):n.add(id);return n;});}
 return <>
  <div className="adminSplit">
   <section className="card"><div className="cardHeader"><h2>{mode==="cloze"?"Cloze content creation":"Question Bank expansion"}</h2><span>Persistent · serial Queue</span></div>
    <form className="stackForm" onSubmit={generate}>
     <div className="formGrid"><label>Level<select value={form.schoolLevel} onChange={e=>setForm({...form,schoolLevel:e.target.value})}><option>P5</option><option>P6</option></select></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{allowedCategories.map(k=><option value={k} key={k}>{labels[k]}</option>)}</select></label></div>
     <div className="formGrid"><label>Subcategory<select value={form.subcategory} onChange={e=>setForm({...form,subcategory:e.target.value})}>{subcats.map(x=><option value={x} key={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label>Difficulty<input type="range" min="1" max="5" value={form.difficulty} onChange={e=>setForm({...form,difficulty:Number(e.target.value)})}/><span>{form.difficulty}/5</span></label></div>
     <label>Reference source<select value={form.sourceId} onChange={e=>setForm({...form,sourceId:e.target.value})}>{compatibleSources.map(s=><option value={s.id} key={s.id}>{s.name} · {s.usage_mode}</option>)}</select></label>
     <label>Skill<select value={form.skillId} onChange={e=>setForm({...form,skillId:e.target.value})}>{compatibleSkills.map(s=><option value={s.id} key={s.id}>{s.id} · {s.name}</option>)}</select></label>
     <label>Topic/context<input value={form.topic} maxLength={160} onChange={e=>setForm({...form,topic:e.target.value})}/></label>
     <label>How many original draft items?<input type="number" min="1" max="50" value={form.count} onChange={e=>setForm({...form,count:Math.max(1,Math.min(50,Number(e.target.value)||1))})}/></label>
     <div className="chips">{[5,10,20,30,50].map(n=><button type="button" className={form.count===n?"chip active":"chip"} key={n} onClick={()=>setForm({...form,count:n})}>{n}</button>)}</div>
     <button className="button primary" disabled={busy||!form.sourceId||!form.skillId}>{busy?"Creating persistent jobs…":`Create & queue ${form.count} drafts`}</button>
     <div className="notice"><strong>Pipeline:</strong> all placeholder Question Bank records and jobs are saved first. Cloudflare Queue then generates exactly one item at a time. Every generated item is structure-checked, deduplicated, quality-scored and left in Draft for human review.</div>
    </form>
   </section>
   <section className="card"><div className="cardHeader"><h2>Recent batches</h2><span>{scopedBatches.length}</span></div><div className="batchList">{scopedBatches.slice(0,10).map(b=><div className="batchRow" key={b.id}><div><strong>{b.school_level} · {labels[b.category]||b.category} · {b.subcategory.replaceAll("_"," ")}</strong><div className="tableSub">{b.source_name} · {b.topic} · source {b.source_stage||"pending"}</div>{b.source_error&&<div className="tableSub">source fallback: {b.source_error}</div>}</div><span className="statusPill">{b.status}</span><div className="tableSub">{b.generating_count||0} generating · {b.review_count||0} review · {b.approved_count||0} published · {b.duplicate_count||0} duplicate · {b.failed_count||0} failed</div></div>)}</div>{msg&&<div className="notice" style={{marginTop:12}}>{msg}</div>}</section>
  </div>
  <section className="card" style={{marginTop:20}}><div className="cardHeader"><h2>{mode==="cloze"?"Cloze library":"Question library"}</h2><span>{scopedDrafts.length} recent</span></div>
   <div className="rowActions" style={{marginBottom:12}}><label>Status <select value={reviewFilter} onChange={e=>setReviewFilter(e.target.value)}><option value="all">All statuses</option>{reviewStatuses.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label><button className="button ghost smallButton" disabled={!filteredDrafts.length} onClick={()=>setSelected(new Set(filteredDrafts.map(d=>d.id)))}>Select filtered</button><button className="button ghost smallButton" onClick={()=>setSelected(new Set())}>Clear</button><button className="button primary smallButton" disabled={!selectedCount||busy} onClick={()=>bulk("publish")}>Publish selected</button><button className="button secondary smallButton" disabled={!selectedCount||busy} onClick={()=>bulk("retry")}>Retry / regenerate</button><button className="button ghost smallButton" disabled={!selectedCount||busy} onClick={()=>bulk("reject")}>Reject</button><button className="button danger smallButton" disabled={!selectedCount||busy} onClick={()=>bulk("delete")}>Delete</button><span className="muted">{selectedCount} selected · {filteredDrafts.length}/{scopedDrafts.length} shown</span></div>
   <div className="contentTableWrap"><table className="monitorTable"><thead><tr><th></th><th>Question</th><th>Answer / explanation</th><th>Quality</th><th>Status</th></tr></thead><tbody>{filteredDrafts.map(d=>{const stem=json<Record<string,unknown>>(d.stem_json,{}),answer=json<Record<string,unknown>>(d.answer_json,{}),exp=json<Record<string,unknown>>(d.explanation_json,{}),quality=json<{notes?:string[];maxSimilarity?:number}>(d.quality_json,{});const options=Array.isArray(stem.options)?stem.options.filter((x):x is string=>typeof x==="string"):[];const correct=typeof answer.correctOption==="number"&&options[answer.correctOption]?options[answer.correctOption]:String(answer.answer||answer.modelAnswer||answer.rubric||"");return <tr key={d.id}><td><input type="checkbox" checked={selected.has(d.id)} onChange={()=>toggle(d.id)}/></td><td><strong>{d.school_level} · {d.category.replaceAll("_"," ")} · {d.subcategory.replaceAll("_"," ")}</strong><div className="tableSub">{d.source_name} · {d.skill_ids||"unmapped"}</div><div>{String(stem.title||"")}</div><div>{String(stem.prompt||"")}</div>{typeof stem.passage==="string"&&stem.passage.length>0&&<details><summary>Passage</summary><div className="tableSub">{stem.passage}</div></details>}</td><td><strong>{correct||"—"}</strong><div className="tableSub">{String(exp.text||exp.explanation||"")}</div>{d.duplicate_of_question_id&&<div className="notice errorNotice">Possible duplicate of {d.duplicate_of_question_id}</div>}{d.generation_error&&<div className="notice errorNotice">{d.generation_error}</div>}</td><td><strong>{d.quality_score??"—"}</strong><div className="tableSub">{(quality.notes||[]).join(" · ")}</div>{typeof quality.maxSimilarity==="number"&&<div className="tableSub">nearest similarity {Math.round(quality.maxSimilarity*100)}%</div>}</td><td><span className={d.review_status==="needs_review"?"statusPill published":"statusPill"}>{d.review_status.replaceAll("_"," ")}</span><div className="tableSub">{d.generation_job_id||""}</div></td></tr>})}</tbody></table></div>
  </section>
  <section className="card" style={{marginTop:20}}><div className="cardHeader"><h2>{mode==="cloze"?"Cloze sources":"Question Bank sources"}</h2><span>{scopedSources.length} configured</span></div><div className="notice"><strong>Copyright rule:</strong> reference-only sources guide level, skill coverage, topic domain or question form. The expansion generator creates new original passages and questions; it does not ingest or republish protected source text.</div><div className="contentTableWrap"><table className="monitorTable"><thead><tr><th>Source</th><th>Categories</th><th>Policy</th></tr></thead><tbody>{scopedSources.map(s=><tr key={s.id}><td><strong>{s.name}</strong><div className="tableSub">{s.provider} · {s.source_kind}</div><a href={s.url} target="_blank" rel="noreferrer">Open source ↗</a></td><td>{json<string[]>(s.categories_json,[]).join(" · ")}</td><td><span className="statusPill">{s.usage_mode}</span><div className="tableSub">{s.licence_note||""}</div></td></tr>)}</tbody></table></div></section>
 </>;
}
