import {getEnv} from "@/lib/cloudflare";
import {resolveIntegrations} from "@/lib/settings/runtime";
import {requireAdmin} from "@/lib/auth/admin";
import {insertLearningMaterial} from "@/lib/content/store";
import type {AdaptedLearningMaterial} from "@/lib/content/types";
import {enqueueJob} from "@/lib/jobs/dispatch";
import {duplicateSkip} from "@/lib/content/dedup";

export async function GET(request:Request){const denied=await requireAdmin(request);if(denied)return denied;const env=await resolveIntegrations(getEnv());const rows=await env.DB.prepare("SELECT c.id,c.title,c.school_level,c.topic,c.status,c.description,c.source_url,c.source_attribution,c.published_at,c.updated_at,c.generation_job_id,c.generation_stage,c.generation_error,j.progress AS generation_progress,COUNT(q.id) AS question_count FROM content_items c LEFT JOIN generation_jobs j ON j.id=c.generation_job_id LEFT JOIN questions q ON q.source_content_id=c.id WHERE c.content_type IN ('article','lesson') GROUP BY c.id ORDER BY c.updated_at DESC,c.created_at DESC LIMIT 100").all();return Response.json({contents:rows.results});}

export async function POST(request:Request){const denied=await requireAdmin(request);if(denied)return denied;const body=await request.json().catch(()=>({})) as Record<string,unknown>,title=typeof body.title==="string"?body.title.trim():"",text=typeof body.text==="string"?body.text.trim():"",schoolLevel=body.schoolLevel==="P5"?"P5":"P6";if(!title||text.length<200)return Response.json({error:"title and at least 200 characters of text are required"},{status:400});const paragraphs=text.split(/\n\s*\n/).map(p=>p.replace(/\s+/g," ").trim()).filter(Boolean),env=await resolveIntegrations(getEnv());const dup=await duplicateSkip(env.DB,{contentType:"article",schoolLevel,scope:"global",title});if(dup.skipped)return Response.json({ok:true,status:"skipped",existingId:dup.existingId,existingStatus:dup.existingStatus});const material:AdaptedLearningMaterial={title,description:typeof body.description==="string"?body.description.trim():"Teacher-created learning material",topic:typeof body.topic==="string"?body.topic.trim():"General English",body:{summary:typeof body.description==="string"?body.description.trim():"",readingTime:Math.max(4,Math.round(text.split(/\s+/).length/150)),paragraphs,vocabulary:[],sourceNote:"Created in English Mastery Admin."},questions:[]};const id=await insertLearningMaterial(env.DB,{material,schoolLevel,status:"draft",skillIds:Array.isArray(body.skillIds)?body.skillIds.filter((x):x is string=>typeof x==="string"):[]});if(env.MODELBRIDGE_API_KEY&&env.MODELBRIDGE_CHAT_MODEL){await env.DB.prepare("UPDATE content_items SET status='generating',generation_stage='generating_questions',description=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(material.description,id).run();const jobId=await enqueueJob(env.DB,env,{jobType:"reading_questions",entityType:"content",entityId:id,request:{contentId:id,title,text,schoolLevel}});await env.DB.prepare("UPDATE content_items SET generation_job_id=? WHERE id=?").bind(jobId,id).run();return Response.json({ok:true,id,jobId,status:"generating"},{status:202});}return Response.json({ok:true,id,status:"draft"},{status:201});}
